export default [
  {
    id: 'purkinje',
    name: 'Purkinje cell',
    group: 'inhibitory',
    color: '#ff6b7d',
    tagline: 'The grand conductors sculpting all motor output from the cerebellar cortex.',
    analogy: 'The lead sculptor carving away rough stone until only smooth, graceful motion remains.',
    transmitter: 'gaba',
    where: ['cerebellum'],
    size: 'About 50 to 80 micrometres (0.06 mm) across the cell body',
    morph: { style: 'purkinje', seed: 44 },
    landmarks: ['soma', 'dendrites', 'spines', 'axon', 'terminals'],
    shape: {
      text: 'Purkinje cells are among the largest and most recognizable [[neuron|neurons]] in the brain. Each pear-shaped cell body supports a gigantic, flat fan of [[dendrite|dendrites]] that branches into a two-dimensional sheet, perpendicular to passing parallel fibres. A single downward [[axon]] carries the only output leaving the cerebellar [[cortex]], delivering powerful [[inhibitory]] braking to deep cerebellar nuclei.',
      bullets: [
        'Large pear-shaped soma containing an extensive protein-making apparatus.',
        'Massive dendritic tree forms a wide, flat fan squeezed into a two-dimensional plane.',
        'Covered in over 150,000 dendritic spines that receive parallel fibre connections.',
        'A single climbing fibre wraps around the main dendritic trunk like climbing ivy.',
      ],
    },
    fires: {
      text: 'Purkinje cells fire two distinct varieties of electrical signals. Thousands of parallel fibres drive steady simple spikes at high frequencies (50 to 100 Hertz). In contrast, an input from a single climbing fibre generates an explosive, multi-peaked complex spike, signaling a movement error and driving motor learning.',
      steps: [
        '1. Parallel fibres release [[glutamate]] onto distal dendritic spines, maintaining continuous simple spikes.',
        '2. A climbing fibre from the medulla releases [[glutamate]] along the primary dendritic trunk.',
        '3. Voltage-gated calcium channels open across the dendritic tree, generating an intense complex spike.',
        '4. High calcium levels trigger long-term depression at recently active parallel fibre [[synapses]], improving motor accuracy over time.',
      ],
    },
    chem: {
      text: 'Purkinje cells synthesize and release [[GABA]] to silence deep cerebellar targets. They express abundant metabotropic glutamate receptors (mGluR1) and calcium-permeable AMPA [[receptors]], which coordinate the synaptic plasticity required for motor learning.',
      receptors: ['AMPA', 'mGluR1', 'GABA-A'],
      modulatedBy: ['noradrenaline', 'serotonin', 'glutamate'],
    },
    breaks: {
      text: 'Damage to Purkinje cells removes the primary motor brake of the {{cerebellum}}, leaving voluntary movements clumsy and fragmented.',
      bullets: [
        'Alcohol selectively suppresses Purkinje cell firing, causing slurred speech, uncoordinated reaching, and unsteady walking.',
        'Autoimmune degeneration of Purkinje cells produces severe [[ataxia]], making smooth intentional actions impossible.',
        'Genetic mutations affecting Purkinje calcium channels cause episodic ataxias with sudden attacks of poor balance.',
      ],
    },
    diagram: 'cerebellar-circuit',
  },
  {
    id: 'stellate',
    name: 'Stellate cell',
    group: 'inhibitory',
    color: '#fb7185',
    tagline: 'The star-shaped local interneurons sharpening sensory borders and circuit timing.',
    analogy: 'A local sound engineer adjusting levels across nearby microphones so quiet instruments are not drowned out by drums.',
    transmitter: 'gaba',
    where: ['visual-cortex', 'somatosensory-cortex', 'cerebellum'],
    size: 'About 10 to 15 micrometres (0.012 mm) across the cell body',
    morph: { style: 'stellate', seed: 55 },
    landmarks: ['soma', 'dendrites', 'axon', 'terminals'],
    shape: {
      text: 'Stellate cells are compact, star-like [[interneuron|interneurons]] with [[dendrite|dendrites]] that radiate outward in all directions like the rays of a star. In sensory areas of the [[cortex]], they reside in layer 4 to receive incoming thalamic signals and provide rapid feedforward inhibition that sharpens sensory borders. In the {{cerebellum}}, they synapse directly onto the branches of [[Purkinje cell|Purkinje cells]].',
      bullets: [
        'Small polygonal or spherical cell body without a preferred vertical orientation.',
        'Radiating dendrites extend symmetrically in a sphere around the cell body.',
        'Axon arborizes locally within a few hundred micrometres of the soma.',
        'Forms inhibitory symmetric [[synapses]] onto nearby dendrites and spines.',
      ],
    },
    fires: {
      text: 'Stellate cells respond with swift, non-adapting trains of action potentials when excited. In the sensory [[cortex]], they fire almost instantaneously upon receiving input from the {{thalamus}}, immediately dampening neighboring cells to ensure that sensory signals remain sharp and focused in time.',
      steps: [
        '1. Thalamic axons or parallel fibres release [[glutamate]] onto AMPA [[receptors]] on stellate dendrites.',
        '2. Rapid sodium influx depolarizes the compact cell body within half a millisecond.',
        '3. Fast-acting potassium channels quickly reset the cell, allowing it to fire repeatedly at high rates without slowing down.',
        '4. Axon terminals release [[GABA]] onto target dendrites, restricting excitation to a brief, precise window.',
      ],
    },
    chem: {
      text: 'Stellate cells use [[GABA]] to inhibit target cells through GABA-A [[receptors]]. They express high-affinity AMPA and NMDA [[receptors]] to capture incoming sensory signals and are tuned by [[acetylcholine]] to adjust circuit sensitivity.',
      receptors: ['AMPA', 'NMDA', 'GABA-A'],
      modulatedBy: ['acetylcholine', 'noradrenaline', 'serotonin'],
    },
    breaks: {
      text: 'Impaired stellate inhibition blurs sensory discrimination and destabilizes local cortical timing.',
      bullets: [
        'Loss of feedforward inhibition in the {{visual-cortex}} broadens visual receptive fields, degrading edge and contrast detection.',
        'Deficits in cortical inhibitory interneurons contribute to sensory hypersensitivity in autism spectrum conditions.',
        'Weakened cerebellar stellate inhibition disrupts the microsecond timing needed for fine finger movements.',
      ],
    },
    diagram: 'cortical-column',
  },
  {
    id: 'basket',
    name: 'Basket cell',
    group: 'inhibitory',
    color: '#f87171',
    tagline: 'The somatic bouncers clamping the cell bodies of principal neurons.',
    analogy: 'A sturdy wicker basket wrapping tightly around an apple, physically guarding the gate where all output begins.',
    transmitter: 'gaba',
    where: ['hippocampus', 'cerebellum', 'prefrontal-cortex'],
    size: 'About 20 to 30 micrometres (0.025 mm) across the cell body',
    morph: { style: 'basket', seed: 62 },
    landmarks: ['soma', 'dendrites', 'axon', 'terminals'],
    shape: {
      text: 'Basket cells are powerful inhibitory [[interneuron|interneurons]] named for their striking axonal endings. Their horizontal [[axon]] branches travel toward neighboring [[pyramidal cell|pyramidal cells]] or [[Purkinje cell|Purkinje cells]], branching into dense pericellular nests that wrap around the target cell bodies like woven baskets. This position right around the cell body gives basket cells decisive control over whether the target cell can fire.',
      bullets: [
        'Medium-sized multipolar soma with smooth or sparsely branched dendrites.',
        'Axon arbor forms specialized basket-like terminal nests embracing target cell bodies.',
        'Long horizontal axon collaterals branch outward to embrace several neighboring target cells.',
        'In the {{cerebellum}}, forms specialized pinceau structures that wrap the axon initial segment of Purkinje cells.',
      ],
    },
    fires: {
      text: 'Basket cells are classic fast-spiking [[interneuron|interneurons]]. They fire brief, needle-sharp action potentials at very high frequencies without tiring. By firing together in rhythmic volleys, they synchronize thousands of neighboring pyramidal cells, pacing the brain\'s gamma waves (30 to 80 Hertz) that support active thinking.',
      steps: [
        '1. Broad excitatory inputs from local pyramidal cells excite AMPA [[receptors]] on basket dendrites.',
        '2. Rapid depolarization triggers an ultra-brief [[action potential]] lasting less than half a millisecond.',
        '3. High-frequency spike trains deliver substantial pulses of [[GABA]] straight onto target cell bodies.',
        '4. Chloride rushes into target somas, clamping their voltage near resting potential and pacing their firing into gamma rhythms.',
      ],
    },
    chem: {
      text: 'Basket cells deliver [[GABA]] directly to somatic GABA-A [[receptors]]. Their terminals express cannabinoid CB1 [[receptors]], which allow target pyramidal cells to release retrograde endocannabinoids that temporarily turn down basket cell braking during intense learning.',
      receptors: ['AMPA', 'NMDA', 'GABA-A'],
      modulatedBy: ['acetylcholine', 'serotonin', 'dopamine'],
    },
    breaks: {
      text: 'Failure of basket cell pacing disrupts rhythmic coordination across large brain networks, causing cognitive disorganization and seizures.',
      bullets: [
        'Loss of basket cell function in the {{prefrontal-cortex}} impairs gamma oscillations, a core feature of cognitive deficits in schizophrenia.',
        'Reduced perisomatic inhibition in the {{hippocampus}} allows runaway pyramidal excitation, triggering temporal lobe seizures.',
        'Destruction of basket cells impairs sensory gating, overwhelming the brain with unfiltered sensory inputs.',
      ],
    },
  },
  {
    id: 'chandelier',
    name: 'Chandelier cell',
    group: 'inhibitory',
    color: '#f43f5e',
    tagline: 'The master circuit breakers clamping the exact trigger point of pyramidal cells.',
    analogy: 'The master electrical switch for an entire building, capable of shutting off all outgoing current with one click.',
    transmitter: 'gaba',
    where: ['prefrontal-cortex', 'temporal-lobe'],
    size: 'About 15 to 25 micrometres (0.02 mm) across the cell body',
    morph: { style: 'chandelier', seed: 73 },
    landmarks: ['soma', 'dendrites', 'axon', 'terminals'],
    shape: {
      text: 'Chandelier cells are among the most specialized inhibitory [[interneuron|interneurons]] in the cerebral [[cortex]]. Their [[axon]] branches horizontally and drops dozens of vertical strings of synaptic boutons that hang down like crystal candles from a chandelier. Each vertical string (or cartridge) specifically clamps the axon initial segment of a different [[pyramidal cell]], the exact spot where action potentials are generated.',
      bullets: [
        'Multipolar soma situated primarily in cortical layers 2, 3, or 5.',
        'Axonal arbor features dozens of vertical strings of boutons known as cartridges.',
        'Each cartridge wraps the axon initial segment of a neighboring pyramidal neuron.',
        'A single chandelier cell can veto the electrical output of hundreds of pyramidal cells at once.',
      ],
    },
    fires: {
      text: 'Chandelier cells fire high-frequency trains of action potentials when stimulated by cortical networks. Because their synapses sit directly on the axon initial segment, where sodium channels are concentrated at highest density, their [[inhibitory]] release can completely veto outgoing signals before they ever leave the cell body.',
      steps: [
        '1. Excitatory inputs from local pyramidal cells depolarize the chandelier dendrites with [[glutamate]].',
        '2. The chandelier cell fires a high-frequency barrage of action potentials.',
        '3. Depolarization reaches the vertical candle cartridges hanging along pyramidal axon initial segments.',
        '4. Massive [[GABA]] release opens chloride channels, short-circuiting electrical impulses right at their birth point.',
      ],
    },
    chem: {
      text: 'Chandelier cells release [[GABA]] onto specialized GABA-A [[receptors]] that contain alpha-2 subunits, clustered densely at the axon initial segment. They express parvalbumin and receive modulatory inputs from [[dopamine]] and [[acetylcholine]] pathways.',
      receptors: ['AMPA', 'NMDA', 'GABA-A'],
      modulatedBy: ['dopamine', 'acetylcholine', 'noradrenaline'],
    },
    breaks: {
      text: 'Because chandelier cells control the final trigger point of cortical output, their loss removes the ultimate safety brake on cortical excitability.',
      bullets: [
        'Selective reduction of chandelier axon cartridges in the {{prefrontal-cortex}} is linked to thought fragmentation and working memory failure in schizophrenia.',
        'Damage to axo-axonic synapses permits uncontrolled pyramidal discharge, triggering focal neocortical epilepsy.',
        'Early developmental disruptions of chandelier cell migration are associated with severe cognitive disorders.',
      ],
    },
  },
  {
    id: 'msn',
    name: 'Medium spiny neuron',
    group: 'inhibitory',
    color: '#be185d',
    tagline: 'The primary decision hubs choosing which movements and habits go forward.',
    analogy: 'The ballot counters in a parliament of desires, tallying votes from the cortex before passing the winning law to motor circuits.',
    transmitter: 'gaba',
    where: ['striatum', 'nucleus-accumbens'],
    size: 'About 15 to 20 micrometres (0.018 mm) across the cell body',
    morph: { style: 'msn', seed: 84 },
    landmarks: ['soma', 'dendrites', 'spines', 'axon', 'terminals'],
    shape: {
      text: 'Medium spiny [[neuron|neurons]] (MSNs) make up roughly 95 percent of all cells in the {{striatum}} and {{nucleus-accumbens}}. A medium-sized spherical cell body radiates four to eight primary [[dendrite|dendrites]] that quickly become blanketed in over 10,000 dendritic spines. A long [[axon]] travels out of the striatum to inhibit downstream basal ganglia nuclei, steering action proposals into physical reality.',
      bullets: [
        'Round cell body embedded within the dense grey matter of the basal ganglia.',
        'Dendritic branches radiate into a sphere roughly a quarter of a millimetre across.',
        'Extraordinary spine density captures convergent signals from the [[cortex]] and {{thalamus}}.',
        'Split into direct pathway cells (promoting movement) and indirect pathway cells (braking movement).',
      ],
    },
    fires: {
      text: 'Medium spiny neurons spend most of their time in a silent down-state near minus 80 millivolts, held down by specialized potassium channels. They only rise into a depolarized up-state and fire when hundreds of cortical inputs land simultaneously, ensuring that only decisive, coordinated plans trigger action.',
      steps: [
        '1. In the down-state, inward rectifier potassium channels keep the cell silent and protected from noise.',
        '2. Synchronized [[glutamate]] inputs from the [[cortex]] and {{thalamus}} depolarize thousands of spines.',
        '3. The cell transitions into a depolarized up-state near minus 50 millivolts.',
        '4. [[Dopamine]] tips the balance: boosting direct pathway cells via D1 receptors while quieting indirect pathway cells via D2 receptors.',
      ],
    },
    chem: {
      text: 'MSNs release [[GABA]] along with peptide messengers like substance P or enkephalin. Their excitability is balanced by [[dopamine]] released from the {{substantia-nigra}} and {{vta}}, acting on D1 or D2 [[receptors]] to encourage or discourage selected movements.',
      receptors: ['AMPA', 'NMDA', 'D1', 'D2', 'mGluR'],
      modulatedBy: ['dopamine', 'acetylcholine', 'serotonin'],
    },
    breaks: {
      text: 'Damage to medium spiny neurons strikes at the core of movement selection, habit formation, and reward valuation.',
      bullets: [
        'Huntington disease causes genetic degeneration of striatal MSNs, unleashing uncontrolled dance-like chorea and emotional changes.',
        'Loss of dopamine inputs to MSNs in Parkinson disease leaves indirect MSNs chronically overactive, locking the body in rigidity and poverty of movement.',
        'Compulsive drug use alters synaptic spine structure on MSNs in the {{nucleus-accumbens}}, entrenching addictive habits.',
      ],
    },
    diagram: 'basal-ganglia',
  },
  {
    id: 'itc',
    name: 'Intercalated cell',
    group: 'inhibitory',
    color: '#f43f5e',
    tagline: 'The GABAergic gatekeepers clamping central output neurons to allow fear extinction.',
    analogy: 'The physical safety catch on an emergency alarm switch, keeping the siren quiet until danger is verified.',
    transmitter: 'gaba',
    where: ['amygdala'],
    size: 'About 10 to 15 micrometres (0.012 mm) across the cell body',
    morph: { style: 'stellate', seed: 68 },
    landmarks: ['soma', 'dendrites', 'axon', 'terminals'],
    shape: {
      text: 'Intercalated cells are densely packed inhibitory [[interneuron|interneurons]] clustered in thin fibrous capsules between the basolateral and central nuclei of the {{amygdala}}. Their compact, radiating [[dendrite|dendrites]] capture incoming signals from the [[prefrontal cortex]], while dense local [[axon|axons]] project directly onto central amygdala projection cells.',
      bullets: [
        'Small spherical soma nested within white matter paracapsular islands.',
        'Compact dendritic arbor radiating locally to catch prefrontal and basolateral inputs.',
        'Dense inhibitory axonal projections that terminate on central amygdala output neurons.',
        'Organized in clusters that act as a gatekeeper between threat assessment and panic execution.',
      ],
    },
    fires: {
      text: 'Intercalated cells fire rapid bursts of action potentials when driven by top-down safety signals. When the [[infralimbic cortex]] detects that a formerly dangerous cue is now harmless, its excitatory projections activate these cells, triggering an immediate wave of [[GABA]] that silences outgoing fear signals.',
      steps: [
        '1. Glutamate released from the prefrontal cortex binds AMPA and NMDA receptors on intercalated dendrites.',
        '2. Rapid depolarization triggers high-frequency action potentials across the compact soma.',
        '3. Impulses travel along short axons into the central amygdala.',
        '4. Massive GABA release opens chloride channels on central output neurons, clamping the panic switch shut.',
      ],
    },
    chem: {
      text: 'Intercalated cells release [[GABA]] to inhibit central amygdala targets. They express high-affinity AMPA and NMDA [[receptors]] to capture cortical inputs, dopamine D1 receptors that tune their excitability, and are sensitive to circulating [[glucocorticoid|glucocorticoids]].',
      receptors: ['AMPA', 'NMDA', 'GABA-A', 'D1'],
      modulatedBy: ['dopamine', 'cortisol', 'noradrenaline'],
    },
    breaks: {
      text: 'Failure or suppression of intercalated cell inhibition removes the primary safety brake on fear output, keeping panic alarms blaring even in safe settings.',
      bullets: [
        'Chronic stress elevates glucocorticoids that weaken prefrontal inputs, preventing intercalated cells from engaging the fear brake.',
        'Impaired extinction learning leaves traumatic memories permanently active, a core mechanism of post-traumatic stress disorder.',
        'Deficits in intercalated GABA release contribute to generalized anxiety and persistent phobias.',
      ],
    },
    diagram: 'fear-circuit',
  },
];
