// Fast amino acid neurotransmitters: Glutamate and GABA.

export default [
  {
    id: 'glutamate',
    name: 'Glutamate',
    group: 'fast',
    color: '#ffcf6b',
    tagline: 'The primary excitatory neurotransmitter that drives fast brain signals and memory storage.',
    analogy: 'The green light of the nervous system that tells the next neuron to go.',
    synapse: 'glutamate',
    madeFrom: 'glutamine',
    madeIn: ['thalamus', 'hippocampus', 'prefrontal-cortex', 'motor-cortex'],
    overview: {
      text: 'Glutamate is the most common chemical messenger in the brain. Over half of all synapses release it to stimulate connected neurons. It enables point to point sensory processing, coordinates movement commands, and alters synaptic strength during learning.',
      bullets: [
        'Main excitatory messenger throughout the entire cerebral cortex and hippocampus.',
        'Acts in less than a millisecond through ligand-gated ion channels.',
        'Excess levels outside cells are rapidly cleared to protect against excitotoxicity.',
      ],
    },
    tracts: [
      {
        id: 'corticostriatal',
        name: 'Corticostriatal projection',
        from: 'motor-cortex',
        to: ['striatum'],
        job: 'Passing motor commands and action proposals into basal ganglia selection circuits',
        text: 'Pyramidal cells in the cortex send fast excitatory fibres into the striatum. These inputs propose actions and habits that the basal ganglia evaluate before movement begins.',
        whenItFails: 'Disrupted signalling contributes to difficulty selecting and initiating intentional actions.',
        whenBlocked: 'Blocking these pathways halts voluntary movement initiation and motor learning.',
      },
      {
        id: 'thalamocortical',
        name: 'Thalamocortical relay',
        from: 'thalamus',
        to: ['somatosensory-cortex', 'visual-cortex'],
        job: 'Relaying sensory information from peripheral receptors to cortical sensory processing areas',
        text: 'Thalamic relay neurons release glutamate into sensory cortex layers. Each burst preserves the timing and structure of incoming sight, touch, and sound.',
        whenItFails: 'Impaired relay leads to sensory loss, numbness, or central pain syndromes.',
        whenBlocked: 'General anaesthetics and dissociative drugs dampen these relays to induce unconsciousness.',
      },
    ],
    density: {
      'cerebellum': 0.95,
      'hippocampus': 0.9,
      'prefrontal-cortex': 0.85,
      'motor-cortex': 0.85,
      'striatum': 0.8,
      'thalamus': 0.75,
    },
    receptors: [
      {
        id: 'AMPA',
        family: 'Ionotropic ion channel',
        effect: 'excite',
        where: ['prefrontal-cortex', 'hippocampus', 'cerebellum'],
        text: 'Opens rapidly when glutamate binds, allowing sodium ions to enter and trigger action potentials within milliseconds.',
      },
      {
        id: 'NMDA',
        family: 'Coincidence detector channel',
        effect: 'excite',
        where: ['hippocampus', 'prefrontal-cortex', 'striatum'],
        text: 'Permits calcium to enter only when the receiving neuron is already depolarised, forming the molecular foundation of synaptic plasticity.',
      },
      {
        id: 'mGluR',
        family: 'Metabotropic G-protein coupled',
        effect: 'modulate',
        where: ['cerebellum', 'thalamus', 'striatum'],
        text: 'Triggers intracellular biochemical cascades that slowly adjust ion channel sensitivity and transmitter release.',
      },
    ],
    life: {
      made: 'Glutamine is converted into glutamate inside presynaptic terminals by the enzyme glutaminase.',
      packed: 'Vesicular glutamate transporters (VGLUT) pump glutamate into synaptic vesicles.',
      released: 'An arriving action potential triggers calcium influx, causing vesicles to fuse and release glutamate.',
      binds: 'Glutamate crosses the synaptic cleft and binds postsynaptic AMPA and NMDA receptor channels.',
      cleared: 'Astrocytes rapidly take up glutamate from the cleft using excitatory amino acid transporters (EAAT).',
      clearedBy: 'astrocyte',
    },
    drugs: [
      {
        id: 'ketamine',
        name: 'Ketamine',
        acts: 'receptor-block',
        target: 'NMDA',
        text: 'Blocks the open pore of NMDA receptors, causing dissociative anaesthesia and rapid antidepressant effects.',
      },
      {
        id: 'memantine',
        name: 'Memantine',
        acts: 'receptor-block',
        target: 'NMDA',
        text: 'Binds NMDA channels under pathological conditions to prevent toxic calcium influx in Alzheimer disease.',
      },
      {
        id: 'ampa',
        name: 'AMPA agonist',
        acts: 'receptor-mimic',
        target: 'AMPA',
        text: 'Directly mimics glutamate at AMPA receptors, triggering immediate sodium entry and rapid depolarization.',
      },
    ],
    breaks: {
      text: 'Because glutamate excites neurons, too much or too little quickly damages brain function.',
      bullets: [
        'Excitotoxicity: during a stroke, starved cells dump glutamate, overloading neighbours with calcium and killing them.',
        'Epilepsy: an imbalance between glutamate excitation and GABA inhibition triggers spreading electrical seizures.',
        'Schizophrenia: altered NMDA receptor signalling is thought to contribute to cognitive and perceptual disturbances.',
      ],
    },
    tryIt: 'Touch a tabletop. The sensation travels up your spinal cord and through your thalamus to your sensory cortex using glutamate at every synaptic handover.',
  },
  {
    id: 'gaba',
    name: 'GABA',
    group: 'fast',
    color: '#ff6b7d',
    tagline: 'The primary inhibitory neurotransmitter that calms neural firing and maintains circuit balance.',
    analogy: 'The braking pedal of the nervous system that prevents electrical activity from running out of control.',
    synapse: 'gaba',
    madeFrom: 'glutamate',
    madeIn: ['striatum', 'globus-pallidus', 'cerebellum'],
    overview: {
      text: 'GABA (gamma-aminobutyric acid) is the primary inhibitory messenger in the mature brain. Produced by interneurons and projection cells, it applies precise pauses and rhythms to neural circuits. Without GABA, unchecked excitation would cascade into continuous seizures.',
      bullets: [
        'Present in roughly one fifth of all brain synapses, especially within local interneurons.',
        'Opens chloride channels to lower the electrical potential inside the receiving cell.',
        'Tunes rhythms like gamma oscillations that bind perceptions across brain regions.',
      ],
    },
    tracts: [
      {
        id: 'striatopallidal',
        name: 'Striatopallidal pathway',
        from: 'striatum',
        to: ['globus-pallidus'],
        job: 'Inhibiting pallidal brake cells to permit or restrain planned movements',
        text: 'Medium spiny neurons in the striatum project directly to the globus pallidus. By releasing GABA, they pause tonic inhibition and allow intended movements to pass through the thalamus.',
        whenItFails: 'Degeneration of striatal GABA cells produces uncontrolled flailing movements in Huntington disease.',
        whenBlocked: 'Blocking GABA release here causes severe motor spasms and muscular rigidity.',
      },
      {
        id: 'purkinje-output',
        name: 'Purkinje cell projection',
        from: 'cerebellum',
        to: ['thalamus'],
        job: 'Providing timed inhibitory sculpting to smooth motor coordination and balance',
        text: 'Purkinje cells form the sole output of the cerebellar cortex. They send strong GABAergic inhibition into deep cerebellar nuclei and onward toward motor relays.',
        whenItFails: 'Loss of Purkinje cells leads to cerebellar ataxia, jerky limb motion, and unsteady gait.',
        whenBlocked: 'Disrupting Purkinje inhibition causes tremors and severe overshooting during reaching.',
      },
    ],
    density: {
      'globus-pallidus': 0.95,
      'striatum': 0.9,
      'cerebellum': 0.85,
      'prefrontal-cortex': 0.8,
      'thalamus': 0.75,
      'hippocampus': 0.7,
    },
    receptors: [
      {
        id: 'GABA-A',
        family: 'Ionotropic chloride channel',
        effect: 'inhibit',
        where: ['prefrontal-cortex', 'cerebellum', 'thalamus'],
        text: 'Opens immediately when GABA binds, letting negative chloride ions rush in to hyperpolarize the cell within milliseconds.',
      },
      {
        id: 'GABA-B',
        family: 'Metabotropic G-protein coupled',
        effect: 'inhibit',
        where: ['hippocampus', 'striatum', 'globus-pallidus'],
        text: 'Couples to potassium channels and inhibits calcium channels, producing a prolonged, slow inhibitory wave.',
      },
    ],
    life: {
      made: 'Glutamate is converted into GABA by the enzyme glutamic acid decarboxylase (GAD).',
      packed: 'Vesicular inhibitory amino acid transporters (VGAT) concentrate GABA into synaptic vesicles.',
      released: 'Terminal depolarization drives calcium entry, triggering vesicle fusion and GABA release into the gap.',
      binds: 'GABA binds GABA-A and GABA-B receptors on the receiving cell, stabilizing membrane potential.',
      cleared: 'GABA transporters (GAT) on neighbouring astrocytes and presynaptic terminals remove GABA from the cleft.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'diazepam',
        name: 'Diazepam (Valium)',
        acts: 'boost-receptor',
        target: 'GABA-A',
        text: 'Binds an allosteric site on GABA-A receptors, boosting channel opening frequency to reduce anxiety and muscle tension.',
      },
      {
        id: 'baclofen',
        name: 'Baclofen',
        acts: 'receptor-mimic',
        target: 'GABA-B',
        text: 'Directly stimulates GABA-B receptors in the spinal cord to suppress muscle spasticity.',
      },
      {
        id: 'tiagabine',
        name: 'Tiagabine',
        acts: 'reuptake-block',
        target: 'GAT-1',
        text: 'Inhibits GABA transporter GAT-1, leaving natural GABA in the synapse longer to control epileptic seizures.',
      },
    ],
    breaks: {
      text: 'Insufficient GABA activity leads to runaway electrical excitation, while excessive inhibition sedates the brain.',
      bullets: [
        'Anxiety and panic: reduced GABA receptor sensitivity makes threat circuits in the amygdala hyperactive.',
        'Insomnia: poor GABA tone impairs the thalamic sleep gate, keeping cortex awake.',
        'Seizure disorders: sudden drops in GABAergic restraint allow synchronous electrical storms to propagate.',
      ],
    },
    tryIt: 'Take a slow, deep breath and let your shoulders drop. Relaxation techniques increase inhibitory tone across brainstem and cortical networks, dampening stress circuits.',
  },
];
