// Fast amino acid neurotransmitters: Glutamate and GABA.

export default [
  {
    id: 'glutamate',
    name: 'Glutamate',
    group: 'fast',
    color: '#ffcf6b',
    tagline: 'The main go signal of the brain, driving fast thoughts and helping build memories.',
    analogy: 'The accelerator pedal that urges the next neuron to fire.',
    synapse: 'glutamate',
    madeFrom: 'glutamine',
    madeIn: ['thalamus', 'hippocampus', 'prefrontal-cortex', 'motor-cortex'],
    overview: {
      text: 'Glutamate is the most common chemical messenger in your brain. More than half of all [[synapse|synapses]] release it to pass messages to connected cells. It carries fast sensory impressions, passes movement commands to muscles, and strengthens connections when you learn something new.',
      bullets: [
        'Main [[excitatory]] messenger across the entire cerebral [[cortex]] and {{hippocampus}}.',
        'Acts in less than a thousandth of a second through tiny molecular channels.',
        'Rapidly cleared by partner cells so it does not build up to harmful levels.',
      ],
    },
    tracts: [
      {
        id: 'corticostriatal',
        name: 'Corticostriatal projection',
        from: 'motor-cortex',
        to: ['striatum'],
        job: 'Passing action plans from the cortex into movement selection circuits',
        text: 'Pyramidal neurons in the cortex send fast excitatory fibres into the {{striatum}}. These signals propose actions, like reaching for a cup, which the basal ganglia evaluate before you move.',
        whenItFails: 'Trouble selecting and starting intentional movements.',
        whenBlocked: 'Halts voluntary movement and motor learning.',
      },
      {
        id: 'thalamocortical',
        name: 'Thalamocortical relay',
        from: 'thalamus',
        to: ['somatosensory-cortex', 'visual-cortex'],
        job: 'Relaying sensory information from the senses to the cortex',
        text: 'Neurons in the {{thalamus}} release glutamate into sensory cortex layers. Each brief burst preserves the timing and fine details of incoming sight, touch, and sound.',
        whenItFails: 'Sensory loss, numbness, or chronic pain.',
        whenBlocked: 'General anaesthetics dampen these relays to induce unconsciousness.',
      },
    ],
    density: {
      'cerebellum': 0.95,
      'hippocampus': 0.9,
      'prefrontal-cortex': 0.85,
      'motor-cortex': 0.85,
      'striatum': 0.8,
      'thalamus': 0.75,
    },
    receptors: [
      {
        id: 'AMPA',
        family: 'Ionotropic ion channel',
        effect: 'excite',
        where: ['prefrontal-cortex', 'hippocampus', 'cerebellum'],
        text: 'Opens in a flash when glutamate lands on it, letting positive sodium ions rush in to trigger an [[action potential]].',
      },
      {
        id: 'NMDA',
        family: 'Coincidence detector channel',
        effect: 'excite',
        where: ['hippocampus', 'prefrontal-cortex', 'striatum'],
        text: 'Acts like a molecular gatekeeper that opens only when the receiving cell is already active, helping lock in long-term memories.',
      },
      {
        id: 'mGluR',
        family: 'Metabotropic G-protein coupled',
        effect: 'modulate',
        where: ['cerebellum', 'thalamus', 'striatum'],
        text: 'Works more slowly through chemical cascades inside the cell, tuning how sensitive the neuron stays over seconds.',
      },
    ],
    life: {
      made: 'Cells build glutamate from the amino acid glutamine inside the sending terminal.',
      packed: 'Transporter proteins pump glutamate molecules into tiny membrane bubbles called vesicles.',
      released: 'An arriving electrical spike lets calcium flood in, fusing the bubbles with the cell edge to spill glutamate into the gap.',
      binds: 'Glutamate floats across the tiny synaptic gap and locks into AMPA and NMDA receptor gates.',
      cleared: 'Nearby star-shaped glia (astrocytes) mop up glutamate from the gap so signals stay crisp.',
      clearedBy: 'astrocyte',
    },
    drugs: [
      {
        id: 'ketamine',
        name: 'Ketamine',
        acts: 'receptor-block',
        target: 'NMDA',
        text: 'Blocks the open pore of NMDA receptors, causing dream-like anaesthesia and rapid relief in depression.',
      },
      {
        id: 'memantine',
        name: 'Memantine',
        acts: 'receptor-block',
        target: 'NMDA',
        text: 'Blocks overactive NMDA channels to protect neurons from toxic calcium overload in Alzheimer disease.',
      },
      {
        id: 'ampa',
        name: 'AMPA agonist',
        acts: 'receptor-mimic',
        target: 'AMPA',
        text: 'Mimics glutamate at AMPA receptors, triggering immediate sodium entry and rapid firing.',
      },
    ],
    breaks: {
      text: 'Because glutamate excites neurons, keeping the right balance is essential. Too much can overstimulate cells to death, while too little slows brain traffic to a crawl.',
      bullets: [
        'Excitotoxicity: during a stroke, starved cells dump glutamate, overexciting neighbours with calcium until they die.',
        'Seizures: if excitation overwhelms inhibitory braking, electrical storms spread across circuits.',
        'Filtering trouble: altered receptor signalling can disturb how circuits filter everyday sights and sounds.',
      ],
    },
    tryIt: 'Tap your fingers on a desk. The sensation travels up your arm, through your {{thalamus}}, and into your {{somatosensory-cortex}}, passing through glutamate synapses at every step.',
  },
  {
    id: 'gaba',
    name: 'GABA',
    group: 'fast',
    color: '#ff6b7d',
    tagline: 'The main calming messenger of the brain, keeping neural activity balanced and under control.',
    analogy: 'The brake pedal that stops electrical activity from running away into a storm.',
    synapse: 'gaba',
    madeFrom: 'glutamate',
    madeIn: ['striatum', 'globus-pallidus', 'cerebellum'],
    overview: {
      text: 'GABA is the chief inhibitory messenger in the adult brain. Released by local [[interneuron|interneurons]] and output cells, it puts precise pauses on circuits and keeps excitation in check. Without GABA, unchecked firing would rapidly spiral into continuous seizures.',
      bullets: [
        'Used at roughly one in five brain synapses, especially by local timing cells.',
        'Opens molecular gates that let negative chloride ions in, quieting the receiving cell.',
        'Shapes natural brain rhythms that help different areas coordinate their work.',
      ],
    },
    tracts: [
      {
        id: 'striatopallidal',
        name: 'Striatopallidal pathway',
        from: 'striatum',
        to: ['globus-pallidus'],
        job: 'Braking unwanted competing actions to keep movements precise and smooth',
        text: 'Cells in the {{striatum}} send inhibitory fibres to the {{globus-pallidus}} as part of the indirect pathway. By releasing GABA, they hold back competing or unwanted muscle contractions so that only intended actions occur.',
        whenItFails: 'Loss of these cells removes this essential brake, causing the uncontrolled jerking movements of Huntington disease.',
        whenBlocked: 'Severe muscle spasms and rigid stiffness.',
      },
      {
        id: 'purkinje-output',
        name: 'Purkinje cell projection',
        from: 'cerebellum',
        to: ['thalamus'],
        job: 'Sculpting motor signals to keep balance and coordination smooth',
        text: 'Large Purkinje cells form the only output leaving the cerebellar cortex, firing timed bursts of GABA into deep cerebellar nuclei, which then relay sculpted motor signals onward to the {{thalamus}}.',
        whenItFails: 'Causes clumsiness, slurred speech, and unsteady walking ([[ataxia]]).',
        whenBlocked: 'Causes tremors and overshooting when reaching for an object.',
      },
    ],
    density: {
      'globus-pallidus': 0.95,
      'striatum': 0.9,
      'cerebellum': 0.85,
      'prefrontal-cortex': 0.8,
      'thalamus': 0.75,
      'hippocampus': 0.7,
    },
    receptors: [
      {
        id: 'GABA-A',
        family: 'Ionotropic chloride channel',
        effect: 'inhibit',
        where: ['prefrontal-cortex', 'cerebellum', 'thalamus'],
        text: 'Opens instantly when GABA binds, letting negative chloride ions rush in to quiet the neuron within milliseconds.',
      },
      {
        id: 'GABA-B',
        family: 'Metabotropic G-protein coupled',
        effect: 'inhibit',
        where: ['hippocampus', 'striatum', 'globus-pallidus'],
        text: 'Works more slowly through internal cascades, opening potassium channels to create a gentle, prolonged wave of calm.',
      },
    ],
    life: {
      made: 'Cells make GABA by trimming an acid group off glutamate using a dedicated enzyme.',
      packed: 'Transporter pumps pack GABA molecules tightly into synaptic vesicles.',
      released: 'An incoming electrical pulse triggers calcium entry, causing vesicles to fuse and release GABA into the gap.',
      binds: 'GABA crosses the gap and binds to GABA-A and GABA-B receptors, holding the cell back from firing.',
      cleared: 'Transporter proteins on terminals and helper glia vacuum GABA out of the gap to reset the circuit.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'diazepam',
        name: 'Diazepam (Valium)',
        acts: 'boost-receptor',
        target: 'GABA-A',
        text: 'Helps GABA bind more tightly to GABA-A receptors, calming anxiety, relaxing muscles, and stopping seizures.',
      },
      {
        id: 'baclofen',
        name: 'Baclofen',
        acts: 'receptor-mimic',
        target: 'GABA-B',
        text: 'Directly activates GABA-B receptors in the spinal cord to loosen tight, spastic muscles.',
      },
      {
        id: 'tiagabine',
        name: 'Tiagabine',
        acts: 'reuptake-block',
        target: 'GAT-1',
        text: 'Blocks the GABA transporter, leaving natural GABA in the gap longer to curb seizures.',
      },
    ],
    breaks: {
      text: 'Without enough GABA, electrical activity can run wild. Too much inhibition, on the other hand, slows thinking and makes you drowsy.',
      bullets: [
        'Anxiety and panic: lowered GABA sensitivity leaves alarm circuits in the {{amygdala}} overactive.',
        'Insomnia: weak GABA braking fails to quiet the thalamus, keeping the cortex awake at night.',
        'Seizures: sudden drops in GABA restraint let synchronous electrical waves tear through circuits.',
      ],
    },
    tryIt: 'Take a slow, deep breath and let your shoulders drop. Deep breathing engages brainstem circuits that increase inhibitory GABA tone, calming your heart rate and easing tension.',
  },
];
