// Hormones: circulating messengers carried in the bloodstream.
// They coordinate body-wide physiology over minutes, hours, and days.

export default [
  {
    id: 'cortisol',
    name: 'Cortisol',
    group: 'hormone',
    color: '#f59e0b',
    tagline: 'Mobilises energy, sharpens alertness under stress, and quiets inflammation.',
    analogy: 'An emergency budget director reallocating all available funds toward immediate survival.',
    madeFrom: 'cholesterol',
    madeIn: ['adrenal'],
    timescale: '20 minutes to several hours',
    overview: {
      text: 'Cortisol is the primary glucocorticoid stress hormone in humans, released by the adrenal cortex above the kidneys. While adrenaline prepares the body for split-second reflexes, cortisol coordinates the prolonged metabolic and neural response to challenges. It liberates glucose into circulation, crosses the blood-brain barrier to prime amygdala threat encoding, and temporarily dials down energy-expensive maintenance like digestion and immune swelling.',
      bullets: [
        'Follows a daily circadian rhythm, peaking roughly 30 to 45 minutes after waking to help you start the day.',
        'Mobilizes glucose from liver stores and fatty acids to provide steady muscular and neural fuel.',
        'Crosses the blood-brain barrier to bind receptors in the amygdala, lowering firing thresholds and accelerating threat conditioning.',
        'Suppresses non-essential inflammation and immune cell proliferation during acute stress emergencies.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'CRH (Corticotropin-releasing hormone)',
        via: 'portal',
        text: 'The {{hypothalamus}} detects physical or emotional stress and releases CRH into tiny hypophyseal portal capillaries.',
      },
      {
        from: 'pituitary',
        to: 'adrenal',
        carries: 'ACTH (Adrenocorticotropic hormone)',
        via: 'blood',
        text: 'The anterior {{pituitary}} secretes ACTH into systemic circulation, which travels through the bloodstream down to the adrenal glands.',
      },
      {
        from: 'adrenal',
        to: 'heart',
        carries: 'Cortisol',
        via: 'blood',
        text: 'The adrenal cortex releases cortisol into general circulation, sustaining vascular tone and tuning brain networks for extended challenges.',
      },
    ],
    feedback: [
      {
        from: 'adrenal',
        to: ['hypothalamus', 'hippocampus'],
        text: 'Circulating cortisol crosses the blood-brain barrier and binds receptors in the {{hippocampus}} and {{hypothalamus}}, shutting off further CRH release to end the stress response.',
      },
    ],
    density: {
      'hippocampus': 0.9,
      'hypothalamus': 0.85,
      'prefrontal-cortex': 0.75,
      'amygdala': 0.8,
    },
    receptors: [
      {
        id: 'GR',
        family: 'Glucocorticoid receptor',
        effect: 'modulate',
        where: ['hippocampus', 'prefrontal-cortex', 'amygdala'],
        text: 'Low-affinity receptor activated during stress surges. In the basolateral amygdala it modulates synaptic plasticity and threat learning. In the prefrontal cortex, sustained high occupancy under chronic stress can alter dendritic organization and affect contextual regulation.',
      },
      {
        id: 'MR',
        family: 'Mineralocorticoid receptor',
        effect: 'modulate',
        where: ['hippocampus'],
        text: 'High-affinity receptor occupied even at resting baseline levels, supporting memory stability and daily circadian rhythms.',
      },
    ],
    life: {
      made: 'Adrenal cortex cells synthesize cortisol on demand from cholesterol through steroidogenic enzyme steps.',
      packed: 'Because cortisol is lipid-soluble, it diffuses directly across cell membranes rather than being stored in vesicles.',
      released: 'ACTH stimulation triggers immediate synthesis and release directly into adrenal capillary blood.',
      binds: 'Cortisol crosses target cell membranes to bind intracellular glucocorticoid and mineralocorticoid receptors.',
      cleared: 'Liver enzymes convert cortisol into water-soluble metabolites excreted by the kidneys into urine.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'hydrocortisone',
        name: 'Hydrocortisone',
        acts: 'receptor-mimic',
        target: 'GR/MR',
        text: 'Synthetic cortisol used to treat adrenal insufficiency and suppress severe inflammatory reactions.',
      },
      {
        id: 'dexamethasone',
        name: 'Dexamethasone',
        acts: 'receptor-mimic',
        target: 'GR',
        text: 'Potent glucocorticoid that suppresses immune swelling and tests feedback sensitivity in the pituitary-adrenal axis.',
      },
      {
        id: 'mifepristone',
        name: 'Mifepristone',
        acts: 'receptor-block',
        target: 'GR',
        text: 'Blocks glucocorticoid receptors to control high blood sugar in patients with severe Cushing syndrome.',
      },
    ],
    breaks: {
      text: 'Imbalances in cortisol impair glucose regulation, immune defense, and emotional resilience.',
      bullets: [
        'Cushing syndrome: chronic cortisol excess causes central weight gain, skin thinning, high blood pressure, and mood swings.',
        'Addison disease: autoimmune destruction of the adrenal cortex leads to severe fatigue, low blood pressure, and life-threatening crises.',
        'Chronic stress: prolonged glucocorticoid elevations alter the balance between amygdala threat responsiveness and prefrontal contextual regulation, making safety learning harder to consolidate.',
      ],
    },
    tryIt: 'Notice how your body reacts when startled by a near-miss while driving. While adrenaline causes the instant racing heartbeat, cortisol rises over the following twenty minutes to restore glucose and calm tissue inflammation.',
  },
  {
    id: 'adrenaline',
    name: 'Adrenaline',
    group: 'hormone',
    color: '#ef4444',
    tagline: 'Triggers the rapid fight-or-flight surge, accelerating heart rate and opening airways.',
    analogy: 'The nitro booster kicking the entire physical engine into maximum overdrive.',
    madeFrom: 'noradrenaline',
    madeIn: ['adrenal'],
    timescale: 'seconds to minutes',
    overview: {
      text: 'Adrenaline (epinephrine) is the emergency hormone of the sympathetic nervous system, produced by chromaffin cells in the adrenal medulla. While central {{chem:noradrenaline}} alerts brain circuits, peripheral adrenaline floods the bloodstream to prepare muscles, heart, and lungs for swift physical action. Within seconds of a perceived threat, it opens breathing passages, quickens cardiac pumping, and directs blood toward skeletal muscles.',
      bullets: [
        'Released into circulation in response to direct sympathetic nerve impulses from the spinal cord.',
        'Triggers rapid breakdown of glycogen into glucose to deliver immediate fuel to sprinting muscles.',
        'Relaxes smooth muscles in the airways while constricting blood vessels feeding the skin and gut.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'spinal-cord',
        carries: 'Sympathetic nerve drive',
        via: 'nerve',
        text: 'The {{hypothalamus}} senses immediate danger and sends rapid electrical signals down sympathetic spinal tracts.',
      },
      {
        from: 'spinal-cord',
        to: 'adrenal',
        carries: 'Acetylcholine',
        via: 'nerve',
        text: 'Splanchnic sympathetic nerves release acetylcholine directly onto adrenal medulla chromaffin cells.',
      },
      {
        from: 'adrenal',
        to: 'heart',
        carries: 'Adrenaline',
        via: 'blood',
        text: 'The adrenal medulla releases adrenaline into the bloodstream, increasing cardiac pumping volume and redirecting circulation toward active muscles.',
      },
    ],
    feedback: [
      {
        from: 'adrenal',
        to: ['hypothalamus'],
        text: 'Elevated arterial pressure stimulates baroreceptors that send sensory signals back to the brainstem and {{hypothalamus}} to ease sympathetic tone.',
      },
    ],
    density: {
      'hypothalamus': 0.6,
      'thalamus': 0.5,
    },
    receptors: [
      {
        id: 'beta-2',
        family: 'Gs coupled adrenergic receptor',
        effect: 'modulate',
        where: ['heart'],
        text: 'Carried through the circulation to relax smooth muscle around airways and dilate arteries supplying skeletal muscles.',
      },
      {
        id: 'beta-1',
        family: 'Gs coupled adrenergic receptor',
        effect: 'excite',
        where: ['heart'],
        text: 'Increases heart rate and the strength of each cardiac contraction to deliver oxygenated blood at higher pressure.',
      },
    ],
    life: {
      made: 'Adrenal chromaffin cells convert noradrenaline to adrenaline using the cortisol-induced enzyme PNMT.',
      packed: 'Vesicular monoamine transporters concentrate adrenaline into dense-core chromaffin granules.',
      released: 'Sympathetic nerve spikes trigger calcium influx and massive exocytosis of granules into capillary blood.',
      binds: 'Adrenaline binds cell-surface alpha and beta adrenergic receptors across vascular, cardiac, and metabolic tissues.',
      cleared: 'Liver and kidney enzymes (COMT and MAO) rapidly break down adrenaline with a circulating half-life of roughly two minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'epinephrine-pen',
        name: 'EpiPen (Epinephrine)',
        acts: 'receptor-mimic',
        target: 'alpha/beta',
        text: 'Injectable adrenaline that rapidly opens constricted airways and raises blood pressure during life-threatening anaphylactic shock.',
      },
      {
        id: 'metoprolol',
        name: 'Metoprolol',
        acts: 'receptor-block',
        target: 'beta-1',
        text: 'Selective beta-1 blocker that shields the heart from adrenaline overdrive, lowering blood pressure and preventing arrhythmias.',
      },
    ],
    breaks: {
      text: 'Excessive or uncontrolled adrenaline surges place dangerous stress on cardiovascular circuits.',
      bullets: [
        'Pheochromocytoma: rare adrenal medulla tumour causing unpredictable spikes of adrenaline with pounding headaches, sweating, and severe hypertension.',
        'Anaphylaxis: massive allergic histamine release causes airway closure and circulatory collapse, requiring immediate adrenaline injection.',
        'Panic attacks: sudden sympathetic adrenaline discharges trigger palpitations, trembling, and shortness of breath.',
      ],
    },
    tryIt: 'Sprint up a flight of stairs as fast as you safely can. The pounding rhythm in your chest and wide, effortless breaths are adrenaline driving blood and oxygen straight to your working muscles.',
  },
  {
    id: 'oxytocin',
    name: 'Oxytocin',
    group: 'hormone',
    color: '#ff9fd1',
    synapse: 'oxytocin',
    tagline: 'Promotes social bonding, maternal care, and physical birth contractions.',
    analogy: 'The biological weaver of social safety, trust, and close emotional connection.',
    madeFrom: 'prepro-oxytocin peptide',
    madeIn: ['hypothalamus'],
    timescale: 'minutes to hours',
    overview: {
      text: 'Oxytocin is a nine-amino-acid peptide produced by magnocellular neurons in the {{hypothalamus}} and released into the bloodstream from the posterior {{pituitary}}. Inside the brain, it acts as a neuromodulator that dampens fear responses in the amygdala and deepens social trust. In the body, it serves as the essential hormonal trigger for uterine labour contractions and milk ejection during nursing.',
      bullets: [
        'Synthesized in the paraventricular and supraoptic nuclei of the hypothalamus and stored in the posterior pituitary.',
        'Promotes maternal bonding, partner attachment, and cooperative trust while dampening social anxiety.',
        'Operates in a positive feedback loop during childbirth: pressure on the cervix triggers more oxytocin release until birth occurs.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'Oxytocin',
        via: 'nerve',
        text: 'Hypothalamic neurosecretory axons carry oxytocin down through the pituitary stalk straight into the posterior {{pituitary}}.',
      },
      {
        from: 'pituitary',
        to: 'gonads',
        carries: 'Oxytocin',
        via: 'blood',
        text: 'The posterior pituitary releases oxytocin into the bloodstream to stimulate uterine contractions and lactation.',
      },
    ],
    feedback: [
      {
        from: 'gonads',
        to: ['hypothalamus'],
        text: 'Sensory stretching of the cervix or nursing nipple sends nerve impulses back to the {{hypothalamus}} to trigger further oxytocin surges in a positive feedback loop.',
      },
    ],
    density: {
      'amygdala': 0.8,
      'nucleus-accumbens': 0.75,
      'hypothalamus': 0.85,
    },
    receptors: [
      {
        id: 'OXTR',
        family: 'Gq coupled oxytocin receptor',
        effect: 'modulate',
        where: ['amygdala', 'nucleus-accumbens', 'hypothalamus'],
        text: 'G-protein coupled receptor that increases intracellular calcium, quieting amygdala alarm circuits and facilitating social affiliation.',
      },
    ],
    life: {
      made: 'Magnocellular hypothalamic neurons synthesize prepro-oxytocin and cleave it into the active nonapeptide.',
      packed: 'Packaged into large dense-core vesicles alongside neurophysin I and transported down axons to the posterior pituitary.',
      released: 'Coordinated bursts of electrical firing cause calcium-dependent exocytosis into fenestrated capillaries.',
      binds: 'Circulating oxytocin stimulates oxytocin receptors on uterine smooth muscle, mammary myoepithelial cells, and limbic neurons.',
      cleared: 'Degraded by oxytocinase enzymes in tissue and blood with a circulating half-life of three to five minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'pitocin',
        name: 'Pitocin (Synthetic oxytocin)',
        acts: 'receptor-mimic',
        target: 'OXTR',
        text: 'Administered intravenously to induce or strengthen rhythmic uterine contractions during childbirth and prevent postpartum bleeding.',
      },
      {
        id: 'atosiban',
        name: 'Atosiban',
        acts: 'receptor-block',
        target: 'OXTR',
        text: 'Inhibits oxytocin receptors to halt premature labour contractions and delay early delivery.',
      },
    ],
    breaks: {
      text: 'Disruptions in oxytocin signaling affect reproductive progression and social attunement.',
      bullets: [
        'Prolonged labour: weak or insufficient oxytocin release during childbirth leads to uterine inertia and delayed delivery.',
        'Impaired milk ejection: emotional stress or pain can inhibit oxytocin release, preventing nursing mothers from letting down milk.',
        'Social anxiety: altered oxytocin receptor sensitivity is studied in social withdrawal and atypical attachment dynamics.',
      ],
    },
    tryIt: 'Hug a close friend, partner, or pet a dog. That gentle wave of physical relaxation and feeling of emotional safety is driven partly by oxytocin release quieting your amygdala.',
  },
  {
    id: 'vasopressin',
    name: 'Vasopressin',
    group: 'hormone',
    color: '#38bdf8',
    tagline: 'Conserves body water, concentrates urine, and raises blood pressure.',
    analogy: 'The dam keeper closing reservoir gates to prevent dehydration when water is scarce.',
    madeFrom: 'prepro-vasopressin peptide',
    madeIn: ['hypothalamus'],
    timescale: 'minutes to hours',
    overview: {
      text: 'Vasopressin, also called antidiuretic hormone (ADH), is manufactured in the {{hypothalamus}} and released into the bloodstream by the posterior {{pituitary}}. It acts as the body\'s master water-conservation controller. When dehydration or high salt levels concentrate the blood, vasopressin commands the kidneys to reabsorb water back into circulation, keeping blood volume and arterial pressure steady.',
      bullets: [
        'Osmoreceptors in the anterior hypothalamus detect tiny changes in blood salinity to regulate vasopressin secretion.',
        'Inserts aquaporin water channels into renal collecting ducts to rescue water before it becomes urine.',
        'Causes arterial vasoconstriction at higher concentrations, helping support blood pressure during haemorrhage.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'Vasopressin',
        via: 'nerve',
        text: 'Osmoreceptive neurons in the {{hypothalamus}} synthesize vasopressin and send it down axonal tracts into the posterior {{pituitary}}.',
      },
      {
        from: 'pituitary',
        to: 'heart',
        carries: 'Vasopressin (ADH)',
        via: 'blood',
        text: 'The posterior pituitary secretes vasopressin into circulation, directing kidneys to conserve water and vessels to sustain pressure.',
      },
    ],
    feedback: [
      {
        from: 'heart',
        to: ['hypothalamus'],
        text: 'Restored blood volume and diluted salt levels satisfy hypothalamic osmoreceptors, shutting off further vasopressin release.',
      },
    ],
    density: {
      'hypothalamus': 0.85,
      'amygdala': 0.6,
    },
    receptors: [
      {
        id: 'V2',
        family: 'Gs coupled vasopressin receptor',
        effect: 'modulate',
        where: ['heart'],
        text: 'Carried through the circulation to renal collecting ducts, moving aquaporin-2 water channels to the cell surface to reclaim water.',
      },
      {
        id: 'V1a',
        family: 'Gq coupled vasopressin receptor',
        effect: 'excite',
        where: ['hypothalamus', 'amygdala'],
        text: 'Causes vascular smooth muscle contraction and modulates territorial and social pair-bonding behavior in the brain.',
      },
    ],
    life: {
      made: 'Synthesized in hypothalamic supraoptic and paraventricular neurons as a prepro-hormone.',
      packed: 'Cleaved and packaged into dense-core secretory granules associated with neurophysin II.',
      released: 'Depolarization driven by increased extracellular osmolarity triggers exocytosis from posterior pituitary terminals.',
      binds: 'Circulates to bind renal V2 receptors and vascular V1a receptors.',
      cleared: 'Rapidly cleaved by renal and hepatic peptidases with a circulating half-life of 10 to 20 minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'desmopressin',
        name: 'Desmopressin (DDAVP)',
        acts: 'receptor-mimic',
        target: 'V2',
        text: 'Synthetic vasopressin analogue used to treat central diabetes insipidus and nocturnal bedwetting without raising blood pressure.',
      },
      {
        id: 'conivaptan',
        name: 'Conivaptan',
        acts: 'receptor-block',
        target: 'V1a/V2',
        text: 'Vasopressin receptor antagonist used to treat dangerous water retention and low blood sodium in hospital settings.',
      },
    ],
    breaks: {
      text: 'Failures in vasopressin regulation cause severe fluid imbalance, extreme thirst, or water intoxication.',
      bullets: [
        'Central diabetes insipidus: lack of vasopressin from hypothalamic or pituitary damage leads to copious dilute urine and intense thirst.',
        'SIADH: inappropriate excess vasopressin secretion causes water retention and dangerously low blood sodium.',
        'Alcohol diuresis: ethanol inhibits hypothalamic vasopressin release, explaining why drinking alcohol causes frequent urination and dehydration.',
      ],
    },
    tryIt: 'Notice how your urine becomes darker and less frequent on a hot summer day or after vigorous exercise. Your hypothalamus has sensed concentrated blood and ordered vasopressin to reclaim every available drop of water.',
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    group: 'hormone',
    color: '#818cf8',
    tagline: 'Signals environmental darkness to coordinate the biological sleep clock.',
    analogy: 'The brain\'s curfew whistle announcing that night has arrived and it is time to rest.',
    madeFrom: 'serotonin',
    madeIn: ['pineal-gland'],
    timescale: 'hours (overnight)',
    overview: {
      text: 'Melatonin is the darkness hormone synthesized by the {{pineal-gland}} on the midline of the brain. Built from {{chem:serotonin}}, its production is strictly governed by the suprachiasmatic master clock in the {{hypothalamus}}. When light fades at dusk, the brake is released, and melatonin floods the bloodstream and cerebrospinal fluid, signaling to organs that nighttime has begun and priming sleep circuits.',
      bullets: [
        'Production is suppressed by blue wavelengths of light (around 460 to 480 nm) detected by retinal ganglion cells.',
        'Reaches peak circulating levels between 2:00 AM and 4:00 AM in people with typical sleep schedules.',
        'Also acts as a potent direct free-radical scavenger and anti-inflammatory antioxidant across tissues.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pineal-gland',
        carries: 'Sympathetic nerve drive',
        via: 'nerve',
        text: 'The circadian master clock in the {{hypothalamus}} senses falling light levels and signals the {{pineal-gland}} via sympathetic tracts.',
      },
      {
        from: 'pineal-gland',
        to: 'thalamus',
        carries: 'Melatonin',
        via: 'blood',
        text: 'The pineal gland releases melatonin into circulation and spinal fluid, promoting blood vessel dilation in hands and feet while easing thalamic sleep gates.',
      },
    ],
    feedback: [
      {
        from: 'pineal-gland',
        to: ['hypothalamus'],
        text: 'Melatonin binds MT1 and MT2 receptors on hypothalamic clock neurons, synchronizing daily circadian phase and preventing sleep drift.',
      },
    ],
    density: {
      'thalamus': 0.8,
      'hypothalamus': 0.85,
    },
    receptors: [
      {
        id: 'MT1',
        family: 'Gi coupled melatonin receptor',
        effect: 'inhibit',
        where: ['hypothalamus', 'thalamus'],
        text: 'Quiets electrical firing in the suprachiasmatic master clock, promoting sleep onset and lowering core body temperature.',
      },
      {
        id: 'MT2',
        family: 'Gi coupled melatonin receptor',
        effect: 'modulate',
        where: ['hypothalamus', 'thalamus'],
        text: 'Shifts and synchronizes the timing of the master circadian clock to match external light-dark cycles.',
      },
    ],
    life: {
      made: 'Pinealocytes convert serotonin into melatonin using the rate-limiting enzyme AANAT, which is activated in darkness.',
      packed: 'Because melatonin is highly lipophilic, it diffuses immediately out of cells into blood capillaries without storage vesicles.',
      released: 'Surges into blood and cerebrospinal fluid as sympathetic noradrenaline stimulates pinealocyte beta receptors in the dark.',
      binds: 'Binds high-affinity MT1 and MT2 receptors in the hypothalamus, thalamus, retina, and vascular beds.',
      cleared: 'Metabolized by cytochrome P450 enzymes in the liver into 6-hydroxymelatonin and excreted by the kidneys.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'melatonin-supp',
        name: 'Melatonin supplement',
        acts: 'receptor-mimic',
        target: 'MT1/MT2',
        text: 'Used to shift circadian timing and reduce time to fall asleep in jet lag, shift work, and delayed sleep phase disorder.',
      },
      {
        id: 'ramelteon',
        name: 'Ramelteon',
        acts: 'receptor-mimic',
        target: 'MT1/MT2',
        text: 'Selective melatonin receptor agonist prescribed to treat chronic insomnia without morning grogginess or dependence.',
      },
    ],
    breaks: {
      text: 'Circadian misalignment and deficient melatonin secretion cause insomnia, daytime fatigue, and metabolic strain.',
      bullets: [
        'Delayed sleep phase: a shifted internal clock delays melatonin onset until late night, making early morning waking exhausting.',
        'Jet lag: rapid travel across time zones leaves pineal melatonin out of sync with destination daylight.',
        'Light at night: late-evening screen exposure suppresses melatonin by up to 50 percent, disrupting restorative sleep stages.',
      ],
    },
    tryIt: 'Dim overhead lights and switch your phone to warm night mode an hour before bed. Cutting out blue light allows your pineal gland to release melatonin on schedule, making it effortless to drift off.',
  },
  {
    id: 'thyroid-hormone',
    name: 'Thyroid hormone',
    group: 'hormone',
    color: '#34d399',
    tagline: 'Sets the metabolic burn rate of every cell, governing warmth and energy.',
    analogy: 'The engine throttle setting the baseline cruising speed of the body.',
    madeFrom: 'iodine and tyrosine',
    madeIn: ['thyroid'],
    timescale: 'hours to days',
    overview: {
      text: 'Thyroid hormones (thyroxine or T4, and active triiodothyronine or T3) are produced by the follicular cells of the thyroid gland in the neck. Controlled by the {{hypothalamus}} and {{pituitary}}, thyroid hormones act as the master metabolic regulator of the body. They stimulate oxygen consumption, protein synthesis, body warmth generation, and proper neural growth throughout development.',
      bullets: [
        'The only biological molecules in vertebrates that require dietary iodine for their synthesis.',
        'T4 is the primary hormone released into circulation; target tissues convert it to the more potent T3 via deiodinase enzymes.',
        'Essential for healthy brain development in infancy: untreated childhood deficiency causes irreversible intellectual disability.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'TRH (Thyrotropin-releasing hormone)',
        via: 'portal',
        text: 'The {{hypothalamus}} monitors metabolic rate and temperature, releasing TRH into hypophyseal portal vessels.',
      },
      {
        from: 'pituitary',
        to: 'thyroid',
        carries: 'TSH (Thyroid-stimulating hormone)',
        via: 'blood',
        text: 'The anterior {{pituitary}} secretes TSH into the bloodstream to stimulate thyroid gland growth and hormone production.',
      },
      {
        from: 'thyroid',
        to: 'heart',
        carries: 'T3 and T4',
        via: 'blood',
        text: 'The thyroid gland secretes T4 and T3 into general circulation, accelerating cellular metabolism and fueling mitochondrial activity across muscles and organs.',
      },
    ],
    feedback: [
      {
        from: 'thyroid',
        to: ['hypothalamus', 'pituitary'],
        text: 'Circulating free T3 and T4 exert negative feedback on both the {{hypothalamus}} and {{pituitary}}, shutting down TRH and TSH to keep metabolism steady.',
      },
    ],
    density: {
      'prefrontal-cortex': 0.6,
      'hippocampus': 0.65,
    },
    receptors: [
      {
        id: 'TR-alpha',
        family: 'Nuclear hormone receptor',
        effect: 'modulate',
        where: ['heart'],
        text: 'Expressed abundantly in cardiac tissue and the brain, regulating heart rate and neural development.',
      },
      {
        id: 'TR-beta',
        family: 'Nuclear hormone receptor',
        effect: 'modulate',
        where: ['pituitary', 'hypothalamus'],
        text: 'Mediates negative feedback in the pituitary and hypothalamus and regulates metabolic expenditure in liver and kidney.',
      },
    ],
    life: {
      made: 'Thyroid follicular cells attach iodine to tyrosine residues on thyroglobulin protein, coupling them into T3 and T4.',
      packed: 'Stored extracellularly in thyroid follicles as iodinated thyroglobulin colloid until needed.',
      released: 'TSH stimulation causes endocytosis and proteolytic cleavage, releasing T4 and T3 into the bloodstream.',
      binds: 'Hormones enter cells and bind nuclear thyroid hormone receptors to regulate hundreds of metabolic genes.',
      cleared: 'Progressively deiodinated in liver, kidney, and brain tissues with a long circulation half-life of roughly seven days.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'levothyroxine',
        name: 'Levothyroxine (Synthroid)',
        acts: 'precursor',
        target: 'TR',
        text: 'Synthetic T4 taken daily to replace missing thyroid hormone in hypothyroidism, restoring energy and metabolic rate.',
      },
      {
        id: 'methimazole',
        name: 'Methimazole',
        acts: 'enzyme-block',
        target: 'TPO',
        text: 'Inhibits thyroid peroxidase to block iodine incorporation and treat hyperthyroidism and Graves disease.',
      },
    ],
    breaks: {
      text: 'Thyroid dysfunction causes broad swings between sluggish exhaustion and frenetic metabolic overdrive.',
      bullets: [
        'Hypothyroidism: insufficient thyroid hormone causes fatigue, weight gain, cold intolerance, constipation, and cognitive slowing.',
        'Hyperthyroidism: excessive hormone production triggers a racing pulse, weight loss, tremor, heat intolerance, and severe anxiety.',
        'Goitre: enlargement of the thyroid gland due to iodine deficiency or autoimmune inflammation.',
      ],
    },
    tryIt: 'Notice your comfortable warmth in a cool air-conditioned room. Thyroid hormone is continuously instructing trillions of cells to burn food fuel and generate that baseline body heat.',
  },
  {
    id: 'leptin',
    name: 'Leptin',
    group: 'hormone',
    color: '#a3e635',
    tagline: 'Signals body fat reserves to the brain, curbing appetite and approving reproduction.',
    analogy: 'The fuel gauge on the dashboard showing how much long-term energy is stored in the fuel tank.',
    madeFrom: 'ob protein peptide',
    madeIn: ['fat'],
    timescale: 'hours to days',
    overview: {
      text: 'Leptin is an adipose-derived peptide hormone produced by white fat cells in proportion to total body energy stores. Carried through the bloodstream, it crosses into the {{hypothalamus}} to inform the brain that energy reserves are sufficient. High leptin levels quiet hunger signals and permit energy-demanding processes like puberty and immune defense, while falling leptin triggers intense appetite and conservation of calories.',
      bullets: [
        'Discovered in 1994, transforming fat tissue from passive insulation into an active endocrine organ.',
        'Provides a long-term homeostatic baseline, helping defend steady body weight over weeks and months.',
        'Falling leptin during starvation shuts down reproductive fertility to prevent pregnancy when nutrients are scarce.',
      ],
    },
    axis: [
      {
        from: 'fat',
        to: 'hypothalamus',
        carries: 'Leptin',
        via: 'blood',
        text: 'White adipose tissue secretes leptin into the bloodstream in proportion to stored lipid mass.',
      },
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'Neuroendocrine signals',
        via: 'portal',
        text: 'Leptin binds arcuate nucleus neurons in the {{hypothalamus}}, curbing appetite peptides and activating metabolic burning.',
      },
    ],
    feedback: [
      {
        from: 'hypothalamus',
        to: ['fat'],
        text: 'Appetite suppression and higher sympathetic calorie burn reduce food intake, stabilizing body fat stores over the long term.',
      },
    ],
    density: {
      'hypothalamus': 0.95,
      'vta': 0.6,
    },
    receptors: [
      {
        id: 'LepR',
        family: 'Class I cytokine receptor',
        effect: 'modulate',
        where: ['hypothalamus'],
        text: 'Receptor linked to the JAK-STAT signalling cascade, activating appetite-suppressing POMC cells and silencing hunger-driving NPY neurons.',
      },
    ],
    life: {
      made: 'Synthesized and secreted constitutively by mature white adipocytes as a 167-amino-acid peptide.',
      packed: 'Released continuously through the constitutive secretory pathway without vesicle storage.',
      released: 'Secretion rates mirror adipocyte fat content, peaking overnight in a circadian pattern.',
      binds: 'Crosses the blood-brain barrier via saturable transport to bind leptin receptors in the hypothalamus and ventral midbrain.',
      cleared: 'Cleared predominantly by renal filtration and metabolic degradation with a half-life of about 90 minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'metreleptin',
        name: 'Metreleptin',
        acts: 'receptor-mimic',
        target: 'LepR',
        text: 'Recombinant human leptin analogue used to treat severe metabolic complications in patients with rare generalized lipodystrophy.',
      },
    ],
    breaks: {
      text: 'Breakdowns in leptin signaling cause uncontrollable hunger, severe obesity, and reproductive arrest.',
      bullets: [
        'Leptin resistance: in common obesity, high circulating leptin fails to curb hunger because transport into the brain becomes saturated.',
        'Congenital leptin deficiency: rare genetic absence of leptin causes constant, insatiable hunger and severe early-childhood obesity.',
        'Hypothalamic amenorrhea: very low body fat drops leptin below the threshold required to maintain menstrual cycles.',
      ],
    },
    tryIt: 'Notice how a hearty, balanced dinner leaves you comfortably full and indifferent to snacks for several hours. As your fat cells sense ample nutrition, leptin reassures your brain that the fuel tank is satisfied.',
  },
  {
    id: 'ghrelin',
    name: 'Ghrelin',
    group: 'hormone',
    color: '#fb923c',
    tagline: 'The hunger hormone released by an empty stomach to drive food seeking.',
    analogy: 'The dinner bell ringing in the empty stomach, reminding the brain to hunt for a meal.',
    madeFrom: 'preproghrelin',
    madeIn: ['stomach'],
    timescale: '30 to 90 minutes',
    overview: {
      text: 'Ghrelin is a fast-acting peptide hormone secreted by P/D1 endocrine cells in the fundus of the stomach. Known as the hunger hormone, ghrelin levels surge before customary mealtimes and plunge rapidly once food enters the stomach. By crossing into the {{hypothalamus}} and ventral midbrain, ghrelin stimulates hunger, enhances the rewarding appeal of high-calorie foods, and primes digestive acid secretion.',
      bullets: [
        'Requires an unusual octanoyl fatty-acid modification by the enzyme GOAT to cross into the brain and bind its receptor.',
        'Acts as the direct physiological counterbalance to {{chem:leptin}}, firing off hunger pangs when the gut is empty.',
        'Also stimulates growth hormone release from the pituitary to protect muscle mass during food restriction.',
      ],
    },
    axis: [
      {
        from: 'stomach',
        to: 'hypothalamus',
        carries: 'Acylated ghrelin',
        via: 'blood',
        text: 'Endocrine cells in the empty stomach release ghrelin into circulation as scheduled mealtime approaches.',
      },
      {
        from: 'hypothalamus',
        to: 'nucleus-accumbens',
        carries: 'Dopaminergic motivational drive',
        via: 'nerve',
        text: 'Ghrelin stimulates NPY/AgRP neurons in the {{hypothalamus}} and boosts dopamine release, making food cues intensely desirable.',
      },
    ],
    feedback: [
      {
        from: 'stomach',
        to: ['hypothalamus'],
        text: 'Physical stomach stretching and nutrient absorption rapidly suppress ghrelin output, allowing satiety signals to take over.',
      },
    ],
    density: {
      'hypothalamus': 0.9,
      'vta': 0.7,
      'nucleus-accumbens': 0.65,
    },
    receptors: [
      {
        id: 'GHSR-1a',
        family: 'Gq coupled growth hormone secretagogue receptor',
        effect: 'excite',
        where: ['hypothalamus', 'vta'],
        text: 'Stimulates intracellular calcium and electrical firing in hypothalamic hunger neurons and midbrain dopamine cells.',
      },
    ],
    life: {
      made: 'Stomach endocrine cells synthesize preproghrelin and attach an eight-carbon octanoic acid chain to activate it.',
      packed: 'Stored in dense-core secretory granules within gastric mucosa cells.',
      released: 'Exocytosed into venous blood when the stomach is empty, rising sharply before customary meal hours.',
      binds: 'Reaches the arcuate nucleus of the hypothalamus and the ventral tegmental area to drive appetite.',
      cleared: 'De-acylated and degraded by circulating and tissue proteases with a half-life of roughly 30 minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'macimorelin',
        name: 'Macimorelin',
        acts: 'receptor-mimic',
        target: 'GHSR-1a',
        text: 'Oral ghrelin receptor agonist used as a diagnostic tool to evaluate adult growth hormone deficiency.',
      },
    ],
    breaks: {
      text: 'Unchecked ghrelin signaling drives insatiable hunger and compulsive overeating.',
      bullets: [
        'Prader-Willi syndrome: genetic condition characterized by chronically elevated ghrelin levels, producing relentless and life-threatening hunger.',
        'Dieting rebound: caloric restriction prompts a persistent compensatory rise in ghrelin, making long-term weight loss challenging.',
        'Gastric bypass effect: bariatric surgery removes ghrelin-producing stomach tissue, dramatically blunting appetite after surgery.',
      ],
    },
    tryIt: 'Notice how your stomach grumbles right around your usual mealtime even if you have not seen or smelled food yet. Ghrelin rises on an internal schedule to remind your brain to go look for a meal.',
  },
  {
    id: 'growth-hormone',
    name: 'Growth hormone',
    group: 'hormone',
    color: '#3b82f6',
    tagline: 'Stimulates tissue growth, bone lengthening, muscle protein synthesis, and cellular repair.',
    analogy: 'The head contractor directing night-time repair crews to rebuild and strengthen physical structures.',
    madeFrom: 'somatotropin peptide',
    madeIn: ['pituitary'],
    timescale: 'hours (surges during deep sleep)',
    overview: {
      text: 'Growth hormone (somatotropin) is a 191-amino-acid peptide secreted by somatotrope cells in the anterior {{pituitary}}. Governed by alternating hypothalamic commands, it is released in dramatic nocturnal pulses during stage 3 slow-wave sleep. Throughout childhood it drives bone lengthening and organ enlargement, while in adulthood it shifts metabolism toward fat burning, muscle repair, and collagen maintenance.',
      bullets: [
        'Released in periodic bursts throughout the day, with peaks provoked by vigorous physical exercise and fasting.',
        'Acts partly by commanding the liver to produce insulin-like growth factor 1 (IGF-1), which drives cellular division.',
        'Saves muscle protein during fasting by switching metabolic fuel consumption to free fatty acids.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'GHRH (Growth hormone-releasing hormone)',
        via: 'portal',
        text: 'The {{hypothalamus}} pulses GHRH into hypophyseal portal vessels, especially during deep slow-wave sleep.',
      },
      {
        from: 'pituitary',
        to: 'heart',
        carries: 'Growth hormone (GH)',
        via: 'blood',
        text: 'The anterior {{pituitary}} secretes growth hormone pulses into circulation, driving protein synthesis and tissue repair.',
      },
    ],
    feedback: [
      {
        from: 'heart',
        to: ['hypothalamus'],
        text: 'Circulating growth hormone and liver IGF-1 stimulate hypothalamic somatostatin release, applying the brake on further GH pulses.',
      },
    ],
    density: {
      'hypothalamus': 0.7,
      'hippocampus': 0.5,
    },
    receptors: [
      {
        id: 'GHR',
        family: 'Class I cytokine receptor',
        effect: 'modulate',
        where: ['heart'],
        text: 'Dimerizes upon GH binding to activate JAK2 and STAT pathways, triggering IGF-1 production and protein building.',
      },
    ],
    life: {
      made: 'Somatotropes in the anterior pituitary transcribe and synthesize the 191-amino-acid peptide.',
      packed: 'Concentrated into dense secretory granules within pituitary cells.',
      released: 'Pulsatile exocytosis triggered by GHRH and suppressed by somatostatin, spiking during deep sleep and strenuous exercise.',
      binds: 'Stimulates growth hormone receptors across the liver, cartilage, adipose tissue, and skeletal muscle.',
      cleared: 'Metabolized primarily by hepatic and renal cells with a brief circulating half-life of 15 to 20 minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'somatropin',
        name: 'Somatropin',
        acts: 'receptor-mimic',
        target: 'GHR',
        text: 'Recombinant human growth hormone prescribed for growth failure in children and adult growth hormone deficiency.',
      },
      {
        id: 'pegvisomant',
        name: 'Pegvisomant',
        acts: 'receptor-block',
        target: 'GHR',
        text: 'Growth hormone receptor antagonist used to treat acromegaly by preventing excess hormone from stimulating IGF-1.',
      },
    ],
    breaks: {
      text: 'Abnormal growth hormone secretion produces disfiguring skeletal overgrowth or stunted stature.',
      bullets: [
        'Acromegaly: a benign pituitary tumour overproducing GH in adults causes enlargement of hands, feet, jaw, and internal organs.',
        'Gigantism: excess GH before growth plates fuse in childhood causes extreme tall stature exceeding seven feet.',
        'Growth hormone deficiency: inadequate childhood secretion produces delayed growth, short stature, and increased body fat.',
      ],
    },
    tryIt: 'Notice how a solid eight hours of deep sleep leaves sore, exercised muscles feeling renewed the next morning. Deep slow-wave sleep triggers massive pulses of growth hormone that repair microscopic muscle tears.',
  },
  {
    id: 'sex-hormones',
    name: 'Sex hormones',
    group: 'hormone',
    color: '#ec4899',
    tagline: 'Drives sexual maturation, reproductive cycles, bone strength, and social behaviour.',
    analogy: 'The architectural blueprints sculpting physical maturation and reproductive cycles.',
    madeFrom: 'cholesterol',
    madeIn: ['gonads'],
    timescale: 'hours to months (cyclical)',
    overview: {
      text: 'Sex steroid hormones including estrogens, progesterone, and androgens like testosterone are manufactured primarily in the gonads (ovaries and testes), along with smaller amounts in the adrenal glands. Regulated by hypothalamic and pituitary pulses, they guide embryonic sexual differentiation, drive secondary physical changes at puberty, maintain adult bone and muscle mass, and shape libido and reproductive cycles.',
      bullets: [
        'All sex steroids are synthesized from cholesterol through shared biochemical pathways.',
        'Testosterone is converted to potent estradiol in specific brain regions by the enzyme aromatase.',
        'In females, cyclic changes in estrogen and progesterone coordinate monthly uterine and ovarian preparation.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'GnRH (Gonadotropin-releasing hormone)',
        via: 'portal',
        text: 'Pulsatile GnRH from the {{hypothalamus}} stimulates gonadotrope cells in the anterior {{pituitary}}.',
      },
      {
        from: 'pituitary',
        to: 'gonads',
        carries: 'LH and FSH',
        via: 'blood',
        text: 'The pituitary secretes LH and FSH into circulation to stimulate follicle development, ovulation, or sperm production.',
      },
      {
        from: 'gonads',
        to: 'heart',
        carries: 'Estrogen, progesterone, or testosterone',
        via: 'blood',
        text: 'The gonads release sex steroids into systemic circulation, carried by binding proteins to influence gene expression across distant tissues.',
      },
    ],
    feedback: [
      {
        from: 'gonads',
        to: ['hypothalamus', 'pituitary'],
        text: 'Sex steroids provide negative feedback to brake GnRH and LH release, except for a high-estrogen surge that triggers mid-cycle ovulation.',
      },
    ],
    density: {
      'hypothalamus': 0.85,
      'amygdala': 0.75,
      'hippocampus': 0.7,
      'prefrontal-cortex': 0.6,
    },
    receptors: [
      {
        id: 'ER-alpha',
        family: 'Nuclear estrogen receptor',
        effect: 'modulate',
        where: ['hypothalamus', 'amygdala'],
        text: 'Regulates reproductive behavior, neuroprotection, and hypothalamic metabolic balance.',
      },
      {
        id: 'AR',
        family: 'Nuclear androgen receptor',
        effect: 'modulate',
        where: ['hypothalamus', 'motor-cortex'],
        text: 'Mediates testosterone signals, promoting muscle hypertrophy, bone density, and masculine physical traits.',
      },
    ],
    life: {
      made: 'Enzymes in gonadal and adrenal cells convert cholesterol into pregnenolone, androgens, and estrogens.',
      packed: 'Because steroids are lipophilic, they diffuse freely across membranes directly into capillary blood.',
      released: 'Release is driven by pulsatile pituitary LH and FSH stimulation.',
      binds: 'Carried in blood by sex hormone-binding globulin (SHBG) to enter target cells and bind nuclear receptors.',
      cleared: 'Conjugated into water-soluble glucuronides and sulfates by liver enzymes and excreted in urine and bile.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'tamoxifen',
        name: 'Tamoxifen',
        acts: 'receptor-block',
        target: 'ER',
        text: 'Selective estrogen receptor modulator that blocks estrogen stimulation in breast tissue to treat hormone-sensitive breast cancer.',
      },
      {
        id: 'testosterone-cyp',
        name: 'Testosterone cypionate',
        acts: 'receptor-mimic',
        target: 'AR',
        text: 'Injectable testosterone formulation used to restore normal androgen levels in male hypogonadism and gender-affirming therapy.',
      },
    ],
    breaks: {
      text: 'Imbalances in sex hormones produce infertility, loss of bone strength, and mood instability.',
      bullets: [
        'Osteoporosis: dropping estrogen after menopause accelerates bone loss, dramatically increasing fracture risk.',
        'Polycystic ovary syndrome (PCOS): elevated androgens and irregular ovulation cause irregular cycles, acne, and metabolic strain.',
        'Hypogonadism: low testosterone in men leads to fatigue, loss of muscle mass, reduced bone density, and depressed mood.',
      ],
    },
    tryIt: 'Notice how your energy, mood, and physical stamina can fluctuate across different weeks or seasons of life. Sex steroids continuously shape neuromuscular vitality, sleep quality, and motivation.',
  },
  {
    id: 'prolactin',
    name: 'Prolactin',
    group: 'hormone',
    color: '#a855f7',
    tagline: 'Promotes milk production after birth and fosters nurturing parental instincts.',
    analogy: 'The supply chain manager stocking the pantry for newborn nourishment.',
    madeFrom: 'prolactin peptide',
    madeIn: ['pituitary'],
    timescale: 'hours to days',
    overview: {
      text: 'Prolactin is a 198-amino-acid peptide produced by lactotrope cells in the anterior {{pituitary}}. Unlike most pituitary hormones that require a releasing factor, prolactin is kept under continuous tonic restraint by {{chem:dopamine}} along the tuberoinfundibular pathway. When nursing, pregnancy, or sleep removes this dopamine brake, prolactin surges to stimulate breast milk synthesis and encourage parental caregiving.',
      bullets: [
        'Uniquely controlled primarily by continuous dopamine inhibition rather than an excitatory releasing hormone.',
        'Stimulates mammary alveolar cells to transcribe milk proteins including casein and lactalbumin.',
        'Rises in both mothers and fathers during child-rearing, promoting protective and nurturing parental behavior.',
      ],
    },
    axis: [
      {
        from: 'hypothalamus',
        to: 'pituitary',
        carries: 'Dopamine brake (Tuberoinfundibular)',
        via: 'portal',
        text: 'The {{hypothalamus}} continuously releases dopamine into portal vessels to restrain pituitary prolactin outside lactation.',
      },
      {
        from: 'pituitary',
        to: 'heart',
        carries: 'Prolactin',
        via: 'blood',
        text: 'When dopamine braking drops during nursing or pregnancy, lactotropes release prolactin into the general circulation.',
      },
    ],
    feedback: [
      {
        from: 'pituitary',
        to: ['hypothalamus'],
        text: 'Rising prolactin feeds back onto hypothalamic arcuate neurons to stimulate dopamine synthesis, restoring the inhibitory brake.',
      },
    ],
    density: {
      'hypothalamus': 0.8,
      'amygdala': 0.55,
    },
    receptors: [
      {
        id: 'PRLR',
        family: 'Class I cytokine receptor',
        effect: 'modulate',
        where: ['hypothalamus'],
        text: 'Activates the JAK2-STAT5 pathway to stimulate milk protein gene transcription and nurture parental bonding.',
      },
    ],
    life: {
      made: 'Synthesized by lactotrope cells in the anterior pituitary gland as a single-chain polypeptide.',
      packed: 'Stored in dense cytoplasmic secretory granules until the hypothalamic dopamine brake is lifted.',
      released: 'Released into capillary blood when dopamine levels in portal vessels fall, or during nipple stimulation.',
      binds: 'Binds prolactin receptors in mammary tissue, the hypothalamus, ovaries, and immune cells.',
      cleared: 'Metabolized by liver and kidney cells with a circulating half-life of 20 to 30 minutes.',
      clearedBy: 'blood',
    },
    drugs: [
      {
        id: 'cabergoline',
        name: 'Cabergoline',
        acts: 'receptor-mimic',
        target: 'D2',
        text: 'Potent D2 dopamine receptor agonist that suppresses pituitary prolactin release to shrink prolactinoma tumours.',
      },
      {
        id: 'bromocriptine',
        name: 'Bromocriptine',
        acts: 'receptor-mimic',
        target: 'D2',
        text: 'Dopamine agonist used to treat hyperprolactinemia, restore fertility, and prevent unwanted lactation.',
      },
    ],
    breaks: {
      text: 'Excessive prolactin production disrupts reproductive hormones and causes inappropriate milk secretion.',
      bullets: [
        'Prolactinoma: benign pituitary tumour that overproduces prolactin, causing breast milk secretion (galactorrhoea) and infertility.',
        'Antipsychotic side effect: medications that block D2 dopamine receptors inadvertently cause hyperprolactinemia.',
        'Infertility: high prolactin suppresses GnRH secretion from the hypothalamus, preventing ovulation in women and lowering testosterone in men.',
      ],
    },
    tryIt: 'Notice the tender protective instinct evoked when holding a tiny infant. Prolactin rises in both mothers and fathers during close infant contact to encourage nurturing caregiving.',
  },
];
