// Neuromodulators: Dopamine, Serotonin, Noradrenaline, Acetylcholine.

export default [
  {
    id: 'dopamine',
    name: 'Dopamine',
    group: 'modulator',
    color: '#b98cff',
    tagline: 'Signals reward prediction errors, tunes voluntary movement, and shapes motivation.',
    analogy: 'The reward highlighter that marks experiences that turned out better than expected.',
    synapse: 'dopamine',
    pathwayId: 'dopamine-pathways',
    madeFrom: 'tyrosine',
    madeIn: ['substantia-nigra', 'vta', 'hypothalamus'],
    overview: {
      text: 'Dopamine is produced by compact clusters of neurons in the midbrain and hypothalamus that project to vast brain areas. Rather than transmitting fast sensations, it modulates how receptive target circuits are to other inputs. Dopamine surges reinforce cues that lead to valuable outcomes and facilitate the initiation of smooth physical movement.',
      bullets: [
        'Secreted mainly by fewer than a million midbrain neurons that broadcast to billions of cortical and subcortical synapses.',
        'Encodes reward prediction errors: firing rises when an outcome is unexpectedly positive and drops when disappointed.',
        'Essential for transitioning from conscious deliberation to fluent motor and cognitive habits.',
      ],
    },
    tracts: [
      {
        id: 'nigrostriatal',
        name: 'Nigrostriatal pathway',
        from: 'substantia-nigra',
        to: ['striatum'],
        job: 'Stimulating basal ganglia circuits to initiate and coordinate smooth voluntary movement',
        text: 'Axons travel from the substantia nigra pars compacta up into the dorsal striatum. Dopamine released here lowers the threshold required for cortical movement proposals to trigger execution.',
        whenItFails: 'Degeneration of these dopamine neurons causes the stiffness, tremor, and bradykinesia of Parkinson disease.',
        whenBlocked: 'High potency dopamine antagonist antipsychotics can induce drug-induced parkinsonism and extrapyramidal stiffness.',
      },
      {
        id: 'mesolimbic',
        name: 'Mesolimbic pathway',
        from: 'vta',
        to: ['nucleus-accumbens', 'amygdala'],
        job: 'Assigning motivational salience and wanting to cues predictive of reward',
        text: 'Originating in the ventral tegmental area (VTA), this projection terminates densely within the nucleus accumbens. It infuses sensory cues with motivational pull, driving animals and humans to seek beneficial goals.',
        whenItFails: 'Underactivity is linked to anhedonia, apathy, and the motivational deficits seen in depression.',
        whenBlocked: 'Reduces intense cravings but can also flatten emotional warmth and enthusiasm.',
      },
      {
        id: 'mesocortical',
        name: 'Mesocortical pathway',
        from: 'vta',
        to: ['prefrontal-cortex'],
        job: 'Stabilizing goal representations and tuning working memory in executive circuits',
        text: 'Fibers from the VTA fan across the prefrontal cortex. Moderate dopamine concentrations optimize the signal-to-noise ratio in frontal networks, protecting attention from distraction while retaining cognitive flexibility.',
        whenItFails: 'Insufficient frontal dopamine impairs working memory, sustained attention, and organizational focus in ADHD.',
        whenBlocked: 'Excessive frontal blockade can worsen cognitive blunting and executive inertia.',
      },
      {
        id: 'tuberoinfundibular',
        name: 'Tuberoinfundibular pathway',
        from: 'hypothalamus',
        to: ['pituitary'],
        job: 'Providing tonic inhibition on pituitary prolactin secretion',
        text: 'Neurons in the arcuate nucleus of the hypothalamus release dopamine into portal capillaries feeding the anterior pituitary gland. Here dopamine acts as prolactin-inhibiting factor, restraining milk production outside lactation.',
        whenItFails: 'Damage or compression of the pituitary stalk lifts the brake on prolactin, leading to hyperprolactinaemia.',
        whenBlocked: 'Dopamine-blocking medicines often trigger breast tenderness and spontaneous lactation as side effects.',
      },
    ],
    density: {
      'striatum': 1.0,
      'nucleus-accumbens': 0.95,
      'prefrontal-cortex': 0.5,
      'amygdala': 0.45,
      'hippocampus': 0.35,
      'hypothalamus': 0.4,
    },
    receptors: [
      {
        id: 'D1',
        family: 'D1-like (Gs coupled)',
        effect: 'excite',
        where: ['striatum', 'nucleus-accumbens', 'prefrontal-cortex'],
        text: 'Stimulates adenylyl cyclase to increase cyclic AMP, enhancing the responsiveness of striatal go cells and prefrontal pyramidal neurons.',
      },
      {
        id: 'D2',
        family: 'D2-like (Gi coupled)',
        effect: 'inhibit',
        where: ['striatum', 'nucleus-accumbens', 'pituitary'],
        text: 'Inhibits adenylyl cyclase and opens potassium channels, dampening striatal stop cells and inhibiting pituitary prolactin release.',
      },
    ],
    life: {
      made: 'Tyrosine is converted to L-DOPA by tyrosine hydroxylase, and then to dopamine by aromatic L-amino acid decarboxylase.',
      packed: 'Vesicular monoamine transporter 2 (VMAT2) pumps dopamine into synaptic vesicles.',
      released: 'Calcium entry triggers vesicle fusion, releasing dopamine into the synaptic cleft.',
      binds: 'Dopamine diffuses to bind postsynaptic D1 and D2 G-protein coupled receptors.',
      cleared: 'The dopamine active transporter (DAT) recovers dopamine into the presynaptic terminal, with residual breakdown by COMT and MAO.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'cocaine',
        name: 'Cocaine',
        acts: 'reuptake-block',
        target: 'DAT',
        text: 'Blocks the dopamine transporter, allowing dopamine molecules to persist in the synaptic cleft and produce intense euphoria.',
      },
      {
        id: 'levodopa',
        name: 'Levodopa (L-DOPA)',
        acts: 'precursor',
        target: 'AADC',
        text: 'Crosses the blood-brain barrier where surviving neurons convert it into dopamine, replenishing depleted motor stores in Parkinson disease.',
      },
      {
        id: 'haloperidol',
        name: 'Haloperidol',
        acts: 'receptor-block',
        target: 'D2',
        text: 'Blocks D2 dopamine receptors to suppress delusions and hallucinations in acute psychotic states.',
      },
    ],
    breaks: {
      text: 'Because dopamine sets both motor readiness and motivational priority, imbalances dramatically alter behaviour.',
      bullets: [
        'Parkinson disease: progressive loss of substantia nigra dopamine neurons leads to resting tremor, rigidity, and freezing.',
        'Addiction: supraphysiological dopamine surges train intense compulsive seeking for drugs or gambling.',
        'ADHD: low dopamine and noradrenaline tone in prefrontal networks impairs sustained attention and self-control.',
      ],
    },
    tryIt: 'Solve an anagram or finish a difficult puzzle. The quiet click of satisfaction when the solution lands is your VTA dopamine neurons firing in response to an internal reward.',
  },
  {
    id: 'serotonin',
    name: 'Serotonin',
    group: 'modulator',
    color: '#6be4ff',
    tagline: 'Broadcasts from the brainstem to modulate mood, patience, appetite, sleep, and pain.',
    analogy: 'A climate controller that sets the background emotional weather of the brain.',
    synapse: 'serotonin',
    pathwayId: 'serotonin-pathways',
    madeFrom: 'tryptophan',
    madeIn: ['raphe-nuclei'],
    overview: {
      text: 'Serotonin (5-hydroxytryptamine, or 5-HT) is synthesized by raphe nuclei neurons situated along the midline of the brainstem. Its axons project to almost every structure in the central nervous system. Rather than creating pure happiness, serotonin promotes patience, dampens impulsive reactions, tunes pain perception, and coordinates cycles of sleeping and waking.',
      bullets: [
        'Only about one to two percent of the body\'s total serotonin resides in the brain; the rest functions in the gut.',
        'Acts through at least 14 distinct receptor subtypes with diverse excitatory and inhibitory actions.',
        'Promotes behavioral patience, helping organisms tolerate delays when anticipating future rewards.',
      ],
    },
    tracts: [
      {
        id: 'rostral-raphe',
        name: 'Ascending raphe projection',
        from: 'raphe-nuclei',
        to: ['prefrontal-cortex', 'hippocampus', 'amygdala', 'striatum'],
        job: 'Modulating mood, threat evaluation, impulse control, and cognitive flexibility across forebrain networks',
        text: 'Rostral raphe neurons project broadly into cortex, limbic structures, and basal ganglia. Serotonin release buffers negative emotional reactivity in the amygdala and supports calm decision-making.',
        whenItFails: 'Impaired ascending transmission is linked to heightened anxiety, rumination, depression, and irritability.',
        whenBlocked: 'Blocking serotonin receptors can induce vivid perceptual distortions or alleviate nausea, depending on the subtype targeted.',
      },
      {
        id: 'caudal-raphe',
        name: 'Descending raphe projection',
        from: 'raphe-nuclei',
        to: ['spinal-cord'],
        job: 'Modulating spinal pain transmission and autonomic motor reflexes',
        text: 'Caudal raphe nuclei send descending axons into the dorsal horn of the spinal cord. Here serotonin inhibits incoming pain signals before they can ascend to consciousness.',
        whenItFails: 'Loss of descending inhibitory tone contributes to chronic widespread pain and fibromyalgia syndromes.',
        whenBlocked: 'Spinal pain sensitivity increases when descending monoamine pathways are disrupted.',
      },
    ],
    density: {
      'amygdala': 0.85,
      'hippocampus': 0.85,
      'prefrontal-cortex': 0.8,
      'hypothalamus': 0.75,
      'striatum': 0.6,
      'spinal-cord': 0.7,
    },
    receptors: [
      {
        id: '5-HT1A',
        family: 'Gi coupled inhibitory receptor',
        effect: 'inhibit',
        where: ['raphe-nuclei', 'hippocampus', 'prefrontal-cortex'],
        text: 'Acts as both a presynaptic autoreceptor and postsynaptic mediator that quiets target cells and reduces anxiety.',
      },
      {
        id: '5-HT2A',
        family: 'Gq coupled excitatory receptor',
        effect: 'modulate',
        where: ['prefrontal-cortex', 'visual-cortex', 'cingulate-cortex'],
        text: 'Depolarizes cortical pyramidal neurons, increasing cognitive flexibility and sensory cross-talk.',
      },
    ],
    life: {
      made: 'Tryptophan is converted to 5-hydroxytryptophan by tryptophan hydroxylase, and then decarboxylated to serotonin.',
      packed: 'Vesicular monoamine transporter 2 (VMAT2) concentrates serotonin into synaptic vesicles.',
      released: 'Spike-driven calcium entry causes exocytosis into the cleft and surrounding extracellular space.',
      binds: 'Serotonin binds multiple families of G-protein coupled receptors and ion channels.',
      cleared: 'The serotonin transporter (SERT) takes up serotonin back into the nerve terminal for repackaging or breakdown by MAO.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'fluoxetine',
        name: 'Fluoxetine (Prozac)',
        acts: 'reuptake-block',
        target: 'SERT',
        text: 'Inhibits the serotonin transporter, keeping serotonin active in the synapse longer to treat depression and obsessive compulsive disorder.',
      },
      {
        id: 'psilocin',
        name: 'Psilocin',
        acts: 'receptor-mimic',
        target: '5-HT2A',
        text: 'Acts as a partial agonist at 5-HT2A receptors, altering cortical sensory filtering and increasing associative neural connectivity.',
      },
      {
        id: 'ondansetron',
        name: 'Ondansetron',
        acts: 'receptor-block',
        target: '5-HT3',
        text: 'Blocks 5-HT3 ion channels in the brainstem and gut to prevent nausea and vomiting triggered by chemotherapy.',
      },
    ],
    breaks: {
      text: 'Alterations in serotonin signaling alter mood stability, sleep timing, and sensory gating.',
      bullets: [
        'Major depression: blunted serotonin signaling correlates with negative emotional bias, low resilience, and insomnia.',
        'Serotonin syndrome: dangerously high serotonin levels from drug interactions trigger hyperthermia, tremors, and seizures.',
        'Migraine: fluctuations in cranial serotonin tone trigger neurogenic inflammation and vascular headache episodes.',
      ],
    },
    tryIt: 'Notice the urge to act immediately when frustrated. The ability to pause, take a breath, and wait for a better moment relies on ascending serotonin projections checking impulsive motor bursts.',
  },
  {
    id: 'noradrenaline',
    name: 'Noradrenaline',
    group: 'modulator',
    color: '#7dffb2',
    tagline: 'Drives arousal, vigilance, and the fight-or-flight alert system across the brain.',
    analogy: 'The master volume dial that snaps the brain to high alert when novelty or danger strikes.',
    synapse: 'noradrenaline',
    pathwayId: 'noradrenaline-pathways',
    madeFrom: 'dopamine',
    madeIn: ['locus-coeruleus'],
    overview: {
      text: 'Noradrenaline (norepinephrine) is the primary alarm and vigilance messenger in the brain. Originating primarily from the locus coeruleus, a tiny pair of blue-tinted nuclei in the pons, noradrenergic axons arborize extensively to touch every level of the neuroaxis. When surprise, novelty, or threat arrives, noradrenaline spikes to focus attention and prepare the organism for urgent action.',
      bullets: [
        'A single locus coeruleus neuron can project axons that branch into cortex, thalamus, and spinal cord simultaneously.',
        'Sets the signal-to-noise ratio in sensory cortex, sharpening relevant inputs while suppressing background chatter.',
        'Drops to near-zero firing rates during REM sleep, allowing restful cortical recuperation.',
      ],
    },
    tracts: [
      {
        id: 'dorsal-noradrenergic',
        name: 'Ascending dorsal tegmental bundle',
        from: 'locus-coeruleus',
        to: ['prefrontal-cortex', 'thalamus', 'hippocampus', 'cerebellum'],
        job: 'Broadcasting vigilance, focusing spatial attention, and coordinating cortical alertness',
        text: 'Axons from the locus coeruleus ascend through the midbrain into forebrain targets. Noradrenaline increases sensory sensitivity in the thalamus and stabilizes working memory networks in the prefrontal cortex.',
        whenItFails: 'Underactivity leads to drowsiness, cognitive fatigue, and difficulty sustaining mental effort.',
        whenBlocked: 'Beta-blocking drugs reduce central and peripheral manifestations of acute performance anxiety.',
      },
      {
        id: 'ventral-noradrenergic',
        name: 'Descending bulbospinal projection',
        from: 'locus-coeruleus',
        to: ['hypothalamus', 'spinal-cord'],
        job: 'Activating sympathetic fight-or-flight responses and modulating spinal pain gates',
        text: 'Descending axons reach autonomic motor nuclei and the spinal dorsal horn. Noradrenaline accelerates heart rate, dilates bronchial passages, and closes spinal gates against acute pain during emergencies.',
        whenItFails: 'Impaired descending tone contributes to postural hypotension and increased chronic pain sensitivity.',
        whenBlocked: 'Centrally acting alpha-2 agonists suppress sympathetic outflow to lower blood pressure.',
      },
    ],
    density: {
      'prefrontal-cortex': 0.85,
      'thalamus': 0.8,
      'hippocampus': 0.75,
      'amygdala': 0.8,
      'hypothalamus': 0.7,
      'cerebellum': 0.65,
    },
    receptors: [
      {
        id: 'alpha-1',
        family: 'Gq coupled excitatory receptor',
        effect: 'excite',
        where: ['prefrontal-cortex', 'thalamus', 'hypothalamus'],
        text: 'Promotes cortical activation, wakefulness, and pupil dilation when noradrenaline surges during high stress.',
      },
      {
        id: 'alpha-2',
        family: 'Gi coupled inhibitory autoreceptor',
        effect: 'inhibit',
        where: ['locus-coeruleus', 'prefrontal-cortex'],
        text: 'High affinity receptor that optimizes working memory at moderate baseline levels and applies negative feedback to locus coeruleus firing.',
      },
      {
        id: 'beta-1',
        family: 'Gs coupled excitatory receptor',
        effect: 'excite',
        where: ['amygdala', 'hippocampus', 'motor-cortex'],
        text: 'Strengthens emotional memory consolidation during frightening or highly charged life experiences.',
      },
    ],
    life: {
      made: 'Dopamine is converted into noradrenaline inside synaptic vesicles by the enzyme dopamine beta-hydroxylase.',
      packed: 'Vesicular monoamine transporter 2 (VMAT2) pumps noradrenaline into dense-core vesicles.',
      released: 'High frequency firing triggers widespread volume release from axonal varicosities into target tissue.',
      binds: 'Noradrenaline stimulates alpha and beta adrenergic receptors across target cells.',
      cleared: 'The noradrenaline transporter (NET) clears transmitter from the extracellular space, supplemented by MAO and COMT.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'atomoxetine',
        name: 'Atomoxetine',
        acts: 'reuptake-block',
        target: 'NET',
        text: 'Selectively blocks the noradrenaline transporter in prefrontal cortex to improve focus and impulse control in ADHD.',
      },
      {
        id: 'propranolol',
        name: 'Propranolol',
        acts: 'receptor-block',
        target: 'beta-receptors',
        text: 'Blocks beta-adrenergic receptors, reducing stage fright, shaking hands, and racing heart during stressful performances.',
      },
      {
        id: 'clonidine',
        name: 'Clonidine',
        acts: 'receptor-mimic',
        target: 'alpha-2',
        text: 'Stimulates inhibitory alpha-2 autoreceptors in the locus coeruleus, dampening sympathetic storming and lowering blood pressure.',
      },
    ],
    breaks: {
      text: 'Because noradrenaline drives alertness, chronic overdrive produces panic while deficiency brings exhaustion.',
      bullets: [
        'Panic disorder: sudden spontaneous bursts of locus coeruleus firing trigger false alarms of impending catastrophe.',
        'PTSD: hyper-reactivity of adrenergic synapses over-consolidates traumatic memories and keeps vigilance exhausting.',
        'Autonomic failure: degeneration of noradrenergic neurons causes fainting upon standing due to uncompensated blood pressure drops.',
      ],
    },
    tryIt: 'Drop your keys onto a hard floor. The instantaneous surge of alertness, widening pupils, and quickened heartbeat before your conscious mind even names the sound is locus coeruleus noradrenaline flooding your brain.',
  },
  {
    id: 'acetylcholine',
    name: 'Acetylcholine',
    group: 'modulator',
    color: '#ffa36b',
    tagline: 'Coordinates muscular contraction, sharpens sensory attention, and facilitates memory encoding.',
    analogy: 'The spotlight operator that directs conscious attention onto the most informative details.',
    synapse: 'acetylcholine',
    pathwayId: 'acetylcholine-pathways',
    madeFrom: 'choline and acetyl-CoA',
    madeIn: ['basal-forebrain', 'pons'],
    overview: {
      text: 'Acetylcholine was the very first neurotransmitter identified. In the peripheral nervous system, it commands voluntary muscle contractions and drives parasympathetic rest-and-digest states. Inside the brain, cholinergic projections from the basal forebrain and brainstem act as an attention spotlight, heightening sensory sensitivity and allowing new memories to take root.',
      bullets: [
        'The essential link at every neuromuscular junction, translating motor neuron spikes into physical movement.',
        'Tilted toward high release during waking and REM sleep, but drops during deep slow-wave sleep.',
        'Enhances cortical plasticity so that attended sensory inputs are recorded into long term memory.',
      ],
    },
    tracts: [
      {
        id: 'basal-cortical',
        name: 'Basal forebrain cortical projection',
        from: 'basal-forebrain',
        to: ['prefrontal-cortex', 'hippocampus', 'temporal-lobe'],
        job: 'Sharpening sensory attention and facilitating synaptic encoding of new memories',
        text: 'Magnocellular cholinergic neurons in the basal forebrain send sweeping axons through the cerebral mantle and hippocampus. Acetylcholine release suppresses internal feedback and emphasizes external sensory inputs.',
        whenItFails: 'Early degeneration of these neurons in Alzheimer disease drives progressive memory loss and disorientation.',
        whenBlocked: 'Anticholinergic medications reliably provoke confusion, acute delirium, and short-term memory blackout.',
      },
      {
        id: 'pontomesencephalic',
        name: 'Pontomesencephalic tegmental tract',
        from: 'pons',
        to: ['thalamus'],
        job: 'Shifting the thalamus from burst-firing sleep mode into single-spike conscious transmission',
        text: 'Cholinergic clusters in the brainstem tegmentum project directly into the thalamus. By depolarizing relay cells, acetylcholine opens the sensory gates for waking consciousness and REM sleep dreaming.',
        whenItFails: 'Brainstem lesions can cause persistent somnolence, coma, or profound loss of sleep architecture.',
        whenBlocked: 'Interfering with brainstem acetylcholine suppresses REM sleep and dream generation.',
      },
    ],
    density: {
      'hippocampus': 0.9,
      'thalamus': 0.85,
      'prefrontal-cortex': 0.8,
      'temporal-lobe': 0.75,
      'striatum': 0.7,
      'motor-cortex': 0.75,
    },
    receptors: [
      {
        id: 'nAChR',
        family: 'Nicotinic ligand-gated ion channel',
        effect: 'excite',
        where: ['thalamus', 'striatum', 'prefrontal-cortex'],
        text: 'Fast pentameric channel permeable to sodium and calcium that depolarizes neurons and stimulates presynaptic transmitter release.',
      },
      {
        id: 'mAChR',
        family: 'Muscarinic G-protein coupled',
        effect: 'modulate',
        where: ['hippocampus', 'prefrontal-cortex', 'temporal-lobe'],
        text: 'Five subtypes (M1 to M5) that modulate potassium currents to sustain cortical attention and promote synaptic plasticity.',
      },
    ],
    life: {
      made: 'Choline acetyltransferase (ChAT) synthesizes acetylcholine from dietary choline and acetyl-coenzyme A.',
      packed: 'Vesicular acetylcholine transporters (VAChT) package acetylcholine into small clear synaptic vesicles.',
      released: 'Depolarization drives calcium influx, leading to rapid quantal exocytosis into the cleft.',
      binds: 'Acetylcholine binds postsynaptic nicotinic ion channels and muscarinic receptors.',
      cleared: 'Acetylcholinesterase (AChE) in the synaptic cleft rapidly cleaves acetylcholine into inactive choline and acetate within microseconds.',
      clearedBy: 'enzyme',
    },
    drugs: [
      {
        id: 'donepezil',
        name: 'Donepezil (Aricept)',
        acts: 'enzyme-block',
        target: 'AChE',
        text: 'Reversibly inhibits acetylcholinesterase, prolonging the survival of acetylcholine at synapses to support memory in Alzheimer disease.',
      },
      {
        id: 'nicotine',
        name: 'Nicotine',
        acts: 'receptor-mimic',
        target: 'nAChR',
        text: 'Directly stimulates nicotinic acetylcholine receptors, triggering brief increases in alertness, focus, and dopamine release.',
      },
      {
        id: 'atropine',
        name: 'Atropine',
        acts: 'receptor-block',
        target: 'mAChR',
        text: 'Competitively blocks muscarinic receptors, causing pupil dilation, dry mouth, increased heart rate, and confusion at high doses.',
      },
    ],
    breaks: {
      text: 'Disruptions in acetylcholine degrade memory acquisition and impair physical muscle movement.',
      bullets: [
        'Alzheimer disease: selective death of basal forebrain cholinergic neurons deprives hippocampus and cortex of encoding signals.',
        'Myasthenia gravis: autoimmune antibodies destroy muscle nicotinic receptors, causing profound fluctuating muscle fatigue.',
        'Anticholinergic toxidrome: overdoses of blocking drugs induce confusion, hallucinations, dilated pupils, and flushed dry skin.',
      ],
    },
    tryIt: 'Focus intently on the shapes of individual letters in this sentence. Basal forebrain acetylcholine is actively sharpening the receptive fields of your visual cortex to pick out subtle contrast differences.',
  },
];
