// Neuromodulators: Dopamine, Serotonin, Noradrenaline, Acetylcholine.

export default [
  {
    id: 'dopamine',
    name: 'Dopamine',
    group: 'modulator',
    color: '#b98cff',
    tagline: 'Signals reward surprises, tunes voluntary movement, and shapes motivation.',
    analogy: 'The reward highlighter that marks experiences that turned out better than you expected.',
    synapse: 'dopamine',
    pathwayId: 'dopamine-pathways',
    madeFrom: 'tyrosine',
    madeIn: ['substantia-nigra', 'vta', 'hypothalamus'],
    overview: {
      text: 'Dopamine comes from small clusters of [[neuron|neurons]] in the {{midbrain}} and {{hypothalamus}} that send fibres to vast areas of the brain. Instead of delivering quick sensory clicks, it acts as a [[neuromodulator]], changing how receptive circuits are to other messages. Surges of dopamine reward successful choices and help you start moving smoothly.',
      bullets: [
        'Made mainly by fewer than a million midbrain cells that broadcast to billions of connections.',
        'Fires strongly when an outcome is unexpectedly good, and dips when an expected reward fails to appear.',
        'Helps turn deliberate, conscious efforts into smooth, automatic habits.',
      ],
    },
    tracts: [
      {
        id: 'nigrostriatal',
        name: 'Nigrostriatal pathway',
        from: 'substantia-nigra',
        to: ['striatum'],
        job: 'Starting and smoothing voluntary physical movements',
        text: 'Fibres travel from the {{substantia-nigra}} into the {{striatum}}. Dopamine released here lowers the resistance on motor circuits, making it easy to start and coordinate movements.',
        whenItFails: 'Loss of these cells causes the tremors, stiff muscles, and frozen posture of Parkinson disease.',
        whenBlocked: 'Blocking dopamine here can make muscles rigid and trigger drug-induced Parkinsonism.',
      },
      {
        id: 'mesolimbic',
        name: 'Mesolimbic pathway',
        from: 'vta',
        to: ['nucleus-accumbens', 'amygdala'],
        job: 'Spotting valuable opportunities and driving motivation to seek them',
        text: 'Originating in the {{vta}}, this projection fans into the {{nucleus-accumbens}} and {{amygdala}}. It gives sights, sounds, and smells motivational pull, driving you to reach for useful goals.',
        whenItFails: 'Low activity causes a lack of drive, apathy, and difficulty feeling joy.',
        whenBlocked: 'Reduces intense cravings, but can also flatten emotional warmth and enthusiasm.',
      },
      {
        id: 'mesocortical',
        name: 'Mesocortical pathway',
        from: 'vta',
        to: ['prefrontal-cortex'],
        job: 'Protecting attention from distraction and sharpening working memory',
        text: 'Fibres from the {{vta}} fan out across the {{prefrontal-cortex}}. A healthy balance of dopamine keeps your mind on track, shielding your focus while staying flexible enough to notice new information.',
        whenItFails: 'Low dopamine in frontal circuits causes difficulty concentrating and impulsivity, as seen in ADHD.',
        whenBlocked: 'Heavy blockade can cause mental fatigue and cloud decision-making.',
      },
      {
        id: 'tuberoinfundibular',
        name: 'Tuberoinfundibular pathway',
        from: 'hypothalamus',
        to: ['pituitary'],
        job: 'Keeping the brake on pituitary milk hormone release',
        text: 'Cells in the {{hypothalamus}} release dopamine into tiny blood vessels leading to the {{pituitary}}. Here, dopamine acts as a natural brake to hold back the hormone prolactin when it is not needed.',
        whenItFails: 'Damage to this connection lifts the brake, causing elevated prolactin levels in the blood.',
        whenBlocked: 'Dopamine-blocking medicines can lead to unwanted milk production and breast soreness.',
      },
    ],
    density: {
      'striatum': 1.0,
      'nucleus-accumbens': 0.95,
      'prefrontal-cortex': 0.5,
      'amygdala': 0.45,
      'hippocampus': 0.35,
      'hypothalamus': 0.4,
    },
    receptors: [
      {
        id: 'D1',
        family: 'D1-like (Gs coupled)',
        effect: 'modulate',
        where: ['striatum', 'nucleus-accumbens', 'prefrontal-cortex'],
        text: 'Tunes target neurons by boosting internal energy messengers, encouraging striatal go circuits to initiate action.',
      },
      {
        id: 'D2',
        family: 'D2-like (Gi coupled)',
        effect: 'modulate',
        where: ['striatum', 'nucleus-accumbens', 'pituitary'],
        text: 'Tunes target neurons by calming internal messengers, quieting stop circuits and keeping prolactin in check.',
      },
    ],
    life: {
      made: 'Cells build dopamine from the dietary amino acid tyrosine in two enzyme steps.',
      packed: 'Vesicle pumps load dopamine molecules into storage bubbles inside the terminal.',
      released: 'An incoming electrical spike lets calcium in, prompting bubbles to fuse and release dopamine into the gap.',
      binds: 'Dopamine drifts across to stimulate D1 and D2 receptors on target cells.',
      cleared: 'Dopamine transporters vacuum the chemical back into the sending cell to end the signal.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'cocaine',
        name: 'Cocaine',
        acts: 'reuptake-block',
        target: 'DAT',
        text: 'Blocks the dopamine transporter, trapping dopamine in the gap to produce a temporary surge of energy and euphoria.',
      },
      {
        id: 'levodopa',
        name: 'Levodopa (L-DOPA)',
        acts: 'precursor',
        target: 'AADC',
        text: 'Crosses into the brain where surviving cells convert it into fresh dopamine, easing Parkinson symptoms.',
      },
      {
        id: 'haloperidol',
        name: 'Haloperidol',
        acts: 'receptor-block',
        target: 'D2',
        text: 'Blocks D2 dopamine receptors to quiet hallucinations and delusions during acute psychosis.',
      },
    ],
    breaks: {
      text: 'Because dopamine sets both motor readiness and motivational drive, shifts in its levels alter behaviour and movement.',
      bullets: [
        'Parkinson disease: loss of dopamine cells in the {{substantia-nigra}} causes tremors, muscle stiffness, and frozen steps.',
        'Addiction: surges from drugs hijack the reward prediction system, reinforcing compulsive habits.',
        'ADHD: low dopamine tone in the {{prefrontal-cortex}} makes it hard to maintain focus on everyday tasks.',
      ],
    },
    tryIt: 'Solve a puzzle or catch a falling pen. That brief burst of satisfaction when you succeed is your dopamine cells firing to reward a positive surprise.',
  },
  {
    id: 'serotonin',
    name: 'Serotonin',
    group: 'modulator',
    color: '#6be4ff',
    tagline: 'Broadcasts from the brainstem to steady mood, patience, appetite, sleep, and pain.',
    analogy: 'A climate controller setting the background emotional weather of your mind.',
    synapse: 'serotonin',
    pathwayId: 'serotonin-pathways',
    madeFrom: 'tryptophan',
    madeIn: ['raphe-nuclei'],
    overview: {
      text: 'Serotonin is made by cells in the {{raphe-nuclei}}, a string of clusters along the midline of the brainstem. Its axons spread to almost every corner of the central nervous system. Rather than creating pure pleasure, serotonin helps you stay patient, cushions emotional reactions, coordinates sleep cycles, and softens pain signals.',
      bullets: [
        'Over nine-tenths of the body\'s serotonin lives in the gut; only about one to two percent is in the brain.',
        'Acts through at least 14 different receptor types that tune cells in contrasting ways.',
        'Promotes behavioral patience, helping you wait calmly for rewards that take time.',
      ],
    },
    tracts: [
      {
        id: 'rostral-raphe',
        name: 'Ascending raphe projection',
        from: 'raphe-nuclei',
        to: ['prefrontal-cortex', 'hippocampus', 'amygdala', 'striatum'],
        job: 'Balancing mood, buffering stress, and supporting patient decision-making',
        text: 'Fibres ascend from the {{raphe-nuclei}} into the {{prefrontal-cortex}}, {{hippocampus}}, and {{amygdala}}. Serotonin softens fear responses in the amygdala and helps you think through stressful choices calmly.',
        whenItFails: 'Weakened signalling is linked to rumination, anxiety, low mood, and irritability.',
        whenBlocked: 'Blocking specific receptors can cause sensory distortion or stop nausea, depending on the target.',
      },
      {
        id: 'caudal-raphe',
        name: 'Descending raphe projection',
        from: 'raphe-nuclei',
        to: ['spinal-cord'],
        job: 'Dampening incoming pain signals in the spinal cord',
        text: 'Lower raphe cells send axons down into the {{spinal-cord}}. Serotonin released here acts as a natural gatekeeper, muting pain signals before they can travel up to conscious awareness.',
        whenItFails: 'Loss of this downward brake can lead to chronic body pain and tender points.',
        whenBlocked: 'Sensitivity to aches and physical discomfort increases when these pathways are interrupted.',
      },
    ],
    density: {
      'amygdala': 0.85,
      'hippocampus': 0.85,
      'prefrontal-cortex': 0.8,
      'hypothalamus': 0.75,
      'striatum': 0.6,
      'spinal-cord': 0.7,
    },
    receptors: [
      {
        id: '5-HT1A',
        family: 'Gi coupled inhibitory receptor',
        effect: 'inhibit',
        where: ['raphe-nuclei', 'hippocampus', 'prefrontal-cortex'],
        text: 'Acts as both a self-brake on serotonin cells and a calming influence on target circuits, easing anxiety.',
      },
      {
        id: '5-HT2A',
        family: 'Gq coupled excitatory receptor',
        effect: 'modulate',
        where: ['prefrontal-cortex', 'visual-cortex', 'cingulate-cortex'],
        text: 'Excites cortical neurons, encouraging flexible thinking and connections across different sensory areas.',
      },
    ],
    life: {
      made: 'Cells synthesize serotonin from tryptophan, an amino acid obtained from food.',
      packed: 'Transporter proteins pump serotonin into storage vesicles within the terminal.',
      released: 'Electrical spikes trigger calcium entry, releasing serotonin to diffuse into the gap and surrounding tissue.',
      binds: 'Serotonin touches a family of receptors on receiving cells to adjust their activity.',
      cleared: 'The serotonin transporter (SERT) collects molecules back into the terminal for recycling or breakdown.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'fluoxetine',
        name: 'Fluoxetine (Prozac)',
        acts: 'reuptake-block',
        target: 'SERT',
        text: 'Blocks the serotonin transporter, keeping serotonin in the gap longer to help ease depression and anxiety.',
      },
      {
        id: 'psilocin',
        name: 'Psilocin',
        acts: 'receptor-mimic',
        target: '5-HT2A',
        text: 'Stimulates 5-HT2A receptors in the cortex, loosening rigid patterns of thinking and altering sensory perception.',
      },
      {
        id: 'ondansetron',
        name: 'Ondansetron',
        acts: 'receptor-block',
        target: '5-HT3',
        text: 'Blocks 5-HT3 receptors in the gut and brainstem, preventing nausea and vomiting.',
      },
    ],
    breaks: {
      text: 'Because serotonin stabilizes emotional balance and sleep patterns, disruptions alter mood resilience.',
      bullets: [
        'Depression: reduced serotonin signaling is linked to persistent negative bias, poor sleep, and low energy.',
        'Serotonin syndrome: excessive buildup from drug interactions can cause dangerous fever, muscle tremors, and confusion.',
        'Migraine: rapid swings in cranial serotonin tone trigger sudden throbbing headaches and light sensitivity.',
      ],
    },
    tryIt: 'Notice the urge to snap back when someone cuts in front of you. Taking a breath and choosing to wait calmly relies on serotonin quieting impulsive reflexes.',
  },
  {
    id: 'noradrenaline',
    name: 'Noradrenaline',
    group: 'modulator',
    color: '#7dffb2',
    tagline: 'Snaps the brain to high alert, sharpens attention, and primes the body for action.',
    analogy: 'The volume dial that snaps the brain to high alert the moment something startling happens.',
    synapse: 'noradrenaline',
    pathwayId: 'noradrenaline-pathways',
    madeFrom: 'dopamine',
    madeIn: ['locus-coeruleus'],
    overview: {
      text: 'Noradrenaline is the brain\'s primary alarm and alertness messenger. Most of it comes from the {{locus-coeruleus}}, a tiny blue-tinted cluster in the {{pons}}. Even though this cluster contains only about 50,000 cells, its axons reach nearly every part of the brain and spinal cord, snapping circuits to attention when surprise or danger appears.',
      bullets: [
        'A single cell in the locus coeruleus can branch to touch the cortex, thalamus, and spinal cord at the same time.',
        'Sharpens signal-to-noise ratio in sensory areas, highlighting relevant inputs while muting background noise.',
        'Quiets down during deep sleep and drops to near zero during dreaming.',
      ],
    },
    tracts: [
      {
        id: 'dorsal-noradrenergic',
        name: 'Ascending dorsal tegmental bundle',
        from: 'locus-coeruleus',
        to: ['prefrontal-cortex', 'thalamus', 'hippocampus', 'cerebellum'],
        job: 'Broadcasting alertness, focusing attention, and sharpening sensory clarity',
        text: 'Axons climb from the {{locus-coeruleus}} through the midbrain into forebrain targets. Noradrenaline tunes sensory processing in the {{thalamus}} and stabilizes focus in the {{prefrontal-cortex}}.',
        whenItFails: 'Low activity brings brain fog, drowsiness, and difficulty sustaining mental effort.',
        whenBlocked: 'Beta-blocker medications reduce shaky hands, racing heart, and nervousness before public speaking.',
      },
      {
        id: 'ventral-noradrenergic',
        name: 'Autonomic and spinal noradrenergic projections',
        from: 'locus-coeruleus',
        to: ['hypothalamus', 'spinal-cord'],
        job: 'Activating fight-or-flight body responses and muting spinal pain',
        text: 'Noradrenergic fibres ascend into the {{hypothalamus}} and descend down the {{spinal-cord}}. Noradrenaline quickens your heart rate, dilates airways, and closes pain gates in the spine during emergencies.',
        whenItFails: 'Weakened signalling can cause dizziness on standing due to poor blood pressure regulation.',
        whenBlocked: 'Blood pressure and sympathetic nerve activity drop when central alpha-2 receptors are stimulated.',
      },
    ],
    density: {
      'prefrontal-cortex': 0.85,
      'thalamus': 0.8,
      'hippocampus': 0.75,
      'amygdala': 0.8,
      'hypothalamus': 0.7,
      'cerebellum': 0.65,
    },
    receptors: [
      {
        id: 'alpha-1',
        family: 'Gq coupled excitatory receptor',
        effect: 'excite',
        where: ['prefrontal-cortex', 'thalamus', 'hypothalamus'],
        text: 'Promotes wakefulness, widens pupils, and primes motor circuits when noradrenaline surges under high stress.',
      },
      {
        id: 'alpha-2',
        family: 'Gi coupled inhibitory autoreceptor',
        effect: 'inhibit',
        where: ['locus-coeruleus', 'prefrontal-cortex'],
        text: 'Optimizes working memory at gentle resting levels and acts as a brake to keep locus coeruleus firing from running wild.',
      },
      {
        id: 'beta-1',
        family: 'Gs coupled excitatory receptor',
        effect: 'excite',
        where: ['amygdala', 'hippocampus', 'motor-cortex'],
        text: 'Strengthens emotional memories during frightening or highly charged experiences.',
      },
    ],
    life: {
      made: 'Cells convert dopamine into noradrenaline inside vesicles with the help of a dedicated enzyme.',
      packed: 'Vesicle pumps load noradrenaline into storage bubbles ready for release.',
      released: 'Bursts of electrical firing trigger release from beaded axon swellings that bathe surrounding tissue.',
      binds: 'Noradrenaline attaches to alpha and beta receptors on target neurons and blood vessels.',
      cleared: 'The noradrenaline transporter (NET) collects molecules back into the terminal for recycling.',
      clearedBy: 'reuptake',
    },
    drugs: [
      {
        id: 'atomoxetine',
        name: 'Atomoxetine',
        acts: 'reuptake-block',
        target: 'NET',
        text: 'Blocks the noradrenaline transporter in the frontal cortex, improving focus and impulse control in ADHD.',
      },
      {
        id: 'propranolol',
        name: 'Propranolol',
        acts: 'receptor-block',
        target: 'beta-receptors',
        text: 'Blocks beta receptors to steady a racing pulse and trembling hands during high-stress performances.',
      },
      {
        id: 'clonidine',
        name: 'Clonidine',
        acts: 'receptor-mimic',
        target: 'alpha-2',
        text: 'Stimulates inhibitory alpha-2 autoreceptors, gently turning down sympathetic alarm signals and lowering blood pressure.',
      },
    ],
    breaks: {
      text: 'Because noradrenaline controls alertness, chronic overdrive creates constant anxiety while too little leaves you exhausted.',
      bullets: [
        'Panic attacks: sudden unprovoked bursts from the {{locus-coeruleus}} sound a false alarm of immediate catastrophe.',
        'PTSD: hyperactive noradrenaline circuits over-record traumatic memories and keep vigilance exhausting.',
        'Autonomic failure: loss of noradrenaline cells causes fainting when standing, as blood pressure fails to adjust.',
      ],
    },
    tryIt: 'Drop your keys onto a hard floor. That immediate jump in alertness, wide eyes, and quick heartbeat before you even name the sound is noradrenaline flooding your circuits.',
  },
  {
    id: 'acetylcholine',
    name: 'Acetylcholine',
    group: 'modulator',
    color: '#ffa36b',
    tagline: 'Commands muscle contraction, sharpens attention, and helps encode new memories.',
    analogy: 'The spotlight operator directing conscious focus onto the clearest details in front of you.',
    synapse: 'acetylcholine',
    pathwayId: 'acetylcholine-pathways',
    madeFrom: 'choline and acetyl-CoA',
    madeIn: ['basal-forebrain', 'pons'],
    overview: {
      text: 'Acetylcholine was the very first neurotransmitter ever discovered. Outside the brain, it triggers voluntary muscle contractions and powers rest-and-digest recovery. Inside the brain, projections from the {{basal-forebrain}} and {{pons}} act as an attention spotlight, heightening sensory clarity and helping new memories take hold.',
      bullets: [
        'The essential link at every neuromuscular junction, translating motor neuron pulses into physical movement.',
        'Levels are highest during alert wakefulness and dream sleep, but drop during deep resting sleep.',
        'Boosts synaptic plasticity so the experiences you pay attention to get recorded for the long term.',
      ],
    },
    tracts: [
      {
        id: 'basal-cortical',
        name: 'Basal forebrain cortical projection',
        from: 'basal-forebrain',
        to: ['prefrontal-cortex', 'hippocampus', 'temporal-lobe'],
        job: 'Focusing sensory attention and allowing new memories to form',
        text: 'Large cells in the {{basal-forebrain}} send long axons across the cortex and into the {{hippocampus}}. Acetylcholine released here sharpens external sensory input and helps the hippocampus record fresh memories.',
        whenItFails: 'Early loss of these cells in Alzheimer disease causes progressive memory loss and confusion.',
        whenBlocked: 'Medications that block acetylcholine can trigger sudden disorientation and temporary memory blanks.',
      },
      {
        id: 'pontomesencephalic',
        name: 'Pontomesencephalic tegmental tract',
        from: 'pons',
        to: ['thalamus'],
        job: 'Switching the thalamus from sleep mode to alert sensory transmission',
        text: 'Clusters in the {{pons}} project straight into the {{thalamus}}. Acetylcholine awakens relay cells, opening sensory gates for conscious waking perception and dream sleep.',
        whenItFails: 'Damage here can cause profound lethargy, loss of sleep structure, or coma.',
        whenBlocked: 'Interfering with brainstem acetylcholine suppresses dream-rich REM sleep.',
      },
    ],
    density: {
      'hippocampus': 0.9,
      'thalamus': 0.85,
      'prefrontal-cortex': 0.8,
      'temporal-lobe': 0.75,
      'striatum': 0.7,
      'motor-cortex': 0.75,
    },
    receptors: [
      {
        id: 'nAChR',
        family: 'Nicotinic ligand-gated ion channel',
        effect: 'excite',
        where: ['thalamus', 'striatum', 'prefrontal-cortex'],
        text: 'Fast ion channel that opens directly to let sodium and calcium rush in, exciting the cell and promoting transmitter release.',
      },
      {
        id: 'mAChR',
        family: 'Muscarinic G-protein coupled',
        effect: 'modulate',
        where: ['hippocampus', 'prefrontal-cortex', 'temporal-lobe'],
        text: 'Five subtypes that tune internal cell messengers to sustain attention and support memory formation.',
      },
    ],
    life: {
      made: 'An enzyme combines choline from food with acetyl molecules to synthesize acetylcholine.',
      packed: 'Transporter pumps pack acetylcholine into small clear vesicles inside the terminal.',
      released: 'An electrical spike triggers calcium influx, causing vesicles to empty acetylcholine into the gap.',
      binds: 'Acetylcholine attaches to nicotinic ion gates and muscarinic receptors on target cells.',
      cleared: 'A fast-acting enzyme in the gap chops acetylcholine into inactive pieces within a split second.',
      clearedBy: 'enzyme',
    },
    drugs: [
      {
        id: 'donepezil',
        name: 'Donepezil (Aricept)',
        acts: 'enzyme-block',
        target: 'AChE',
        text: 'Slows down the enzyme that breaks down acetylcholine, helping remaining molecules survive longer to support memory in Alzheimer disease.',
      },
      {
        id: 'nicotine',
        name: 'Nicotine',
        acts: 'receptor-mimic',
        target: 'nAChR',
        text: 'Mimics acetylcholine at nicotinic receptors, briefly boosting alertness, focus, and dopamine release.',
      },
      {
        id: 'atropine',
        name: 'Atropine',
        acts: 'receptor-block',
        target: 'mAChR',
        text: 'Blocks muscarinic receptors, causing wide pupils, a dry mouth, and a faster heartbeat.',
      },
    ],
    breaks: {
      text: 'Disruptions in acetylcholine undermine memory formation and weaken muscular contraction.',
      bullets: [
        'Alzheimer disease: the selective loss of cholinergic cells in the {{basal-forebrain}} deprives the cortex and hippocampus of encoding signals.',
        'Myasthenia gravis: antibodies attack muscle acetylcholine receptors, causing muscles to tire and weaken quickly.',
        'Anticholinergic confusion: high doses of blocking medicines cause dry mouth, dilated pupils, and acute disorientation.',
      ],
    },
    tryIt: 'Focus intently on the curved shape of a single letter on your screen. Basal forebrain acetylcholine is actively sharpening the contrast in your visual cortex to bring that shape into clear focus.',
  },
];
