// Pathway evidence registry.
// Each record is keyed by pathway id and stores editorial review metadata,
// factual claims with evidentiary basis and source locators, route semantics,
// and declared related content targets.

export default {
  'seeing': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'seeing-retina',
        stepId: 'retina-photons',
        field: 'text',
        claim: 'Photoreceptors convert light into electrical signals and retinal ganglion axons form the optic nerve with hemidecussation at the chiasm.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 11: well-established vertebrate visual anatomy.',
      },
      {
        id: 'seeing-thalamus',
        stepId: 'thalamus-relay',
        field: 'text',
        claim: 'Retinogeniculate axons relay in the lateral geniculate nucleus of the thalamus before projecting to primary visual cortex.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 12: LGN retinotopic organization and cortical feedback.',
      },
      {
        id: 'seeing-v1',
        stepId: 'visual-cortex-features',
        field: 'text',
        claim: 'V1 neurons exhibit orientation, spatial frequency, and motion tuning, tiling visual space.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 22: Hubel & Wiesel classical receptive field architecture.',
      },
      {
        id: 'seeing-dorsal-stream',
        stepId: 'dorsal-where-stream',
        field: 'text',
        claim: 'The dorsal stream projects toward posterior parietal cortex, supporting spatial localization and action guidance.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 23: Goodale & Milner two-streams framework.',
      },
      {
        id: 'seeing-ventral-stream',
        stepId: 'ventral-what-stream',
        field: 'text',
        claim: 'The ventral stream projects toward inferior temporal cortex, supporting object and face recognition, with ongoing cross-talk between streams.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 23: streams interact extensively rather than operating as isolated pipes.',
      },
    ],
    routeNotes: [
      { stepId: 'thalamus-relay', from: 'eye', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Optic nerve and tract fibres terminating in lateral geniculate nucleus.' },
      { stepId: 'visual-cortex-features', from: 'thalamus', to: 'visual-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Optic radiations from LGN to primary visual cortex.' },
      { stepId: 'dorsal-where-stream', from: 'visual-cortex', to: 'posterior-parietal', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Dorsal stream pathway across V2, V3, MT/V5 to posterior parietal areas.' },
      { stepId: 'ventral-what-stream', from: 'visual-cortex', to: 'temporal-lobe', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Ventral stream pathway across V2, V4 to inferior temporal cortex.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'visual-cortex', field: 'levels.overview.text' },
    ],
  },

  'smelling': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'smell-tagline-bypass',
        field: 'tagline',
        claim: 'Smell bypasses an initial thalamic relay to reach primary olfactory cortex, though thalamic circuits participate in downstream processing.',
        sourceIds: ['pmc5362339-olfactory'],
        basis: 'established-anatomy',
        limits: 'PMC5362339 introduction: primary sensory station bypasses thalamus, but mediodorsal thalamus is recruited in subsequent networks. Current tagline needs qualification.',
      },
      {
        id: 'smell-nasal-binding',
        stepId: 'molecules-in-nose',
        field: 'text',
        claim: 'Odorants bind olfactory receptor neurons in the nasal olfactory epithelium.',
        sourceIds: ['pmc5362339-olfactory'],
        basis: 'established-anatomy',
        limits: 'PMC5362339: well-established odor transduction cascade.',
      },
      {
        id: 'smell-bulb-glomeruli',
        stepId: 'olfactory-bulb-sorting',
        field: 'text',
        claim: 'Olfactory receptor axons converge onto glomeruli in the olfactory bulb to generate odor representations.',
        sourceIds: ['pmc5362339-olfactory'],
        basis: 'established-anatomy',
        limits: 'PMC5362339: glomerular sorting and mitral/tufted cell projection.',
      },
      {
        id: 'smell-limbic-access',
        stepId: 'limbic-memory-route',
        field: 'text',
        claim: 'Bulb outputs project to piriform cortex and cortical amygdala without an initial thalamic relay; hippocampal access occurs through entorhinal and cortical relays.',
        sourceIds: ['pmc5362339-olfactory'],
        basis: 'established-anatomy',
        limits: 'PMC5362339 section on Cortico/Thalamo-cortical and limbic networks: bulb outputs connect to primary olfactory cortex and cortical amygdala; hippocampal access is mediated via entorhinal cortex.',
      },
      {
        id: 'smell-flavor-orbitofrontal',
        stepId: 'flavor-and-recognition',
        field: 'text',
        claim: 'Olfactory signals reach insular and orbitofrontal cortex to integrate flavor and support conscious recognition.',
        sourceIds: ['pmc5362339-olfactory'],
        basis: 'mixed',
        limits: 'PMC5362339: secondary processing engages mediodorsal thalamus and orbitofrontal loops.',
      },
    ],
    routeNotes: [
      { stepId: 'olfactory-bulb-sorting', from: 'nose', to: 'olfactory-bulb', semantics: 'direct', sourceIds: ['pmc5362339-olfactory'], note: 'Olfactory nerve fila traversing cribriform plate to olfactory bulb.' },
      { stepId: 'limbic-memory-route', from: 'olfactory-bulb', to: 'amygdala', semantics: 'direct', sourceIds: ['pmc5362339-olfactory'], note: 'Lateral olfactory tract projection to cortical amygdala nuclei.' },
      { stepId: 'limbic-memory-route', from: 'amygdala', to: 'hippocampus', semantics: 'multi-hop', sourceIds: ['pmc5362339-olfactory'], note: 'Multi-hop route: signals reach the hippocampus via adjacent entorhinal and medial temporal cortical gateways.' },
      { stepId: 'flavor-and-recognition', from: 'olfactory-bulb', to: 'insula', semantics: 'multi-hop', sourceIds: ['pmc5362339-olfactory'], note: 'Secondary projection via primary olfactory cortex.' },
      { stepId: 'flavor-and-recognition', from: 'olfactory-bulb', to: 'prefrontal-cortex', semantics: 'multi-hop', sourceIds: ['pmc5362339-olfactory'], note: 'Orbitofrontal route via piriform cortex and mediodorsal thalamus.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'glossary', id: 'olfactory bulb', field: 'olfactory bulb' },
    ],
  },

  'moving': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'moving-goal',
        stepId: 'goal-formation',
        field: 'text',
        claim: 'Prefrontal networks maintain goal representations before action selection.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 33: motor planning and working memory.',
      },
      {
        id: 'moving-action-selection',
        stepId: 'action-selection',
        field: 'text',
        claim: 'Striatal and globus pallidus microcircuits contribute to action selection by modulating tonic pallidal inhibition for chosen movements.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 38: basal ganglia direct and indirect pathway interactions.',
      },
      {
        id: 'moving-thalamic-disinhibition',
        stepId: 'basal-ganglia-gate',
        field: 'text',
        claim: 'Basal ganglia output modulates thalamocortical motor drive with dopamine tuning striatal plasticity.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 38: classical disinhibition model represents a simplified framework of continuous modulation.',
      },
      {
        id: 'moving-cortex-commands',
        stepId: 'cortex-commands',
        field: 'text',
        claim: 'Primary motor cortex pyramidal cells contribute to descending motor trajectories.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 17: population vectors and corticospinal outputs.',
      },
      {
        id: 'moving-brainstem-decussation',
        stepId: 'brainstem-descent',
        field: 'text',
        claim: 'Corticospinal fibres descend through midbrain, pons, and cross in the medullary pyramids.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 17: pyramidal decussation occurs for approximately 90 percent of lateral corticospinal tract axons.',
      },
      {
        id: 'moving-motoneurons',
        stepId: 'spinal-muscle-output',
        field: 'text',
        claim: 'Descending upper motor commands synapse onto spinal motor neurons that release acetylcholine at the neuromuscular junction to contract skeletal muscle fibres.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 16: neuromuscular junction physiology.',
      },
      {
        id: 'moving-cerebellar-correction',
        stepId: 'cerebellar-correction',
        field: 'text',
        claim: 'The cerebellum receives efference copy via the pons and sensory feedback, sending timing corrections back to motor cortex.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 37: cerebellar internal forward models.',
      },
    ],
    routeNotes: [
      { stepId: 'action-selection', from: 'prefrontal-cortex', to: 'striatum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Corticostriatal glutamatergic projection.' },
      { stepId: 'action-selection', from: 'striatum', to: 'globus-pallidus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Striatopallidal GABAergic projection.' },
      { stepId: 'basal-ganglia-gate', from: 'globus-pallidus', to: 'thalamus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Pallidothalamic inhibitory projection.' },
      { stepId: 'basal-ganglia-gate', from: 'substantia-nigra', to: 'striatum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Nigrostriatal dopaminergic tract.' },
      { stepId: 'cortex-commands', from: 'thalamus', to: 'motor-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Thalamocortical motor relay from ventral anterior and ventral lateral nuclei.' },
      { stepId: 'brainstem-descent', from: 'motor-cortex', to: 'midbrain', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Corticospinal fibres traversing cerebral peduncles.' },
      { stepId: 'brainstem-descent', from: 'midbrain', to: 'medulla', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Descent to medullary pyramids.' },
      { stepId: 'spinal-muscle-output', from: 'medulla', to: 'spinal-cord', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Lateral corticospinal tract descent in spinal cord.' },
      { stepId: 'spinal-muscle-output', from: 'spinal-cord', to: 'hand', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Lower motor neuron peripheral nerve innervation.' },
      { stepId: 'cerebellar-correction', from: 'motor-cortex', to: 'pons', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Corticopontine projection carrying efference copy.' },
      { stepId: 'cerebellar-correction', from: 'pons', to: 'cerebellum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Pontocerebellar mossy fibre projection.' },
      { stepId: 'cerebellar-correction', from: 'cerebellum', to: 'thalamus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Dentatothalamic projection.' },
      { stepId: 'cerebellar-correction', from: 'thalamus', to: 'motor-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Thalamocortical feedback.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'motor-cortex', field: 'levels.overview.text' },
      { kind: 'structure', id: 'striatum', field: 'levels.overview.text' },
    ],
  },

  'remembering': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'remembering-cortical-features',
        stepId: 'cortical-experience',
        field: 'text',
        claim: 'Sensory features of an event are processed across distributed cortical networks.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 55: episodic memory encoding.',
      },
      {
        id: 'remembering-hippocampal-binding',
        stepId: 'hippocampal-binding',
        field: 'text',
        claim: 'The hippocampus binds multidimensional cortical representations into an indexed episodic trace.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 55: relational binding and pattern separation/completion.',
      },
      {
        id: 'remembering-amygdala-modulation',
        stepId: 'emotional-weight',
        field: 'text',
        claim: 'Amygdala arousal and neuromodulators enhance memory consolidation, though emotion does not guarantee complete factual accuracy.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 55: emotional enhancement of central features with potential peripheral trade-offs.',
      },
      {
        id: 'remembering-papez-circuit',
        stepId: 'papez-loop',
        field: 'text',
        claim: 'The Papez circuit (hippocampus, mammillary bodies, anterior thalamus, cingulate) forms part of an extended episodic memory network rather than acting as an isolated storage depot.',
        sourceIds: ['purves-neuroscience-6e', 'kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 31 and Kandel ch. 55: diencephalic and medial temporal components of declarative memory; Korsakoff syndrome disrupts anterior thalamic and mammillary body relays.',
      },
      {
        id: 'remembering-consolidation',
        stepId: 'systems-consolidation',
        field: 'text',
        claim: 'Systems consolidation gradually reorganizes memories across neocortical networks over time, with vivid episodic details retaining hippocampal dependence.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 55: standard consolidation theory versus multiple trace theory.',
      },
    ],
    routeNotes: [
      { stepId: 'hippocampal-binding', from: 'temporal-lobe', to: 'hippocampus', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Perirhinal and entorhinal cortex relay to hippocampal formation.' },
      { stepId: 'hippocampal-binding', from: 'parietal-lobe', to: 'hippocampus', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Parahippocampal and entorhinal cortex relay to hippocampal formation.' },
      { stepId: 'emotional-weight', from: 'amygdala', to: 'hippocampus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Basolateral amygdala modulation of hippocampal synaptic plasticity.' },
      { stepId: 'papez-loop', from: 'hippocampus', to: 'mammillary-bodies', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Fornix projection.' },
      { stepId: 'papez-loop', from: 'mammillary-bodies', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Mammillothalamic tract to anterior thalamic nuclei.' },
      { stepId: 'papez-loop', from: 'thalamus', to: 'cingulate-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Thalamocortical projection to cingulate cortex.' },
      { stepId: 'papez-loop', from: 'cingulate-cortex', to: 'hippocampus', semantics: 'multi-hop', sourceIds: ['purves-neuroscience-6e'], note: 'Cingulum bundle projection via entorhinal cortex.' },
      { stepId: 'systems-consolidation', from: 'hippocampus', to: 'temporal-lobe', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Retrograde cortical projection during reactivation.' },
      { stepId: 'systems-consolidation', from: 'hippocampus', to: 'prefrontal-cortex', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Direct and thalamic relays to medial prefrontal cortex during consolidation.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'hippocampus', field: 'levels.overview.text' },
    ],
  },

  'fear': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'fear-threat-detection',
        stepId: 'threat-movement',
        field: 'text',
        claim: 'Visual detection of motion and coarse shape prompts rapid threat evaluation before conscious identification.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 48: fear processing and threat salience.',
      },
      {
        id: 'fear-subcortical-route',
        stepId: 'early-warning',
        field: 'text',
        claim: 'Sensory inputs influence the amygdala through thalamic and cortical routes; direct thalamo-amygdalar contribution to visual fear in humans remains an active research area.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'mixed',
        limits: 'Frontiers 2015: distinction between robust rodent auditory thalamo-amygdala pathway and debated human visual low-road.',
      },
      {
        id: 'fear-autonomic-output',
        stepId: 'body-reaction',
        field: 'text',
        claim: 'Amygdala central nucleus projections to hypothalamus and brainstem drive autonomic and motor defense responses.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'established-anatomy',
        limits: 'Frontiers 2015 section 2: freezing (PAG) and autonomic arousal (hypothalamus).',
      },
      {
        id: 'fear-cortical-reappraisal',
        stepId: 'cortical-detail',
        field: 'text',
        claim: 'Cortical visual processing provides fine details to update the initial threat estimate.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 48: cortical sensory inputs to basolateral amygdala.',
      },
      {
        id: 'fear-prefrontal-inhibition',
        stepId: 'safety-reappraisal',
        field: 'text',
        claim: 'Prefrontal cortex modulates amygdala output by activating inhibitory interneurons, facilitating safety reappraisal and reducing autonomic distress alarms.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'mixed',
        limits: 'Frontiers 2015 section 2.2: top-down prefrontal regulation and extinction circuitry recruitment.',
      },
    ],
    routeNotes: [
      { stepId: 'early-warning', from: 'eye', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Retinogeniculate and retinocollicular pathways.' },
      { stepId: 'early-warning', from: 'thalamus', to: 'amygdala', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Subcortical sensory input to basolateral amygdala.' },
      { stepId: 'body-reaction', from: 'amygdala', to: 'hypothalamus', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Stria terminalis and ventral amygdalofugal pathway to lateral hypothalamus.' },
      { stepId: 'body-reaction', from: 'amygdala', to: 'midbrain', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Central amygdala projection to periaqueductal gray.' },
      { stepId: 'cortical-detail', from: 'thalamus', to: 'visual-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Geniculocalcarine optic radiation.' },
      { stepId: 'cortical-detail', from: 'visual-cortex', to: 'amygdala', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Ventral visual stream projections to basolateral amygdala.' },
      { stepId: 'safety-reappraisal', from: 'prefrontal-cortex', to: 'amygdala', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Medial and ventromedial prefrontal projections regulating amygdala output.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'amygdala', field: 'levels.overview.text' },
    ],
  },

  'hearing-speech': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'hearing-cochlea',
        stepId: 'inner-ear-sound',
        field: 'text',
        claim: 'Cochlear hair cells transduce sound pressure waves into auditory nerve action potentials with tonotopic frequency tuning.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 13: auditory transduction and tonotopy.',
      },
      {
        id: 'hearing-brainstem',
        stepId: 'brainstem-computation',
        field: 'text',
        claim: 'Cochlear nuclei and superior olivary complex compute binaural time and level differences for sound localization.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 13: interaural time and level difference processing.',
      },
      {
        id: 'hearing-thalamus',
        stepId: 'thalamus-sound-relay',
        field: 'text',
        claim: 'Auditory signals relay through the medial geniculate body of the thalamus with extensive corticothalamic feedback.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 13: medial geniculate complex connectivity.',
      },
      {
        id: 'hearing-auditory-cortex',
        stepId: 'auditory-cortex-patterns',
        field: 'text',
        claim: 'Auditory cortex extracts spectrotemporal acoustic patterns with parallel engagement of speech-sensitive networks.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 27: cortical auditory organization.',
      },
      {
        id: 'hearing-wernicke-semantics',
        stepId: 'wernicke-comprehension',
        field: 'text',
        claim: 'Speech sounds connect with lexical and semantic meaning across distributed superior/middle temporal and parietal networks.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 54: modern dual-stream language model expands beyond classic Wernicke area.',
      },
      {
        id: 'hearing-broca-planning',
        stepId: 'broca-speech-planning',
        field: 'text',
        claim: 'Frontal language regions including Broca area coordinate phonological and articulatory planning in two-way dialogue with temporal areas.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 54: dorsal language stream and arcuate fasciculus interaction.',
      },
      {
        id: 'hearing-motor-vocal',
        stepId: 'motor-vocalisation',
        field: 'text',
        claim: 'Motor cortex drives vocal tract articulators with auditory feedback loops monitoring speech production in real time.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 54: sensorimotor integration in speech production.',
      },
    ],
    routeNotes: [
      { stepId: 'brainstem-computation', from: 'ear', to: 'pons', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Cranial nerve VIII fibres to cochlear nuclei.' },
      { stepId: 'brainstem-computation', from: 'pons', to: 'midbrain', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Lateral lemniscus fibres to inferior colliculus.' },
      { stepId: 'thalamus-sound-relay', from: 'midbrain', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Brachium of inferior colliculus to medial geniculate nucleus.' },
      { stepId: 'auditory-cortex-patterns', from: 'thalamus', to: 'auditory-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Auditory radiations to primary auditory cortex.' },
      { stepId: 'wernicke-comprehension', from: 'auditory-cortex', to: 'wernickes-area', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Intracortical association fibres within superior temporal gyrus.' },
      { stepId: 'broca-speech-planning', from: 'wernickes-area', to: 'brocas-area', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Arcuate fasciculus and superior longitudinal fasciculus with bidirectional exchange.' },
      { stepId: 'motor-vocalisation', from: 'brocas-area', to: 'motor-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Prefrontal and premotor connections to ventral primary motor cortex.' },
      { stepId: 'motor-vocalisation', from: 'motor-cortex', to: 'auditory-cortex', semantics: 'functional', sourceIds: ['kandel-principles-6e'], note: 'Auditory feedback loop during vocalization.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'auditory-cortex', field: 'levels.overview.text' },
      { kind: 'structure', id: 'brocas-area', field: 'levels.overview.text' },
      { kind: 'structure', id: 'wernickes-area', field: 'levels.overview.text' },
    ],
  },

  'pain': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'pain-nociceptors',
        stepId: 'fingertip-prick',
        field: 'text',
        claim: 'Tissue damage activates high-threshold mechanothermal A-delta and polymodal C nociceptors in peripheral skin.',
        sourceIds: ['pmc5883380-5ht-pain'],
        basis: 'established-anatomy',
        limits: 'PMC5883380: standard nociceptive transduction taxonomy.',
      },
      {
        id: 'pain-spinal-gate',
        stepId: 'spinal-gate',
        field: 'text',
        claim: 'In the spinal dorsal horn, local interneurons modulate nociceptive transmission according to gate control mechanisms.',
        sourceIds: ['pmc5883380-5ht-pain'],
        basis: 'established-anatomy',
        limits: 'PMC5883380: substantia gelatinosa interneuronal gating.',
      },
      {
        id: 'pain-thalamic-relay',
        stepId: 'thalamic-pain-relay',
        field: 'text',
        claim: 'Spinothalamic ascending fibres relay in lateral and medial thalamic nuclei, diverging toward sensory and affective systems.',
        sourceIds: ['pmc5883380-5ht-pain'],
        basis: 'established-anatomy',
        limits: 'Ventral posterolateral nucleus versus intralaminar and medial thalamic nuclei.',
      },
      {
        id: 'pain-somatosensory',
        stepId: 'somatosensory-localisation',
        field: 'text',
        claim: 'Primary and secondary somatosensory cortex encode spatial localization, intensity, and physical quality of pain.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 24: sensory-discriminative dimension of pain.',
      },
      {
        id: 'pain-affective-dimension',
        stepId: 'affective-sting',
        field: 'text',
        claim: 'Anterior insula and anterior cingulate cortex process the unpleasant, affective-motivational dimension of pain.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 24: affective-motivational pain network. Suffering reflects distributed network interaction rather than isolated centers.',
      },
      {
        id: 'pain-descending-modulation',
        stepId: 'descending-modulation',
        field: 'text',
        claim: 'Descending pathways from midbrain PAG and raphe nuclei modulate spinal nociception, with serotonin capable of suppressing or facilitating transmission depending on receptor subtypes.',
        sourceIds: ['pmc5883380-5ht-pain'],
        basis: 'mixed',
        limits: 'PMC5883380 abstract and review: 5-HT1A/B mediate antinociception while 5-HT2 and 5-HT3 can promote pronociceptive facilitation. Current text oversimplifies descending serotonin as a uniform brake.',
      },
    ],
    routeNotes: [
      { stepId: 'spinal-gate', from: 'hand', to: 'spinal-cord', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Primary afferent nociceptor central axons entering dorsal horn.' },
      { stepId: 'thalamic-pain-relay', from: 'spinal-cord', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Ascending spinothalamic tract.' },
      { stepId: 'somatosensory-localisation', from: 'thalamus', to: 'somatosensory-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Thalamocortical projection from VPL to S1.' },
      { stepId: 'affective-sting', from: 'thalamus', to: 'insula', semantics: 'multi-hop', sourceIds: ['kandel-principles-6e'], note: 'Posterior and anterior insula projections via ventral posterior inferior thalamus.' },
      { stepId: 'affective-sting', from: 'thalamus', to: 'cingulate-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Medial thalamic nuclei projection to anterior cingulate cortex.' },
      { stepId: 'descending-modulation', from: 'midbrain', to: 'raphe-nuclei', semantics: 'direct', sourceIds: ['pmc5883380-5ht-pain'], note: 'Periaqueductal gray projection to rostral ventromedial medulla and raphe magnus.' },
      { stepId: 'descending-modulation', from: 'raphe-nuclei', to: 'spinal-cord', semantics: 'direct', sourceIds: ['pmc5883380-5ht-pain'], note: 'Dorsolateral funiculus descending serotonergic projection to spinal dorsal horn.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'somatosensory-cortex', field: 'levels.overview.text' },
      { kind: 'chemical', id: 'serotonin', field: 'breaks.text' },
    ],
  },

  'dopamine-pathways': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'dopamine-wanting-vs-liking',
        stepId: 'wanting-not-pleasure',
        field: 'text',
        claim: 'Midbrain dopamine supports motivation, incentive salience, and prediction learning, distinct from opioid-mediated sensory pleasure.',
        sourceIds: ['pmc10915723-dopamine-opioid'],
        basis: 'mixed',
        limits: 'PMC10915723: human pharmacological dissociation between dopamine and opioid reward mechanisms; Berridge wanting/liking framework.',
      },
      {
        id: 'dopamine-positive-rpe',
        stepId: 'unexpected-reward',
        field: 'text',
        claim: 'An unpredicted reward evokes a phasic burst above baseline in specific midbrain dopamine neurons, functioning as a positive reward prediction error.',
        sourceIds: ['pmc6721851-rpe'],
        basis: 'animal',
        limits: 'PMC6721851 introduction: Schultz classic electrophysiology in non-human primates and rodents. Illustrates one well-studied population, not every dopamine cell.',
      },
      {
        id: 'dopamine-cue-learning',
        stepId: 'cue-reward-association',
        field: 'text',
        claim: 'Phasic dopamine modulates synaptic plasticity in hippocampal, amygdalar, and striatal circuits to bind predictive cues to reward outcomes.',
        sourceIds: ['pmc6721851-rpe'],
        basis: 'animal',
        limits: 'PMC6721851: dopamine inputs and circuit mechanisms in learning.',
      },
      {
        id: 'dopamine-cue-transfer',
        stepId: 'cue-predicts-reward',
        field: 'text',
        claim: 'With repeated conditioning, phasic dopamine bursts transfer from the reward to the earliest reliable predictive cue.',
        sourceIds: ['pmc6721851-rpe'],
        basis: 'animal',
        limits: 'PMC6721851: classic Schultz prediction error signal transfer.',
      },
      {
        id: 'dopamine-expected-baseline',
        stepId: 'expected-reward',
        field: 'text',
        claim: 'When a reward arrives as expected, examined dopamine neurons show little extra phasic response because the prediction error is zero.',
        sourceIds: ['pmc6721851-rpe'],
        basis: 'animal',
        limits: 'PMC6721851: does not imply that dopamine ceases working or that subject ceases experiencing enjoyment.',
      },
      {
        id: 'dopamine-motor-vigor',
        stepId: 'action-and-drive',
        field: 'text',
        claim: 'Nigrostriatal and mesocorticolimbic dopamine modulates movement initiation, vigor, and goal-directed attention.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'established-anatomy',
        limits: 'Kandel ch. 38: modulation of direct/indirect striatal pathways.',
      },
      {
        id: 'dopamine-negative-rpe',
        stepId: 'disappointment-dip',
        field: 'text',
        claim: 'When an expected reward is omitted, lateral habenula activation drives a transient dip below baseline in dopamine firing, signaling negative prediction error.',
        sourceIds: ['pmc6721851-rpe'],
        basis: 'animal',
        limits: 'PMC6721851: pause in firing constitutes a computational error signal, not identical to the conscious subjective feeling of disappointment.',
      },
      {
        id: 'dopamine-habit-formation',
        stepId: 'automatic-habit',
        field: 'text',
        claim: 'Extensive repetition can shift behavioral control from ventral/prefrontal goal-directed networks toward dorsolateral striatal habit circuits.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 38: habit formation depends on context and training conditions rather than an inevitable timeline.',
      },
    ],
    routeNotes: [
      { stepId: 'unexpected-reward', from: 'vta', to: 'nucleus-accumbens', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Mesolimbic dopaminergic projection.' },
      { stepId: 'cue-reward-association', from: 'vta', to: 'hippocampus', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Mesohippocampal dopaminergic projection.' },
      { stepId: 'cue-reward-association', from: 'vta', to: 'amygdala', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Mesoamygdaloid dopaminergic projection.' },
      { stepId: 'cue-reward-association', from: 'vta', to: 'nucleus-accumbens', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Mesolimbic pathway.' },
      { stepId: 'cue-predicts-reward', from: 'vta', to: 'nucleus-accumbens', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Phasic release at predictive cue.' },
      { stepId: 'expected-reward', from: 'vta', to: 'nucleus-accumbens', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Baseline tonic firing during predicted reward.' },
      { stepId: 'action-and-drive', from: 'substantia-nigra', to: 'striatum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Nigrostriatal projection to dorsal striatum.' },
      { stepId: 'action-and-drive', from: 'striatum', to: 'globus-pallidus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Striatopallidal pathway.' },
      { stepId: 'action-and-drive', from: 'globus-pallidus', to: 'thalamus', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Pallidothalamic motor disinhibition.' },
      { stepId: 'action-and-drive', from: 'thalamus', to: 'motor-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Thalamocortical motor projection.' },
      { stepId: 'action-and-drive', from: 'vta', to: 'prefrontal-cortex', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Mesocortical projection sustaining working memory and focus.' },
      { stepId: 'disappointment-dip', from: 'globus-pallidus', to: 'habenula', semantics: 'direct', sourceIds: ['pmc6721851-rpe'], note: 'Basal ganglia internal segment output to lateral habenula.' },
      { stepId: 'disappointment-dip', from: 'habenula', to: 'vta', semantics: 'multi-hop', sourceIds: ['pmc6721851-rpe'], note: 'Lateral habenula excites rostromedial tegmental nucleus GABA neurons, which inhibit VTA dopamine.' },
      { stepId: 'automatic-habit', from: 'substantia-nigra', to: 'striatum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Nigrostriatal projection to dorsolateral striatum.' },
      { stepId: 'automatic-habit', from: 'prefrontal-cortex', to: 'striatum', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Corticostriatal transition from associative to sensorimotor striatum.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'chemical', id: 'dopamine', field: 'overview.text' },
      { kind: 'glossary', id: 'reward prediction error', field: 'reward prediction error' },
    ],
  },

  'serotonin-pathways': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'serotonin-raphe-origin',
        stepId: 'raphe-pulse',
        field: 'text',
        claim: 'Brainstem raphe nuclei synthesize serotonin from tryptophan and maintain tonic discharge during wakefulness.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 6: serotonergic projection system.',
      },
      {
        id: 'serotonin-amygdala-modulation',
        stepId: 'amygdala-tuning',
        field: 'text',
        claim: 'Serotonergic projections modulate amygdala threat reactivity and stress coping.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 48: 5-HT1A receptor modulation of emotional reactivity.',
      },
      {
        id: 'serotonin-prefrontal-impulse',
        stepId: 'frontal-patience',
        field: 'text',
        claim: 'Serotonin in prefrontal and anterior cingulate cortex is associated with behavioral flexibility and waiting tolerance.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 50: impulse control and delayed discounting.',
      },
      {
        id: 'serotonin-hypothalamus-homeostasis',
        stepId: 'sleep-appetite-regulation',
        field: 'text',
        claim: 'Hypothalamic serotonergic projections influence sleep-wake cycles, thermoregulation, and satiety.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 28: homeostatic hypothalamic circuits.',
      },
      {
        id: 'serotonin-spinal-pain',
        stepId: 'pain-modulation',
        field: 'text',
        claim: 'Descending serotonergic projections from caudal raphe nuclei to spinal dorsal horn modulate nociceptive input bidirectionally depending on receptor subtype and state.',
        sourceIds: ['pmc5883380-5ht-pain'],
        basis: 'mixed',
        limits: 'PMC5883380: effects depend on receptor subtypes (inhibition via 5-HT1, facilitation via 5-HT2/3).',
      },
    ],
    routeNotes: [
      { stepId: 'amygdala-tuning', from: 'raphe-nuclei', to: 'amygdala', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Ascending dorsal raphe serotonergic projection.' },
      { stepId: 'frontal-patience', from: 'raphe-nuclei', to: 'prefrontal-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Medial forebrain bundle projection to prefrontal cortex.' },
      { stepId: 'frontal-patience', from: 'raphe-nuclei', to: 'cingulate-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Projection to anterior cingulate cortex.' },
      { stepId: 'sleep-appetite-regulation', from: 'raphe-nuclei', to: 'hypothalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Projection to preoptic and hypothalamic nuclei.' },
      { stepId: 'pain-modulation', from: 'raphe-nuclei', to: 'spinal-cord', semantics: 'direct', sourceIds: ['pmc5883380-5ht-pain'], note: 'Descending dorsolateral funiculus projection to dorsal horn.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'chemical', id: 'serotonin', field: 'overview.text' },
    ],
  },

  'noradrenaline-pathways': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'noradrenaline-lc-discharge',
        stepId: 'locus-coeruleus-burst',
        field: 'text',
        claim: 'Locus coeruleus neurons fire phasic bursts to salient novel sensory stimuli.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 6: locus coeruleus noradrenergic distribution.',
      },
      {
        id: 'noradrenaline-sensory-tuning',
        stepId: 'sharper-senses',
        field: 'text',
        claim: 'Noradrenaline enhances signal-to-noise ratio in thalamic and primary sensory cortical areas.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 46: sensory gating and arousal.',
      },
      {
        id: 'noradrenaline-attentional-focus',
        stepId: 'focused-attention',
        field: 'text',
        claim: 'Noradrenaline in prefrontal and posterior parietal cortex focuses attention via high-affinity alpha-2A receptors, while excessive release under stress recruits lower-affinity receptors.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 46: Arnsten inverted-U model of alpha-2A versus alpha-1/beta receptor occupancy.',
      },
      {
        id: 'noradrenaline-motor-tone',
        stepId: 'motor-readiness',
        field: 'text',
        claim: 'Projections to cerebellum and spinal cord increase motor excitability and prepare somatic reflexes.',
        sourceIds: ['purves-neuroscience-6e'],
        basis: 'established-anatomy',
        limits: 'Purves ch. 16: descending reticulospinal and coeruleospinal facilitation.',
      },
    ],
    routeNotes: [
      { stepId: 'sharper-senses', from: 'locus-coeruleus', to: 'thalamus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Ascending noradrenergic projection to sensory thalamus.' },
      { stepId: 'focused-attention', from: 'locus-coeruleus', to: 'prefrontal-cortex', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Dorsal noradrenergic bundle to prefrontal cortex.' },
      { stepId: 'focused-attention', from: 'locus-coeruleus', to: 'posterior-parietal', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Projection to posterior parietal attention networks.' },
      { stepId: 'motor-readiness', from: 'locus-coeruleus', to: 'cerebellum', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Noradrenergic projection to cerebellar cortex and deep nuclei.' },
      { stepId: 'motor-readiness', from: 'locus-coeruleus', to: 'spinal-cord', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Coeruleospinal pathway to ventral horn motor circuits.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'chemical', id: 'noradrenaline', field: 'overview.text' },
    ],
  },

  'acetylcholine-pathways': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'acetylcholine-salience',
        stepId: 'salience-signal',
        field: 'text',
        claim: 'Basal forebrain cholinergic neurons become active when external stimuli require focused attention.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 46: cholinergic attentional modulation.',
      },
      {
        id: 'acetylcholine-sensory-enhancement',
        stepId: 'sensory-signal-boost',
        field: 'text',
        claim: 'Cholinergic release across frontal and parietal cortex enhances feedforward sensory processing relative to internal recurrent activity.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Hasselmo model of cholinergic regulation of cortical dynamics.',
      },
      {
        id: 'acetylcholine-hippocampal-encoding',
        stepId: 'hippocampal-encoding',
        field: 'text',
        claim: 'Cholinergic inputs coordinate hippocampal theta rhythms and facilitate synaptic plasticity, favoring new memory encoding over retrieval.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'animal',
        limits: 'Kandel ch. 55: cholinergic modulation of LTP in CA1 and CA3.',
      },
      {
        id: 'acetylcholine-semantic-linking',
        stepId: 'cortical-integration',
        field: 'text',
        claim: 'Cholinergic projections to temporal association cortex support integration of new associations with existing knowledge.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'mixed',
        limits: 'Kandel ch. 55: semantic memory organization.',
      },
    ],
    routeNotes: [
      { stepId: 'sensory-signal-boost', from: 'basal-forebrain', to: 'frontal-lobe', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Nucleus basalis of Meynert projection to frontal neocortex.' },
      { stepId: 'sensory-signal-boost', from: 'basal-forebrain', to: 'parietal-lobe', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Cholinergic projection to parietal neocortex.' },
      { stepId: 'hippocampal-encoding', from: 'basal-forebrain', to: 'hippocampus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Medial septal and vertical diagonal band projection to hippocampus.' },
      { stepId: 'cortical-integration', from: 'basal-forebrain', to: 'temporal-lobe', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Cholinergic projection to temporal neocortex.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'chemical', id: 'acetylcholine', field: 'overview.text' },
    ],
  },

  'default-mode-network': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'dmn-self-referential',
        stepId: 'inward-attention',
        field: 'text',
        claim: 'Medial prefrontal regions increase activity during unconstrained inward reflection and self-referential thought.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 61: default mode network discovery by Raichle et al. Resting state does not mean complete cessation of external monitoring.',
      },
      {
        id: 'dmn-prospection-memory',
        stepId: 'past-and-future',
        field: 'text',
        claim: 'Posterior cingulate cortex and hippocampus co-activate during autobiographical memory recall and future projection.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 61: episodic simulation and mental time travel.',
      },
      {
        id: 'dmn-theory-of-mind',
        stepId: 'social-cognition',
        field: 'text',
        claim: 'Temporal and temporoparietal junction areas participate in social cognition and mentalizing about others.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Kandel ch. 61: theory of mind networks overlapping DMN sub-nodes.',
      },
      {
        id: 'dmn-task-switching',
        stepId: 'task-re-engagement',
        field: 'text',
        claim: 'Salience network hubs including the anterior insula coordinate switching between default mode and task-positive executive networks in response to salient cues.',
        sourceIds: ['kandel-principles-6e'],
        basis: 'human',
        limits: 'Menon & Uddin tri-network model (salience, executive, DMN).',
      },
    ],
    routeNotes: [
      { stepId: 'past-and-future', from: 'prefrontal-cortex', to: 'cingulate-cortex', semantics: 'functional', sourceIds: ['kandel-principles-6e'], note: 'Functional correlation between medial PFC and posterior cingulate cortex.' },
      { stepId: 'past-and-future', from: 'cingulate-cortex', to: 'hippocampus', semantics: 'direct', sourceIds: ['purves-neuroscience-6e'], note: 'Parahippocampal and retro-splenial anatomical connections.' },
      { stepId: 'social-cognition', from: 'cingulate-cortex', to: 'temporal-lobe', semantics: 'functional', sourceIds: ['kandel-principles-6e'], note: 'DMN functional connectivity with lateral temporal cortex.' },
      { stepId: 'social-cognition', from: 'temporal-lobe', to: 'posterior-parietal', semantics: 'direct', sourceIds: ['kandel-principles-6e'], note: 'Temporoparietal junction connectivity.' },
      { stepId: 'task-re-engagement', from: 'insula', to: 'prefrontal-cortex', semantics: 'functional', sourceIds: ['kandel-principles-6e'], note: 'Salience network fronto-insular hub disengaging default mode network.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'structure', id: 'cingulate-cortex', field: 'levels.overview.text' },
    ],
  },

  'stress-and-fear': {
    status: 'draft',
    reviewedOn: null,
    fingerprint: null,
    claims: [
      {
        id: 'stress-hpa-axis-anticipation',
        stepId: 'anticipation-surge',
        field: 'text',
        claim: 'Anticipatory psychological stress engages the HPA axis, promoting glucocorticoid release alongside rapid sympathetic adrenaline release.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'human',
        limits: 'Frontiers 2015 section 3: acute anticipation activates sympathetic and HPA components on different timescales (seconds vs 15-30 minutes). Current text mixes these into a single instantaneous flood.',
      },
      {
        id: 'stress-amygdala-priming',
        stepId: 'glucocorticoids-prime-amygdala',
        field: 'text',
        claim: 'Glucocorticoids and noradrenaline enhance basolateral amygdala synaptic excitability and plasticity.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'animal',
        limits: 'Frontiers 2015 section 2.1: rodent electrophysiology shows glucocorticoid enhancement of BLA synaptic plasticity and LTP.',
      },
      {
        id: 'stress-fear-conditioning',
        stepId: 'accelerated-conditioning',
        field: 'text',
        claim: 'Sensitized amygdala circuits accelerate associative fear conditioning across sensory and contextual inputs.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'mixed',
        limits: 'Frontiers 2015 section 2.1: enhanced threat acquisition under elevated stress.',
      },
      {
        id: 'stress-prefrontal-disruption',
        stepId: 'prefrontal-disruption',
        field: 'text',
        claim: 'Stress hormones modulate medial prefrontal cortex function, with timing and chronicity determining whether safety learning is impaired.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'animal',
        limits: 'Frontiers 2015 section 3: acute stress shifts cognitive balance toward habitual control; prolonged chronic stress over weeks causes dendritic spine remodeling.',
      },
      {
        id: 'stress-safety-brake-mechanism',
        stepId: 'safety-brake-circuit',
        field: 'text',
        claim: 'Prefrontal circuits promote fear extinction by exciting inhibitory intercalated cells in the amygdala, muting central nucleus fear output.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'animal',
        limits: 'Frontiers 2015 section 2.2: rodent infralimbic circuitry. In humans, ventromedial prefrontal cortex homologues mediate extinction, but caution is needed when treating rodent anatomy as literal human circuitry.',
      },
      {
        id: 'stress-extinction-failure',
        stepId: 'extinction-impairment',
        field: 'text',
        claim: 'High or persistent stress can impair prefrontal engagement of extinction circuits, leaving conditioned threat alarms uninhibited.',
        sourceIds: ['frontiers2015-fear-extinction'],
        basis: 'mixed',
        limits: 'Frontiers 2015 section 2.2: prefrontal projections are excitatory glutamatergic inputs onto inhibitory intercalated cells; effects depend strongly on stress timing and learning phase.',
      },
    ],
    routeNotes: [
      { stepId: 'anticipation-surge', from: 'hypothalamus', to: 'pituitary', semantics: 'multi-hop', sourceIds: ['frontiers2015-fear-extinction'], note: 'Hypophyseal portal microcirculation transport of CRH from median eminence.' },
      { stepId: 'anticipation-surge', from: 'pituitary', to: 'adrenal', semantics: 'blood', sourceIds: ['frontiers2015-fear-extinction'], note: 'Systemic circulation of ACTH to adrenal cortex.' },
      { stepId: 'anticipation-surge', from: 'adrenal', to: 'heart', semantics: 'blood', sourceIds: ['frontiers2015-fear-extinction'], note: 'Circulating cortisol and systemic autonomic cardiovascular tone.' },
      { stepId: 'accelerated-conditioning', from: 'thalamus', to: 'amygdala', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Sensory thalamic input to basolateral amygdala.' },
      { stepId: 'accelerated-conditioning', from: 'hippocampus', to: 'amygdala', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Ventral hippocampal projection providing contextual representation.' },
      { stepId: 'safety-brake-circuit', from: 'prefrontal-cortex', to: 'amygdala', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Medial prefrontal glutamatergic projection exciting inhibitory intercalated paracapsular cells.' },
      { stepId: 'extinction-impairment', from: 'amygdala', to: 'hypothalamus', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Central amygdala output driving autonomic stress axis.' },
      { stepId: 'extinction-impairment', from: 'amygdala', to: 'midbrain', semantics: 'direct', sourceIds: ['frontiers2015-fear-extinction'], note: 'Central amygdala projection to periaqueductal gray.' },
    ],
    detailByStep: {},
    relatedTargets: [
      { kind: 'chemical', id: 'cortisol', field: 'overview.text' },
      { kind: 'cell', id: 'itc', field: 'fires.text' },
      { kind: 'diagram', id: 'fear-circuit', field: 'caption' },
      { kind: 'glossary', id: 'infralimbic cortex', field: 'infralimbic cortex' },
      { kind: 'glossary', id: 'intercalated cells', field: 'intercalated cells' },
    ],
  },
};
