// Guided pathways. Each step lights up `focus`, animates signals along `route`
// (pairs of structure or anchor ids), and can override the camera with `view`.
// Earlier steps' routes stay visible but faint, so the whole journey builds up.

export default [
  {
    id: 'seeing',
    category: 'function',
    name: 'Seeing: from eye to meaning',
    tagline: 'Light becomes edges, then objects and places.',
    summary: 'Seeing happens in stages. The eyes catch light, the {{thalamus}} relays it, and the {{visual-cortex}} analyzes edges, color and motion. From primary areas, visual processing engages interacting streams: where objects sit, and what they are.',
    steps: [
      { id: 'retina-photons', title: 'Light hits the retina', focus: ['eye'], route: [], view: 'left-front', text: 'Light lands on the retina at the back of each eye. There, roughly 100 million rods and cones begin turning it into electrical signals. At the optic chiasm, some fibres cross and some stay on the same side, so each hemisphere receives the opposite half of the visual world from both eyes.' },
      { id: 'thalamus-relay', title: 'A relay in the thalamus', focus: ['thalamus'], route: [['eye', 'thalamus']], text: 'Most retinal signals headed for vision relay in the {{thalamus}}, in a cluster called the lateral geniculate [[nucleus]]. It preserves the map of the visual field while attention and feedback from the cortex change the strength of the signal. Fibres then fan back to the {{visual-cortex}}.' },
      { id: 'visual-cortex-features', title: 'Edges and lines in the visual cortex', focus: ['visual-cortex'], route: [['thalamus', 'visual-cortex']], view: 'left-back', text: 'In the {{visual-cortex}}, cells fire for short edges, angles, colours and motion. Together they tile the whole view like puzzle pieces. This is seeing without yet knowing: lines and movement, but no names.' },
      { id: 'dorsal-where-stream', title: 'The "where" stream', focus: ['posterior-parietal'], route: [['visual-cortex', 'posterior-parietal']], view: 'left-back', text: 'Signals project upward along the dorsal stream toward the {{posterior-parietal}} cortex. This pathway maps where things sit and how to reach them, guiding your hand toward a mug without needing to consciously name the object.' },
      { id: 'ventral-what-stream', title: 'The "what" stream', focus: ['temporal-lobe'], route: [['visual-cortex', 'temporal-lobe']], text: 'Visual processing also flows toward the {{temporal-lobe}}, where patterns are matched with learned objects and faces. Damage in this network can spare basic sight while disrupting recognition. The "what" and "where" streams are useful labels, but they exchange information rather than working as separate pipes.' },
    ],
  },
  {
    id: 'smelling',
    category: 'function',
    name: 'Smelling: scent straight to emotion',
    tagline: 'A direct path from scent receptors to primary cortex.',
    summary: 'Unlike sight, sound, or touch, smell reaches primary cortex without an initial thalamic relay. Airborne molecules land in the {{nose}}, travel to the {{olfactory-bulb}}, and connect swiftly into emotional and memory networks.',
    steps: [
      { id: 'molecules-in-nose', title: 'Molecules land in the nose', focus: ['nose'], route: [], view: 'left-front', text: 'Airborne molecules drift into the nasal passage with every breath. They dissolve in the nasal mucus and bind to olfactory receptors on millions of sensory neurons lining the upper nasal cavity.' },
      { id: 'olfactory-bulb-sorting', title: 'Sorting in the olfactory bulb', focus: ['olfactory-bulb'], route: [['nose', 'olfactory-bulb']], view: 'left-below', text: 'Nerve fibres pass upward through microscopic pores in the skull base into the {{olfactory-bulb}}. Here, thousands of sensory inputs converge into spherical glomeruli, transforming a blend of chemical signals into an organized odor map.' },
      { id: 'limbic-memory-route', title: 'Connecting to emotional and memory networks', focus: ['amygdala', 'hippocampus'], route: [['olfactory-bulb', 'amygdala'], ['amygdala', 'hippocampus']], view: 'medial', slice: true, text: 'Without an initial stop at the {{thalamus}}, output fibres fan out to primary olfactory cortex and parts of the {{amygdala}}. From these entry points, signals reach the {{hippocampus}} through adjacent cortical gateways. This close connectivity helps explain why a fleeting scent can evoke vivid feelings and childhood memories before you have consciously named the smell.' },
      { id: 'flavor-and-recognition', title: 'Flavor and recognition', focus: ['insula', 'prefrontal-cortex', 'thalamus'], route: [['olfactory-bulb', 'insula'], ['olfactory-bulb', 'prefrontal-cortex']], view: 'left-front', slice: false, text: 'From primary olfactory areas, signals project to the {{insula}} to blend with taste into flavor. Downstream projections also engage the mediodorsal {{thalamus}} and orbitofrontal circuits in the {{prefrontal-cortex}}, allowing you to identify the scent, assess its value, and decide whether to eat or pull away.' },
    ],
  },
  {
    id: 'moving',
    category: 'function',
    name: 'Moving: deciding to reach',
    tagline: 'From an intention to a muscle twitch.',
    summary: 'A reach starts as a goal and ends as muscle. In between, cortical and basal-ganglia loops help select the action, the {{motor-cortex}} contributes descending commands, and the {{cerebellum}} helps predict and correct errors. No single region acts as the lone start switch.',
    steps: [
      { id: 'goal-formation', title: 'A goal forms', focus: ['prefrontal-cortex'], route: [], view: 'left-front', text: 'It starts in the {{prefrontal-cortex}} with a goal, like "grab that mug". The goal stays active while distractions pass. This holding is what lets a plan survive the seconds before moving.' },
      { id: 'action-selection', title: 'Choosing the action', focus: ['striatum', 'globus-pallidus'], route: [['prefrontal-cortex', 'striatum'], ['striatum', 'globus-pallidus']], text: 'The goal goes to the {{striatum}}, which helps weigh potential actions. Striatal projections connect with the {{globus-pallidus}}, whose inhibitory output tonically reins in unwanted movement. Selecting an action reduces this inhibition for the chosen movement.' },
      { id: 'basal-ganglia-gate', title: 'Adjusting the gate', focus: ['thalamus'], route: [['globus-pallidus', 'thalamus'], ['substantia-nigra', 'striatum']], text: 'Changes in {{globus-pallidus}} output alter the inhibition reaching the {{thalamus}}, which feeds activity back to motor areas. [[Dopamine]] from the {{substantia-nigra}} tunes how striatal pathways respond and learn. The familiar brake metaphor captures part of this loop, but real movement uses several interacting pathways.' },
      { id: 'cortex-commands', title: 'Commands leave the cortex', focus: ['motor-cortex'], route: [['thalamus', 'motor-cortex']], text: 'Populations in the {{motor-cortex}} contribute to the direction, force and timing of the reach. Large [[pyramidal cell|pyramidal cells]] send descending signals, which brainstem and spinal circuits combine with other inputs before muscles contract.' },
      { id: 'brainstem-descent', title: 'Down the brainstem', focus: ['midbrain', 'pons', 'medulla'], route: [['motor-cortex', 'midbrain'], ['midbrain', 'medulla']], view: 'left', text: 'Motor commands travel down through the {{midbrain}}, past the {{pons}} (which sends a copy to the {{cerebellum}}) and through the {{medulla}}. Most fibres cross sides in the medullary pyramids, so the left motor cortex guides the right hand.' },
      { id: 'spinal-muscle-output', title: 'Out to the muscles', focus: ['spinal-cord', 'hand'], route: [['medulla', 'spinal-cord'], ['spinal-cord', 'hand']], view: 'left', text: 'In the {{spinal-cord}}, descending signals synapse onto motor [[neuron|neurons]] that release acetylcholine to contract skeletal muscle fibres. Fingers close around the mug. Touch signals begin the return trip up to the {{somatosensory-cortex}} to confirm the grip.' },
      { id: 'cerebellar-correction', title: 'The cerebellum corrects', focus: ['cerebellum'], route: [['motor-cortex', 'pons'], ['pons', 'cerebellum'], ['cerebellum', 'thalamus'], ['thalamus', 'motor-cortex']], view: 'left-back', text: 'While the hand moves, a copy sent via the {{pons}} reaches the {{cerebellum}}. It compares plan with feedback from muscles and eyes, then sends corrections up through the {{thalamus}} to the {{motor-cortex}}. The reach lands smooth instead of jerky.' },
    ],
  },
  {
    id: 'remembering',
    category: 'function',
    name: 'Remembering: making a memory',
    tagline: 'How an experience becomes something you can recall.',
    summary: 'An experience activates patterns across the [[cortex]], while the {{hippocampus}} helps bind their relationships. Emotion can alter what is remembered, and later replay helps reorganise the memory across hippocampal and cortical networks.',
    steps: [
      { id: 'cortical-experience', title: 'An experience in the cortex', focus: ['temporal-lobe', 'parietal-lobe'], route: [], text: 'Meeting a friend in a cafe wakes the {{temporal-lobe}} (faces, words) and the {{parietal-lobe}} (where you sat, the reach for the cup). At first the pieces live apart. Nothing yet ties them into one recallable event.' },
      { id: 'hippocampal-binding', title: 'Bound together in the hippocampus', focus: ['hippocampus'], route: [['temporal-lobe', 'hippocampus'], ['parietal-lobe', 'hippocampus']], text: 'Both streams flow into the {{hippocampus}}. Its looped wiring binds who, what and where into one pattern, so later one cue can bring back the rest. This binding is why picturing the cafe can return the whole chat.' },
      { id: 'emotional-weight', title: 'Emotion adds weight', focus: ['amygdala'], route: [['amygdala', 'hippocampus']], text: 'If the meeting was emotionally charged, the {{amygdala}} boosts hippocampal consolidation through modulators like noradrenaline. This arousal can make central, salient features stick vividly, though peripheral details may be lost or distorted rather than saved like a photographic recording.' },
      { id: 'papez-loop', title: 'The extended memory network: the Papez loop', focus: ['mammillary-bodies', 'thalamus', 'cingulate-cortex'], route: [['hippocampus', 'mammillary-bodies'], ['mammillary-bodies', 'thalamus'], ['thalamus', 'cingulate-cortex'], ['cingulate-cortex', 'hippocampus']], view: 'medial', slice: true, text: 'Signals leave the {{hippocampus}} along the arching [[fornix]] to reach the {{mammillary-bodies}}. These nuclei relay into the anterior {{thalamus}} and onward to the {{cingulate-cortex}}, forming classical legs of the Papez circuit. Rather than acting as the sole storage depot, this subcortical-cortical loop forms part of an extended network vital for episodic memory. Damage here, as seen in Korsakoff syndrome, severely impairs forming new lasting memories.' },
      { id: 'systems-consolidation', title: 'Reorganised over time', focus: ['temporal-lobe', 'prefrontal-cortex'], route: [['hippocampus', 'temporal-lobe'], ['hippocampus', 'prefrontal-cortex']], text: 'During rest, sleep and recall, hippocampal and cortical activity can replay parts of an experience. Over time, many memories rely more on distributed cortical connections, although vivid episodic detail can continue to involve the {{hippocampus}}. Consolidation has no single fixed timetable.' },
    ],
  },
  {
    id: 'fear',
    category: 'function',
    name: 'Fear: the snake on the path',
    tagline: 'Why you jump before you know why.',
    summary: 'Threat responses emerge from interacting sensory, amygdala, hippocampal, frontal and body-control networks. Thalamic and cortical routes can both carry useful information, while context helps the brain revise an early guess.',
    steps: [
      { id: 'threat-movement', title: 'Something moves', focus: ['eye'], route: [], view: 'left-front', text: 'On a path, a curved shape moves near your foot. The eyes detect motion and coarse outlines before fine details resolve. Rapid sensory circuits treat the potential threat as urgent, initiating defensive preparations before conscious identification occurs.' },
      { id: 'early-warning', title: 'An early warning', focus: ['thalamus', 'amygdala'], route: [['eye', 'thalamus'], ['thalamus', 'amygdala']], text: 'Early sensory activity can influence the {{amygdala}} through thalamic and cortical routes before you have identified the object. Researchers still debate how much a direct thalamic route contributes to visual fear in humans.' },
      { id: 'body-reaction', title: 'The body reacts', focus: ['hypothalamus', 'midbrain'], route: [['amygdala', 'hypothalamus'], ['amygdala', 'midbrain']], text: 'Amygdala networks can recruit the {{hypothalamus}}, brainstem and midbrain systems that change heart rate, stress hormones, attention and movement. Several pathways work together when you freeze or step back.' },
      { id: 'cortical-detail', title: 'Detail changes the guess', focus: ['visual-cortex'], route: [['thalamus', 'visual-cortex'], ['visual-cortex', 'amygdala']], view: 'left-back', text: 'Visual processing resolves edges, colour and shape into bark with no snake head. That information reaches amygdala and memory networks through several cortical routes, updating the early guess without a fixed half-second delay.' },
      { id: 'safety-reappraisal', title: '"It\'s just a stick"', focus: ['prefrontal-cortex'], route: [['prefrontal-cortex', 'amygdala']], view: 'left-front', text: 'The {{prefrontal-cortex}} evaluates the new evidence and dampens amygdala output by activating inhibitory [[interneuron|interneurons]]. As defensive autonomic signals ease, heart rate falls. You laugh, step past the harmless stick, and the {{amygdala}} updates its assessment of the setting.' },
    ],
  },
  {
    id: 'hearing-speech',
    category: 'function',
    name: 'Hearing a sentence and replying',
    tagline: 'A voice reaches your ears. A reply leaves your mouth.',
    summary: 'Follow the main stops as you hear a question and answer it. The brain regions work together, even though we are visiting them one at a time. Sound moves from the ear through the brainstem and {{thalamus}} to the {{auditory-cortex}}. From there, temporal, parietal and frontal networks exchange information in parallel as meaning is grasped and speech is prepared, rather than passing a finished parcel down a single assembly line.',
    steps: [
      {
        id: 'inner-ear-sound',
        title: 'Sound reaches the inner ear',
        focus: ['ear'],
        route: [],
        text: 'A friend asks a question. Sound vibrates your eardrum, and tiny bones carry that vibration into the fluid-filled cochlea. Hair cells there turn the movement into nerve signals. Different parts of the cochlea respond best to different pitches, while the timing of nerve activity carries more detail about the sound.',
      },
      {
        id: 'brainstem-computation',
        title: 'Signals meet in the brainstem',
        focus: ['pons', 'midbrain'],
        route: [['ear', 'pons'], ['pons', 'midbrain']],
        text: 'The signals first reach the cochlear nuclei near the {{pons}}, then travel along several routes. One group of brainstem cells compares sound arriving at your two ears, helping you tell where the voice is coming from. Higher up, the inferior colliculus in the {{midbrain}} brings together information about the sound before it travels onward.',
      },
      {
        id: 'thalamus-sound-relay',
        title: 'Sound reaches the thalamus',
        focus: ['thalamus'],
        route: [['midbrain', 'thalamus']],
        text: 'The hearing-related part of the {{thalamus}} sharpens and routes sound signals on their way to the {{auditory-cortex}}. Rather than a simple one-way depot, this relay constantly receives feedback from the cortex itself, helping tune your attention to your friend\'s voice amidst surrounding cafe noise.',
      },
      {
        id: 'auditory-cortex-patterns',
        title: 'Patterns form in auditory cortex',
        focus: ['auditory-cortex'],
        route: [['thalamus', 'auditory-cortex']],
        text: 'The {{auditory-cortex}} tracks acoustic features such as pitch, rhythm and quick changes in sound. Processing does not wait for a neat border between sound and meaning. Speech-sensitive networks across the temporal lobe progressively match these patterns with familiar words while staying in dialogue with frontal areas.',
      },
      {
        id: 'wernicke-comprehension',
        title: 'Words connect with meaning',
        focus: ['wernickes-area'],
        route: [['auditory-cortex', 'wernickes-area']],
        text: 'Across temporal and parietal regions, the sounds you hear connect with words, ideas and the rest of the sentence. {{wernickes-area}} is a traditional name for part of this territory, but understanding language is the collective work of a wider network. These regions stay continuously engaged, linking what you hear to the speech you might prepare.',
      },
      {
        id: 'broca-speech-planning',
        title: 'A reply takes shape',
        focus: ['brocas-area'],
        route: [['wernickes-area', 'brocas-area', { flow: 'both' }]],
        text: 'Frontal language regions, including {{brocas-area}}, help shape a response and organize it for speech. They work in continuous two-way exchange with temporal and parietal regions as you choose words and prepare to say something like "Yes, with milk, please." This is an ongoing conversation between regions, not a message passed along a single wire.',
      },
      {
        id: 'motor-vocalisation',
        title: 'Spoken aloud and heard',
        focus: ['motor-cortex'],
        route: [['brocas-area', 'motor-cortex'], ['motor-cortex', 'auditory-cortex']],
        text: 'The mouth and face region of the {{motor-cortex}} helps send commands that move your jaw, lips and tongue while breathing muscles make sound. As you speak, signals also loop back to your own {{auditory-cortex}} to monitor and tune your pronunciation in real time, while the sound crossing the room begins the hearing pathway in your friend.',
      },
    ],
  },
  {
    id: 'pain',
    category: 'function',
    name: 'Pain: the alarm and the brake',
    tagline: 'From a sharp prick to how your brain tunes the hurt.',
    summary: 'Pain is more than a simple reflex wire from tissue to awareness. It is an integrated experience shaped across multiple networks: one encodes physical location and intensity, another processes emotional unpleasantness, and descending pathways can dial the volume up or down.',
    steps: [
      { id: 'fingertip-prick', title: 'A prick on the fingertip', focus: ['hand'], route: [], view: 'left', text: 'Touching a sharp pin or hot pan activates specialized nociceptors in the skin. Fast, lightly myelinated A-delta fibres convey an immediate sharp sensation, while slower unmyelinated C fibres convey a duller, lingering ache.' },
      { id: 'spinal-gate', title: 'The spinal gate', focus: ['spinal-cord'], route: [['hand', 'spinal-cord']], view: 'left', text: 'Nociceptive signals enter the dorsal horn of the {{spinal-cord}}. Here, local [[interneuron|interneurons]] regulate incoming traffic according to gate control mechanisms. Rubbing your finger activates larger touch fibres that stimulate inhibitory interneurons, helping quiet the pain signals before they ascend.' },
      { id: 'thalamic-pain-relay', title: 'Relayed through the thalamus', focus: ['thalamus'], route: [['spinal-cord', 'thalamus']], view: 'medial', slice: true, text: 'Ascending signals climb the spinothalamic tract into the {{thalamus}}. Rather than acting as a passive relay, thalamic nuclei shape the message and distribute it into parallel cortical networks that handle sensory detail and emotional relevance.' },
      { id: 'somatosensory-localisation', title: 'Locating and assessing the injury', focus: ['somatosensory-cortex'], route: [['thalamus', 'somatosensory-cortex']], view: 'left', slice: false, text: 'Signals reaching the {{somatosensory-cortex}} map the physical location, duration, and type of injury, telling you precisely where on your fingertip the sharp or burning contact occurred. This provides the sensory-discriminative map of the event.' },
      { id: 'affective-sting', title: 'The affective unpleasantness', focus: ['insula', 'cingulate-cortex'], route: [['thalamus', 'insula'], ['thalamus', 'cingulate-cortex']], view: 'left-front', text: 'Parallel projections engage the {{insula}} and {{cingulate-cortex}}. The insula reflects how bodily state is disrupted, while anterior cingulate networks generate the affective unpleasantness and motivational urge to pull away. These regions interact closely with sensory areas rather than acting as isolated suffering centers.' },
      { id: 'descending-modulation', title: 'Tuning the incoming signals', focus: ['midbrain', 'raphe-nuclei', 'spinal-cord'], route: [['midbrain', 'raphe-nuclei'], ['raphe-nuclei', 'spinal-cord']], view: 'left-back', text: 'The brain can actively modulate incoming pain signals. Descending circuits from the {{prefrontal-cortex}}, {{midbrain}} periaqueductal gray, and {{raphe-nuclei}} project back down to the {{spinal-cord}}. Through messengers including [[serotonin]] and endorphins, these pathways can dampen or facilitate nociceptive signals depending on physiological state and context.' },
    ],
  },
  {
    id: 'dopamine-pathways',
    category: 'chemistry',
    name: 'Dopamine: prediction, drive and habit',
    tagline: 'How reward prediction errors teach the brain what to want and repeat.',
    summary: 'Dopamine is often called a pleasure chemical, but immediate sensory enjoyment involves separate opioid and sensory networks. Dopamine functions as a critical engine for motivation, movement vigor, and learning. Midbrain cells in the {{vta}} and {{substantia-nigra}} release dopamine to tune expectations through [[reward prediction error|reward prediction errors]], support goal-directed action, and help establish routines.',
    steps: [
      {
        id: 'wanting-not-pleasure',
        title: 'Wanting, not pleasure',
        focus: ['vta', 'substantia-nigra'],
        route: [],
        view: 'left',
        text: 'Pop culture often calls dopamine the pleasure chemical, but research points to a different role. The immediate delight of tasting food or hearing music depends heavily on opioid networks and sensory pathways. In contrast, dopamine drives anticipation, motivation, and learning. From midbrain clusters in the {{vta}} and {{substantia-nigra}}, projections broadcast signals that teach circuits what cues are worth pursuing.',
      },
      {
        id: 'unexpected-reward',
        title: 'An unexpected reward',
        focus: ['vta', 'nucleus-accumbens'],
        route: [['vta', 'nucleus-accumbens']],
        view: 'left',
        text: 'Imagine walking down an unfamiliar street and finding a table of free fresh pastries. You had no expectation of food, yet you receive a treat. In this setup, the outcome exceeds expectations. In a well-studied reward-learning pattern, dopamine neurons in the {{vta}} respond with a burst above baseline, signaling a positive [[reward prediction error]]. Projections into the {{nucleus-accumbens}} highlight this event as worth remembering.',
      },
      {
        id: 'cue-reward-association',
        title: 'Connecting cue to reward',
        focus: ['hippocampus', 'amygdala', 'nucleus-accumbens'],
        route: [['vta', 'hippocampus'], ['vta', 'amygdala'], ['vta', 'nucleus-accumbens']],
        view: 'left',
        text: 'To get that treat again, your brain links the setting to the outcome. Dopamine release occurs while circuits in the {{hippocampus}} (mapping location) and {{amygdala}} (registering emotional weight) are active. This dopamine signal modulates synaptic plasticity, strengthening active connections so the street corner, bakery sign, and aroma become bound into a predictive memory.',
      },
      {
        id: 'cue-predicts-reward',
        title: 'Dopamine moves to the cue',
        focus: ['vta', 'nucleus-accumbens'],
        route: [['vta', 'nucleus-accumbens']],
        view: 'left',
        text: 'The next morning, you turn the same corner and catch the aroma. In landmark experiments by Wolfram Schultz and colleagues, recordings showed that with learning, phasic bursts in recorded dopamine cells transfer to the earliest reliable predictor. The cue acquires [[incentive salience]]: a motivational pull that draws your attention and urges you forward.',
      },
      {
        id: 'expected-reward',
        title: 'Expected reward: little extra burst',
        focus: ['nucleus-accumbens', 'vta'],
        route: [['vta', 'nucleus-accumbens']],
        view: 'left',
        text: 'You reach the table and take a bite. The pastry is just as sweet, but it is no longer a surprise. In this classic reward-learning paradigm, recorded dopamine neurons show little extra phasic burst because the outcome was already predicted. That does not mean dopamine stops operating altogether or that you stop enjoying the food; rather, the prediction error signal itself remains close to baseline.',
      },
      {
        id: 'action-and-drive',
        title: 'Fuelling action and focus',
        focus: ['substantia-nigra', 'striatum', 'globus-pallidus', 'thalamus', 'motor-cortex', 'prefrontal-cortex'],
        route: [
          ['substantia-nigra', 'striatum'],
          ['striatum', 'globus-pallidus'],
          ['globus-pallidus', 'thalamus'],
          ['thalamus', 'motor-cortex'],
          ['vta', 'prefrontal-cortex'],
        ],
        view: 'left',
        text: 'Wanting turns into action through motor loops. Projections from the {{substantia-nigra}} release dopamine into the {{striatum}}, modulating competing pathways that project through the {{globus-pallidus}} to the {{thalamus}}. This tuning promotes movement vigor and action selection toward the {{motor-cortex}}. Simultaneously, {{vta}} projections to the {{prefrontal-cortex}} help focus attention on the goal.',
      },
      {
        id: 'disappointment-dip',
        title: 'When an expected reward is missing',
        focus: ['habenula', 'vta', 'globus-pallidus'],
        route: [['globus-pallidus', 'habenula'], ['habenula', 'vta']],
        view: 'medial',
        slice: true,
        text: 'What if you smell the pastry, reach the corner, and the table is gone? An expected outcome failed to arrive, producing a negative [[reward prediction error]]. Signals via the basal ganglia and lateral {{habenula}} recruit brake interneurons that temporarily suppress {{vta}} dopamine firing below baseline. This pause in firing acts as a learning signal to adjust expectations, rather than being the feeling of disappointment itself.',
      },
      {
        id: 'automatic-habit',
        title: 'From wanting to automatic habit',
        focus: ['striatum', 'prefrontal-cortex', 'substantia-nigra'],
        route: [['substantia-nigra', 'striatum'], ['prefrontal-cortex', 'striatum']],
        view: 'left',
        text: 'If the reward appears reliably over many months, the way actions are selected can evolve. With extensive repetition, behavioral control often shifts from flexible {{prefrontal-cortex}} and {{nucleus-accumbens}} networks toward circuits in the dorsal {{striatum}}. This transition toward automatic routines frees up conscious attention, though habits can be broken when circumstances change.',
      },
    ],
  },
  {
    id: 'serotonin-pathways',
    category: 'chemistry',
    name: 'Serotonin: mood, resilience and sleep',
    tagline: 'A slow, steady signal from the brainstem that shapes mood and sleep.',
    summary: 'Serotonin is made by a thin strip of cells, the {{raphe-nuclei}}, running down the middle of the brainstem. Their fibres branch to almost every part of the brain and spinal cord. Its effects are broad and slow, and scientists still argue about exactly what it does for mood.',
    steps: [
      { id: 'raphe-pulse', title: 'A steady pulse in the brainstem', focus: ['raphe-nuclei'], route: [], view: 'medial', slice: true, text: 'The {{raphe-nuclei}} fire slowly and regularly while you are awake. They make [[serotonin]] from tryptophan, an amino acid you get from food.' },
      { id: 'amygdala-tuning', title: 'Tuning the amygdala', focus: ['amygdala'], route: [['raphe-nuclei', 'amygdala']], view: 'left', slice: true, text: 'Fibres reach the {{amygdala}}. Serotonin changes how easily it reacts, which is one reason serotonin is linked to anxiety and to how well people cope with stress.' },
      { id: 'frontal-patience', title: 'Patience in the frontal cortex', focus: ['prefrontal-cortex', 'cingulate-cortex'], route: [['raphe-nuclei', 'prefrontal-cortex'], ['raphe-nuclei', 'cingulate-cortex']], view: 'left-front', text: 'Other fibres reach the {{prefrontal-cortex}} and {{cingulate-cortex}}. Here serotonin is linked to patience and to switching away from a strategy that is not working. Low serotonin in animals makes them more impulsive.' },
      { id: 'sleep-appetite-regulation', title: 'Sleep and appetite', focus: ['hypothalamus'], route: [['raphe-nuclei', 'hypothalamus']], view: 'medial', slice: true, text: 'Serotonin also reaches the {{hypothalamus}}, which runs appetite, body temperature and the sleep-wake cycle. The raphe cells go almost silent during dreaming sleep.' },
      { id: 'pain-modulation', title: 'Modulating incoming pain', focus: ['spinal-cord'], route: [['raphe-nuclei', 'spinal-cord']], view: 'left', text: 'One major branch from caudal raphe nuclei runs down the {{spinal-cord}}. Rather than acting as a simple one-way volume brake, descending serotonergic projections can suppress or facilitate incoming pain signals depending on receptor subtypes, injury state, and behavioral context.' },
    ],
  },
  {
    id: 'noradrenaline-pathways',
    category: 'chemistry',
    name: 'Noradrenaline: the alert system',
    tagline: 'How a sudden surprise snaps you to attention.',
    summary: 'The two {{locus-coeruleus}} nuclei contain only tens of thousands of neurons, yet send [[noradrenaline]] to most of the brain. Their activity helps tune alertness, attention and responses to uncertainty.',
    steps: [
      { id: 'locus-coeruleus-burst', title: 'A burst from the blue spot', focus: ['locus-coeruleus'], route: [], view: 'left-back', text: 'A sudden bang breaks the quiet. The {{locus-coeruleus}} fires a burst within a fraction of a second and releases [[noradrenaline]] across the brain.' },
      { id: 'sharper-senses', title: 'Sharper senses', focus: ['thalamus'], route: [['locus-coeruleus', 'thalamus']], view: 'left', text: 'In the {{thalamus}} and primary sensory cortex, noradrenaline increases the signal-to-noise ratio: it enhances neural responses to salient inputs while suppressing spontaneous background firing, helping the sudden sound stand out.' },
      { id: 'focused-attention', title: 'Attention snaps into place', focus: ['prefrontal-cortex', 'posterior-parietal'], route: [['locus-coeruleus', 'prefrontal-cortex'], ['locus-coeruleus', 'posterior-parietal']], view: 'left-front', text: 'In the {{prefrontal-cortex}} and {{posterior-parietal}}, moderate noradrenaline engages high-affinity receptors that sharpen working memory and focus attention on the unexpected cue. Under high stress, excessive release engages lower-affinity receptors, which can disrupt flexible planning in favor of habitual reflexes.' },
      { id: 'motor-readiness', title: 'Ready to move', focus: ['cerebellum', 'spinal-cord'], route: [['locus-coeruleus', 'cerebellum'], ['locus-coeruleus', 'spinal-cord']], view: 'left-back', text: 'Descending projections to the {{cerebellum}} and {{spinal-cord}} raise motor excitability and prepare spinal reflexes, readying the musculoskeletal system for swift physical action.' },
    ],
  },
  {
    id: 'acetylcholine-pathways',
    category: 'chemistry',
    name: 'Acetylcholine: attention and memory',
    tagline: 'Helping you pay attention and remember what you learned.',
    summary: '[[acetylcholine]] carries the signal from motor neurons to skeletal muscles. Inside the brain, cells in the {{basal-forebrain}} send it across the cortex and to the {{hippocampus}} to tune attention and learning. Separate brainstem clusters also release it to regulate arousal and sleep. The forebrain supply degenerates early in Alzheimer\'s disease.',
    steps: [
      { id: 'salience-signal', title: 'Something worth learning', focus: ['basal-forebrain'], route: [], view: 'left-front', text: 'You sit down to learn something new, a tune or a puzzle. Cells in the {{basal-forebrain}} become more active when something needs attention.' },
      { id: 'sensory-signal-boost', title: 'Boosting what comes in', focus: ['frontal-lobe', 'parietal-lobe'], route: [['basal-forebrain', 'frontal-lobe'], ['basal-forebrain', 'parietal-lobe']], view: 'left', text: 'Their fibres release [[acetylcholine]] across the {{frontal-lobe}} and {{parietal-lobe}}. By acting on nicotinic and muscarinic receptors, acetylcholine enhances feedforward sensory signals while dampening recurrent internal cortical noise, giving incoming information greater weight.' },
      { id: 'hippocampal-encoding', title: 'Laying down new memories', focus: ['hippocampus'], route: [['basal-forebrain', 'hippocampus']], view: 'medial', slice: true, text: 'In the {{hippocampus}}, cholinergic inputs coordinate theta rhythms and facilitate synaptic plasticity, biasing local circuits toward encoding new experiences rather than retrieving older traces. Blocking cholinergic receptors impairs the formation of new memories.' },
      { id: 'cortical-integration', title: 'Linking to what you know', focus: ['temporal-lobe'], route: [['basal-forebrain', 'temporal-lobe']], view: 'left', text: 'Projections to association cortex in the {{temporal-lobe}} support the consolidation of declarative knowledge, helping new experiences link with existing semantic frameworks.' },
    ],
  },
  {
    id: 'default-mode-network',
    category: 'network',
    name: 'Default mode: the wandering mind',
    tagline: 'What your brain does when you are doing nothing in particular.',
    summary: 'Some brain areas get more active when you stop focusing on the outside world. Together they are called the default mode network. They are busy when you daydream, remember your past, picture the future or think about other people.',
    steps: [
      { id: 'inward-attention', title: 'Looking away from the world', focus: ['prefrontal-cortex'], route: [], view: 'left-front', text: 'You set your tasks aside and look out the window. As circuits focused on external goals ease their activity, medial regions of the {{prefrontal-cortex}} become more engaged. These areas are active during self-reflection, personal judgment, and unconstrained inward thought.' },
      { id: 'past-and-future', title: 'Past and future', focus: ['hippocampus', 'cingulate-cortex'], route: [['prefrontal-cortex', 'cingulate-cortex'], ['cingulate-cortex', 'hippocampus']], view: 'medial', slice: true, text: 'The posterior {{cingulate-cortex}} and medial temporal structures including the {{hippocampus}} join this network. Together they enable mental time travel: retrieving episodic memories from your past and simulating possible future scenarios.' },
      { id: 'social-cognition', title: 'Thinking about other people', focus: ['temporal-lobe', 'posterior-parietal'], route: [['cingulate-cortex', 'temporal-lobe'], ['temporal-lobe', 'posterior-parietal']], view: 'left', text: 'Nodes in the lateral {{temporal-lobe}} and the temporoparietal junction within the {{posterior-parietal}} cortex contribute to mentalizing: considering other people\'s beliefs, motivations, and feelings.' },
      { id: 'task-re-engagement', title: 'Back to the task', focus: ['insula'], route: [['insula', 'prefrontal-cortex']], view: 'left', text: 'Someone calls your name. The salience network, centered in the anterior {{insula}} and anterior cingulate, detects this meaningful cue and coordinates a state shift: default mode activity attenuates as task-positive executive networks re-engage.' },
    ],
  },
  {
    id: 'stress-and-fear',
    category: 'function',
    name: 'Stress and fear: how threat learning changes',
    tagline: 'How stress shifts the balance between threat detection and safety recall.',
    summary: 'Anticipating a challenge activates both fast autonomic signals and slower hormone cascades. These changes prime amygdala circuits for rapid threat learning, while altering the prefrontal networks needed to recognize and recall safety.',
    steps: [
      {
        id: 'anticipation-surge',
        title: 'Anticipation primes body and brain',
        focus: ['hypothalamus', 'pituitary', 'adrenal', 'heart'],
        route: [['hypothalamus', 'pituitary'], ['pituitary', 'adrenal'], ['adrenal', 'heart']],
        view: 'body',
        body: true,
        text: 'Just expecting a challenge starts preparing the body. The sympathetic nervous system triggers a quick release of [[adrenaline]], raising heart rate and blood pressure within seconds. In parallel, the {{hypothalamus}} signals the {{pituitary}} and adrenal glands along the [[HPA axis]], starting a slower rise in [[glucocorticoid|glucocorticoids]] like [[cortisol]] that takes minutes to build up in the bloodstream and cross into the brain.',
      },
      {
        id: 'glucocorticoids-prime-amygdala',
        title: 'Glucocorticoids prime the amygdala',
        focus: ['amygdala'],
        route: [],
        view: 'left',
        slice: true,
        text: 'As cortisol and adrenaline-driven signals reach the brain, they bind receptors in the [[basolateral amygdala]]. In animal studies, these messengers raise excitability and promote synaptic changes through [[long-term potentiation]]. The brain turns up sensitivity to potential danger, making threat detection faster when vigilance is needed.',
      },
      {
        id: 'accelerated-conditioning',
        title: 'Threat associations form more readily',
        focus: ['thalamus', 'amygdala', 'hippocampus'],
        route: [['thalamus', 'amygdala'], ['hippocampus', 'amygdala']],
        view: 'left',
        slice: false,
        text: 'With the {{amygdala}} sensitized, associations between an unexpected cue and a threatening event can form with fewer repetitions. Sensory inputs relayed from the {{thalamus}} and spatial context provided by the {{hippocampus}} link with emotional arousal. This prioritized learning helps animals and humans avoid hazards in dangerous environments.',
      },
      {
        id: 'prefrontal-disruption',
        title: 'Prefrontal regulation shifts',
        focus: ['prefrontal-cortex'],
        route: [],
        view: 'left-front',
        text: 'Strong stress alters processing in the medial [[prefrontal cortex]], a network important for flexible regulation and evaluating context. Rather than literally turning off, high stress shifts the balance of control toward habitual and defensive reflexes. While prolonged chronic stress over weeks can cause dendritic spines to remodel, acute stress primarily alters immediate synaptic signaling and attention.',
      },
      {
        id: 'safety-brake-circuit',
        title: 'Learning that a cue is now safe',
        focus: ['prefrontal-cortex', 'amygdala'],
        route: [['prefrontal-cortex', 'amygdala']],
        view: 'left-front',
        text: 'When a formerly threatening cue occurs repeatedly without harm, the brain can learn safety through [[extinction]]. In rodent models, the [[infralimbic cortex]] (corresponding functionally to ventral medial prefrontal areas in humans) sends excitatory glutamate signals to inhibitory [[intercalated cells]] in the {{amygdala}}. These gatekeeper cells release [[GABA]] onto central amygdala output neurons, reducing defensive responses without erasing the original memory.',
      },
      {
        id: 'extinction-impairment',
        title: 'Stress can make safety harder to recall',
        focus: ['prefrontal-cortex', 'amygdala', 'hypothalamus', 'midbrain'],
        route: [['amygdala', 'hypothalamus'], ['amygdala', 'midbrain']],
        view: 'left',
        text: 'When stress hormones remain elevated or occur during recovery, they can interfere with this safety learning. Prefrontal circuits struggle to effectively recruit the intercalated cell brake, allowing amygdala projections to the {{hypothalamus}} and {{midbrain}} to keep triggering defensive arousal. The outcome depends heavily on timing: stress before or after learning produces distinct effects, rather than a universal failure.',
      },
    ],
  },
];
