// Glossary of Neuroanatomical, Cellular, and Neurochemical Terms.
// Write [[term]] or [[term|shown text]] in any text field and the explainer
// underlines it with a hover definition. Matching ignores case and trailing "s"/"es".
export default {
  // =========================================================================
  // 1. BRAIN STRUCTURES (ATLAS REGIONS & ALIASES)
  // =========================================================================

  'frontal lobe': 'Named from Latin frons (genitive frontis, meaning forehead or brow). Historical anatomists designated it for its position directly beneath the frontal bone of the skull, formalised by Louis Pierre Gratiolet in 1854. In the living brain, it serves as the master executive center, directing voluntary movement, speech, long-term planning, and social decisions.',
  'prefrontal cortex': 'From Latin prae (in front of), frons (forehead), and cortex (bark). It occupies the anterior tip of the frontal lobe, resting directly behind your forehead and eyebrows. It functions as the brain\'s executive director and mental sketchpad, weighing consequences, keeping goals in working memory, and curbing impulsive reactions.',
  'primary motor cortex': 'From Latin motor (mover, from movere "to move") and cortex (bark). It forms the precentral gyrus directly in front of the central sulcus, mapped by Wilder Penfield in conscious patients into an upside-down "homunculus" with oversized hands and lips. It sends direct electrical commands down the spinal cord to trigger voluntary muscle contractions.',
  'motor cortex': 'From Latin motor (mover) and cortex (bark). Located along the precentral gyrus, this cortical strip was mapped by Wilder Penfield to reveal an upside-down muscular map of the human body. It dispatches electrical movement signals down the spinal cord to command voluntary physical actions.',
  "Broca's area": 'Named for French physician Paul Broca, who in 1861 examined a patient nicknamed "Tan," who understood language but could say only that single syllable. Broca traced the damage to this patch of the left inferior frontal gyrus, which choreographs the motor movements of the tongue, lips, and vocal cords to produce fluent spoken words.',
  'brocas area': 'Named for French physician Paul Broca, who in 1861 traced expressive language loss to this left frontal patch after studying his famous patient "Tan." It coordinates the vocal cords, tongue, and lips to convert thoughts into spoken and written words.',
  'parietal lobe': 'From Latin parietalis (belonging to a wall, from paries "wall"). Named because it rests directly under the parietal bones of the skull, which form the protective side walls and ceiling of the cranium. It acts as the brain\'s sensory integration engine, combining touch, pressure, and visual cues into an accurate 3D map of your body and surroundings.',
  'primary somatosensory cortex': 'From Greek soma (body), Latin sensus (feeling), and cortex (bark). Located on the postcentral gyrus just behind the central sulcus, it was mapped by Wilder Penfield as a sensory homunculus where sensitive zones like fingertips and lips receive huge cortical territory. It receives sensory signals from the skin and joints, decoding touch, temperature, vibration, and pain.',
  'somatosensory cortex': 'From Greek soma (body) and Latin sensus (feeling). Forming a vertical band directly behind the central sulcus, this cortical strip receives touch and body signals from across the body, letting you feel texture, temperature, pressure, and limb position.',
  'posterior parietal cortex': 'From Latin posterior (coming after, rear) and paries (wall). It occupies the rear portion of the parietal lobe, positioned where touch, vision, and hearing pathways meet. It blends these senses into a unified spatial coordinate frame, guiding your hands and limbs to reach, grasp, and navigate without bumping into objects.',
  'posterior parietal': 'From Latin posterior (behind) and paries (wall). Situated at the back of the parietal lobe, this region integrates sight and touch to calculate spatial coordinates, guiding accurate reaching, pointing, and navigation.',
  'temporal lobe': 'From Latin tempora (the temples of the head), from tempus (time), so called because gray hair first appears at the temples as years pass. Tucked beneath the lateral fissure behind your ears, it houses circuits for hearing, recognizing faces and objects, understanding spoken words, and anchoring long-term memories via the hippocampus.',
  'primary auditory cortex': 'From Latin audire (to hear) and cortex (bark). Buried inside the lateral fissure along Heschl\'s gyri (described by Austrian anatomist Richard Heschl in 1878), it receives sound signals from the cochlea via the thalamus. It is mapped tonotopically like a piano keyboard, with neighboring neuron bands tuned to specific sound pitches.',
  'auditory cortex': 'From Latin audire (to hear). Tucked within the temporal lobe along Heschl\'s gyri, this cortical region is organized like a musical keyboard from low to high pitches, translating sound vibrations into conscious hearing.',
  "Wernicke's area": 'Named for German physician Carl Wernicke, who in 1874 discovered that damage to the posterior left superior temporal gyrus left patients speaking fluently but with meaningless "word salad," unable to understand speech. It translates sound patterns into meaningful linguistic concepts so you can comprehend spoken and written language.',
  'wernickes area': 'Named for German neurologist Carl Wernicke, who discovered in 1874 that damage to this rear left temporal area destroys language comprehension while leaving speech rhythm intact. It decodes speech and text sounds into meaningful concepts.',
  'occipital lobe': 'From Latin occiput (the back of the head, from ob "behind" and caput "head"). Positioned at the very rear of the cerebral cortex, cupped in the occipital bone above the cerebellum. It is dedicated entirely to vision, breaking incoming light patterns from the eyes into edges, orientation, motion, depth, and color.',
  'primary visual cortex': 'From Latin visualis (pertaining to sight, from videre "to see") and cortex (bark). Lining the calcarine sulcus on the medial occipital surface, it was termed the "striate cortex" in 1776 by Francesco Gennari, who spotted a distinctive white band of myelinated fibers with the naked eye. It maps the visual field point for point, detecting raw contrast, orientation, and motion.',
  'visual cortex': 'From Latin videre (to see). Occupying the rear occipital lobe along the calcarine fissure, this region processes raw visual signals from the retina, detecting lines, movement, and contrast before sending them to higher recognition centers.',
  'cingulate cortex': 'From Latin cingulum (a belt, sash, or girdle). Historical anatomists named it for the way this sweeping band of cortex wraps directly over the upper curve of the corpus callosum like an arched headband. It connects cognitive thoughts with emotional feelings, monitoring errors, registering physical and social pain, and resolving motivational conflicts.',
  'cingulate gyrus': 'From Latin cingulum (belt or sash) and Greek gyros (ring or circle). Arching over the corpus callosum along the brain\'s inner midline, this limbic fold helps manage emotional responses, error detection, and motivation.',
  'insula': 'Latin for "island." German anatomist Johann Christian Reil named it the "Island of Reil" in 1809 because it lies hidden deep within the lateral fissure like a sunken island, concealed under the overlapping folds of the frontal, parietal, and temporal lobes. It maps your internal bodily states, turning heart rate, gut feelings, pain, and taste into conscious feelings and empathy.',
  'insular cortex': 'Latin insula (island). Buried deep inside the lateral fissure beneath the surrounding cortical lobes, this hidden island of cortex monitors heartbeat, gut sensations, and taste to generate subjective emotional feelings.',
  'thalamus': 'From Greek thalamos (inner room or bridal bedchamber), applied by Galen in the second century to chambers near the brain\'s base. On dissection, the thalami appear as two symmetrical, egg-shaped masses of grey matter sitting side by side at the heart of the brain. It acts as the grand central switchboard, sorting and relaying all sensory signals (except smell) to the cerebral cortex.',
  'hypothalamus': 'From Greek hypo (under, beneath) and thalamos (inner chamber), coined in 1893 by Swiss anatomist Wilhelm His. It forms an almond-sized cluster of nuclei tucked directly beneath the thalamus on the floor of the third ventricle. It is the body\'s master homeostatic control center, regulating body temperature, hunger, thirst, sleep cycles, stress responses, and hormone release via the pituitary.',
  'striatum': 'From Latin striatus (striped or furrowed). English physician Thomas Willis named it the "corpus striatum" in 1664 because pale myelinated fiber tracts slice through its grey nuclei, producing a striped or marbled pattern on cross-section. Combining the caudate and putamen, it acts as the primary input engine of the basal ganglia, selecting physical movements and reinforcing rewarding habits.',
  'corpus striatum': 'Latin for "striped body," named by Thomas Willis in 1664 for the striped appearance caused by pale white-matter bundles cutting through grey nuclei. It coordinates motor planning, action selection, and reward-based habit formation.',
  'globus pallidus': 'Latin for "pale globe." Named by German anatomist Karl Friedrich Burdach in 1819 for its pale, bleached appearance on unstained brain slices, caused by a dense crisscrossing web of myelinated nerve fibers. It acts as the primary inhibitory braking system of the basal ganglia, continuously damping down unwanted movements so only intended actions can proceed.',
  'substantia nigra': 'Latin for "black substance." Sliced open on the dissection table, this midbrain structure forms a striking dark crescent because its dopamine-producing neurons are rich in dark neuromelanin pigment. Described by Félix Vicq d\'Azyr in 1786 and named by Samuel Thomas von Soemmerring in 1791, it supplies dopamine to the striatum to unlock movement; its decay causes Parkinson\'s disease.',
  'hippocampus': 'From Greek hippokampos (seahorse, from hippos "horse" and kampos "sea monster"). Named in 1587 by Venetian anatomist Giulio Cesare Aranzio, who dissected the temporal lobe floor and observed a ridged structure curling upward like the tail of a dried seahorse. It acts as the brain\'s memory index, stitching experiences into lasting episodic memories and building an internal GPS map of space.',
  'amygdala': 'From Greek amygdale (almond). Identified and named by German anatomist Karl Friedrich Burdach in 1822 because this small nucleus, nestled in the temporal lobe just ahead of the hippocampus, closely matches an almond in size and shape. It acts as the brain\'s threat alarm and emotional significance detector, rapidly flagging danger, processing fear, and igniting the fight-or-flight response.',
  'corpus callosum': 'Latin for "tough body" (from corpus "body" and callum "hardened skin"). Roman physician Galen named it because this arched bridge of over 200 million insulated nerve fibers felt distinctly firmer and tougher than the soft cerebral cortex above it. It serves as the primary data superhighway linking your left and right hemispheres so they can instantly share information.',
  'ventral tegmental area': 'From Latin ventralis (on the belly side, from venter "belly") and tegmentum (a covering or roof, from tegere "to cover"). It sits on the front floor of the midbrain tegmentum, nestled just beside the substantia nigra. It is a major dopamine nursery whose projections to the nucleus accumbens and prefrontal cortex drive motivation, desire, and the anticipation of rewards.',
  'VTA': 'Abbreviation for ventral tegmental area. A midbrain cluster of dopamine-producing neurons that broadcast reward prediction signals to the frontal cortex and nucleus accumbens, fueling motivation, curiosity, and goal pursuit.',
  'basal forebrain': 'From Greek basis (pedestal or base) and Old English fore (front) plus brain. Refers to structures (including the nucleus basalis of Meynert and septal nuclei) clustered at the front base of the brain beneath the striatum. It serves as the brain\'s master acetylcholine projector, spraying the cortex to sharpen attention, promote wakeful focus, and facilitate learning.',
  'nucleus accumbens': 'From Latin nucleus (kernel or little nut) and accumbens (leaning against, from accumbere). Named because this basal forebrain nucleus rests where the head of the caudate meets the putamen, leaning directly against the septum pellucidum. It serves as the crossroads of motivation and pleasure, turning dopamine-driven anticipation into physical action.',
  'pituitary gland': 'From Latin pituitarius (producing phlegm or mucus, from pituita). Ancient physician Galen mistakenly believed this pea-sized gland at the base of the brain drained waste phlegm into the nose. Also called the hypophysis (Greek for "undergrowth"), it is the master endocrine gland, releasing hormones into the bloodstream to regulate growth, metabolism, stress, and reproduction.',
  'pituitary': 'From Latin pituita (mucus, reflecting Galen\'s ancient theory). Suspended from the hypothalamus by a thin stalk, this master gland secretes essential regulatory hormones into the bloodstream to govern growth, thyroid activity, stress, and reproductive cycles.',
  'pineal gland': 'From Latin pinea (pinecone, from pinus "pine tree"). Galen noted in the second century that this tiny, unpaired gland nestled between the two thalami closely resembles a miniature pinecone. René Descartes considered it the seat of the soul; today we know it senses darkness to release melatonin into the blood, regulating circadian rhythms and promoting sleep.',
  'pineal': 'From Latin pinea (pinecone). A tiny, pinecone-shaped endocrine gland nestled deep between the thalami that synthesizes and releases melatonin in response to darkness, synchronizing your daily sleep-wake cycle.',
  'cerebellum': 'Latin for "little brain," the diminutive form of cerebrum. Tucked beneath the rear overhang of the cerebral hemispheres, it resembles a compact, miniature brain with its own densely folded surface sheets (folia). Containing over half of all neurons in the brain, it calibrates timing and balance, smoothing out voluntary muscle movements so actions feel effortless and fluid.',
  'midbrain': 'From Old English mid (middle) and brain, translating Greek mesencephalon (mesos "middle" and enkephalos "brain"). It forms the topmost stalk of the brainstem, bridging the forebrain above and the pons below. It contains relay hubs for vision and hearing (the colliculi), dopamine centers (substantia nigra and VTA), and circuits that muffle pain and orient your gaze.',
  'mesencephalon': 'From Greek mesos (middle) and enkephalos (brain). The topmost segment of the brainstem, housing crucial dopamine nuclei, eye-movement controls, and auditory and visual reflex centers.',
  'pons': 'Latin for "bridge." Italian anatomist Costanzo Varolio named it pons Varolii in 1573 because its bulging belly of transverse white-matter fibers forms an arching bridge across the brainstem between the two halves of the cerebellum. It channels movement signals into the cerebellum and houses cranial nerve nuclei controlling facial feeling, chewing, swallowing, and breathing rhythm.',
  'medulla oblongata': 'From Latin medulla (marrow, pith, or innermost core) and oblongata (lengthened or oblong). Named by early anatomists for the elongated, marrow-like stalk forming the lowest section of the brainstem, tapering downward to merge with the spinal cord. It houses autonomic reflex centers that control essential life-support functions, including heartbeat, blood pressure, breathing, and swallowing.',
  'medulla': 'From Latin medulla (marrow or innermost core). The lowest segment of the brainstem, connecting directly to the spinal cord. It acts as the body\'s autopilot, governing breathing, heart rate, blood pressure, and swallowing reflexes.',
  'spinal cord': 'From Latin spina (thorn, prickle, or backbone) and cord (from Greek chorde, gut string). A glistening white neural cable running from the base of the skull down through the protective canal of the vertebral column. It serves as the primary two-way data highway of the central nervous system, carrying touch and pain messages upward to the brain and motor commands down to muscles.',
  'raphe nuclei': 'From Greek rhaphe (a seam or line of stitches). Named in 1890 because these cell clusters form a narrow vertical ridge running down the midline seam where the two halves of the brainstem fuse together. They are the brain\'s primary serotonin factories, sending modulatory fibers across the brain and spinal cord to stabilize mood, sleep cycles, pain sensitivity, and emotional resilience.',
  'raphe': 'From Greek rhaphe (seam or stitch). A vertical column of serotonin-producing neurons running along the midline of the brainstem, projecting widely to modulate mood, pain, and sleep cycles.',
  'locus coeruleus': 'Latin for "sky-blue spot" (from locus "place" and caeruleus "dark blue"). Described by Félix Vicq d\'Azyr in 1786 and named by the Wenzel brothers in 1812 for the subtle bluish-grey tint seen in unstained tissue on the floor of the fourth ventricle in the upper pons, caused by neuromelanin. It serves as the brain\'s alarm button, spraying noradrenaline across the cortex to trigger alert focus.',
  'locus ceruleus': 'Variant spelling of locus coeruleus, Latin for "sky-blue spot." A tiny brainstem nucleus that synthesizes noradrenaline, firing rapidly during unexpected events to snap the brain into a state of high vigilance.',

  // =========================================================================
  // 2. GENERAL NEUROSCIENCE & ANATOMICAL TERMS
  // =========================================================================

  neuron: 'From Greek neuron (originally meaning sinew, cord, or tendon, used loosely in antiquity for any white bodily fiber). In 1891, Heinrich Wilhelm Waldeyer introduced it for the discrete cellular building blocks discovered by Santiago Ramón y Cajal. An excitable cell that collects inputs on its dendrites, integrates them in its soma, and fires electrical action potentials down its axon.',
  axon: 'From Greek axon (axle of a chariot, axis, or central pivot). Coined in 1896 by Swiss anatomist Rudolph Albert von Kölliker to describe the single, long, cylindrical cable that extends from the nerve cell body like a drive shaft. It serves as the output wire of a neuron, carrying electrical action potentials away from the soma toward target cells, often wrapped in insulating myelin.',
  dendrite: 'From Greek dendron (tree) and the suffix -ite (resembling). Coined in 1889 by Swiss anatomist Wilhelm His because under the microscope, these branching extensions unfurling from the neuronal cell body resemble the bare limbs of a winter tree. They act as the receiving antennae of the neuron, covered in thousands of tiny spines that capture incoming neurotransmitter signals.',
  synapse: 'From Greek synapsis (a contact, junction, or clasp), from syn- (together) and haptein (to clasp, fasten, or join). Coined in 1897 by English physiologist Sir Charles Sherrington on the advice of classicist A.W. Verrall. It is the microscopic junction (about 20 nanometers wide) where an axon terminal releases chemical neurotransmitter molecules that float across to bind receptors on a target cell.',
  neurotransmitter: 'From Greek neuron (nerve) and Latin transmittere (to send across, from trans- "across" and mittere "to send"). Coined in the mid-20th century following Otto Loewi\'s 1921 discovery of chemical signaling in frog hearts. A chemical messenger stored in synaptic vesicles and released into the synaptic cleft to excite, inhibit, or modulate the electrical behavior of a receiving cell.',
  receptor: 'From Latin receptor (a receiver or welcomer, from recipere "to receive"). Proposed by British pharmacologist John Newport Langley in 1905 and Paul Ehrlich as specialized molecular locks. A protein embedded in a cell membrane that fits a specific chemical messenger like a key, changing shape upon binding to open an ion channel or launch an internal biochemical cascade.',
  'action potential': 'From Latin actio (a doing or setting in motion) and potentialis (having power, from potens "able"). Conceptualized by Julius Bernstein in 1902 and recorded directly by Alan Hodgkin and Andrew Huxley in 1939 from the giant squid axon. A brief, all-or-nothing electrical pulse lasting about one millisecond that races down an axon to deliver signals across long distances without fading.',
  excitatory: 'From Latin excitare (to rouse, stir up, awaken, or call forth, from ex- "out" and citare "to set in motion"). Used in early physiological studies of reflex arcs to describe inputs that spark activity. A synaptic signal (typically delivered by glutamate) that depolarizes the receiving cell membrane, nudging its electrical voltage closer to the firing threshold needed to trigger an action potential.',
  inhibitory: 'From Latin inhibere (to hold back, check, curb, or restrain, from in- "in" and habere "to hold"). Demonstrated by the Weber brothers in 1845 when vagal stimulation slowed the heart, proving active braking is essential to life. A synaptic signal (typically delivered by GABA or glycine) that hyperpolarizes the receiving cell membrane, keeping it safely below firing threshold.',
  cortex: 'Latin for "the bark of a tree, outer rind of fruit, or cork." Early anatomists noted that the folded outer sheet of grey matter wraps around the inner core of white matter much like rough protective bark covers the wood of a tree trunk. The 2 to 4 millimeter thick outer mantle of the brain containing billions of neurons responsible for perception, thought, language, and voluntary action.',
  'grey matter': 'From Old English græg (grey) and Latin materia (substance or material). Named for its muted pinkish-grey appearance in fresh, unfixed brain tissue, in contrast to the glistening white tracts beneath it. The computational tissue of the central nervous system, densely packed with neuronal cell bodies, branching dendrites, synapses, and capillaries where information is processed.',
  'white matter': 'From Old English hwit (white) and Latin materia (material). Named for its brilliant, pearly white sheen in freshly sliced brain tissue, produced by the thick lipid layers of myelin that wrap and insulate millions of nerve fibers. The communication wiring of the brain, composed of vast bundles of myelinated axons linking distant grey-matter processing centers together.',
  hemisphere: 'From Greek hemisphairion (half of a sphere, from hemi- "half" and sphaira "globe or ball"). A classical geometry term used by early anatomists to describe the two large, symmetrical, dome-like halves of the cerebrum and cerebellum. The left and right halves of the cerebral cortex, separated by the longitudinal fissure, sharing duties while dividing labor between language, spatial focus, and movement.',
  lobe: 'From Greek lobos (a rounded flap, projection, or fold, such as an earlobe or liver lobe). Formalized in 1854 by French anatomist Louis Pierre Gratiolet to divide each cerebral hemisphere into broad sectors matching the skull bones over them. A major anatomical region of the cortex (frontal, parietal, temporal, or occipital), grouping functional areas dedicated to related neural tasks.',
  gyrus: 'From Greek gyros (a circle, ring, or curved loop), through Latin gyrus. Early anatomists compared the undulating folds on the cerebral surface to coils of rope or a maze of winding garden paths; each outward crest or ridge is a gyrus. Crumpling the brain into gyri allows a huge surface area of computational tissue to fit inside a compact skull.',
  sulcus: 'Latin for "a furrow or trench made by a plow in a farm field." Roman agricultural metaphor applied by anatomists to describe the narrow grooves and deep valleys dipping between the swollen ridges of the cerebral cortex. A cleft or fold on the brain surface that dips down between gyri, concealing approximately two-thirds of the human cerebral cortex within its depths.',
  nucleus: 'From Latin nucleus (a little nut, kernel, or core), the diminutive of nux (nut). Adopted by neuroanatomists to describe a distinct, compact clump of grey matter nestled within white matter like a hard nut inside its shell. In the central nervous system, a localized cluster of neuron cell bodies sharing common connections and functional tasks (distinct from the genetic nucleus inside a cell).',
  'basal ganglia': 'From Greek basis (base or foundation) and ganglion (a knot, swelling, or subcutaneous lump). Coined in the 19th century to describe the prominent cluster of large grey-matter "knots" situated deep in the base of the forebrain. A feedback circuit loop that filters and selects which motor commands and cognitive thoughts get executed, while suppressing competing impulses.',
  interneuron: 'From Latin inter (between or among) and Greek neuron (nerve). Conceptualized by Santiago Ramón y Cajal to describe short-axon neurons that stay within their local tissue rather than projecting across long distances. A local circuit neuron that connects nearby cells, usually releasing inhibitory GABA to shape firing rhythms, sharpen sensory contrast, and prevent runaway excitation.',
  neuromodulator: 'From Greek neuron (nerve) and Latin modulator (one who measures or regulates, from modulari "to tune" and modus "measure"). Coined in modern neurobiology to distinguish diffuse, widespread chemical signaling from fast point-to-point synaptic transmission. A chemical messenger (such as dopamine, serotonin, or noradrenaline) released broadly to tune overall circuit sensitivity, mood, or attention.',
  myelin: 'From Greek myelos (marrow, pith, or innermost core). German pathologist Rudolf Virchow named it in 1854 because he believed the thick, glistening white fatty coating surrounding nerve fibers resembled the soft marrow inside bones. An insulating lipid sheath produced by glial cells that wraps around axons in spaced segments, allowing electrical action potentials to leap down the wire up to 100 times faster.',
  ataxia: 'From Greek ataxia (lack of order, confusion, or irregularity, from a- "without" and taxis "order"). Ancient medical term redefined in 19th-century neurology to describe clumsy, uncoordinated movement without muscle paralysis. A neurological condition, typically resulting from cerebellar damage, characterized by unsteady drunken-like gait, shaky limb movements, overshoot when reaching, and slurred speech.',

  // =========================================================================
  // 3. CELL TYPES (NEURONS & GLIA)
  // =========================================================================

  'pyramidal cell': 'From Latin pyramis (pyramid, from Greek pyramis) and cell (Latin cella, small chamber). Named by 19th-century histologists because its triangular cell body resembles an Egyptian pyramid, tapering into a tall apical dendrite that climbs toward the surface like a church spire. The principal excitatory neuron of the cerebral cortex and hippocampus, releasing glutamate to send long-distance signals.',
  'granule cell': 'From Latin granulum (a tiny grain, seed, or crumb), diminutive of granum (grain). Early microscopists examining the cerebellar cortex and dentate gyrus saw swathes of tiny, rounded cell bodies packed so tightly that they looked like fine sand or cornmeal under the lens. Tiny, densely packed excitatory neurons that filter and distribute sensory inputs; the cerebellum holds tens of billions of them.',
  'Purkinje cell': 'Named after Czech anatomist Jan Evangelista Purkyně, who discovered them in 1837 using an early compound microscope. He described their enormous, fan-shaped dendritic trees that spread out in a single plane like delicate sea fans. Located in the cerebellar cortex, they are the sole output cells of the cerebellum, releasing inhibitory GABA to sculpt smooth, well-timed physical movements.',
  'purkinje cell': 'Named after Czech anatomist Jan Evangelista Purkyně, who discovered them in 1837. These giant cerebellar output neurons possess vast fan-like dendritic trees and release inhibitory GABA to coordinate smooth muscle timing.',
  'stellate cell': 'From Latin stellatus (starry or set with stars, from stella "star"). Named by 19th-century anatomists because their dendrites radiate outward symmetrically in all directions from the central cell body, resembling a twinkling star or firework. Compact local interneurons found throughout the cerebral cortex and cerebellum, integrating nearby incoming signals and providing rapid local inhibition or feedforward relay.',
  'basket cell': 'From Old French bascat and Latin bascauda (basket). Santiago Ramón y Cajal described how the axon terminals of these inhibitory interneurons wrap intimately around the cell body of a target neuron, cradling the soma like a woven wicker basket. Powerful inhibitory interneurons that clamp down directly onto the cell bodies of principal neurons, delivering fast, decisive braking to synchronize network rhythms.',
  'chandelier cell': 'From French chandelier (candleholder), from Latin candelabrum (candle tree). Named in the 1970s by Hungarian-American neuroanatomist János Szentágothai because its vertical axon terminals hang in parallel rows like strings of sparkling crystal candles on an ornate ballroom chandelier. A specialized inhibitory interneuron that synapses exclusively onto the axon initial segments of pyramidal cells, vetoing spikes at the trigger zone.',
  'medium spiny neuron': 'From Latin medius (intermediate), Old English spin (spine or thorn), and Greek neuron. Named for its intermediate cell body size and the dense coat of thousands of tiny, mushroom-shaped spines that carpet its dendrites under Golgi staining. Making up roughly 95% of all neurons in the striatum, these GABA-releasing cells calculate reward expectations and funnel basal ganglia decisions into "go" or "no-go" motor pathways.',
  MSN: 'Abbreviation for medium spiny neuron. The primary GABA-releasing projection neuron of the striatum, covered in dense dendritic spines that integrate glutamate and dopamine signals to guide action selection and habit learning.',
  'thalamic relay neuron': 'From Greek thalamos (inner room), Old French relaier (to replace or relay, referring to fresh post-horses), and Greek neuron. Clustered within the sensory and motor nuclei of the thalamus, projecting bundled axons through the internal capsule to the cortex. An excitatory neuron that receives incoming sensory signals, switches between burst and single-spike modes, and forwards sensory data to the cerebral cortex.',
  'dopamine neuron': 'Chemical abbreviation DOPA (dioxyphenylalanine) plus amine and Greek neuron. Clustered predominantly in the substantia nigra and ventral tegmental area of the midbrain, identified histologically by their dark neuromelanin granules and branched axonal trees. Neuromodulatory cells that broadcast dopamine across the brain to signal reward prediction errors, motivate effort, and initiate voluntary movement.',
  'motor neuron': 'From Latin motor (mover, from movere "to move") and Greek neuron. Located in the ventral horn of the spinal cord and cranial nerve nuclei of the brainstem, these are among the largest cells in the body, with cell bodies reaching 0.1 mm across and axons extending over a meter. The final common pathway for physical action, sending electrical pulses directly to skeletal muscle fibers to provoke contraction.',
  astrocyte: 'From Greek astron (star) and kytos (hollow vessel or cell). Named in 1893 by Hungarian anatomist Mihály Lenhossék because under metallic silver and gold stains, its myriad radiating branches resemble glowing, star-shaped constellations. Star-shaped glial cells that maintain the blood-brain barrier with endfeet, feed neurons lactate, recycle spilled glutamate, and buffer extracellular potassium.',
  oligodendrocyte: 'From Greek oligos (few), dendron (tree), and kytos (cell), literally "cell with few branches." Named in 1921 by Spanish neuroscientist Pío del Río-Hortega, who used a silver carbonate stain to show these cells have fewer, simpler branches than astrocytes. The myelin-producing glia of the central nervous system, wrapping insulating myelin sheaths around up to 50 separate axon segments simultaneously.',
  microglia: 'From Greek mikros (tiny, small) and glia (glue). Discovered and named in 1919 by Spanish neuroscientist Pío del Río-Hortega, who distinguished these tiny, mobile cells from larger neuroglia, identifying their distinct origin in embryonic yolk sac tissue. The resident immune cells and cleanup crew of the brain, constantly waving mobile arms to inspect tissue, devour cellular debris, prune weak synapses, and fight infections.',

  // =========================================================================
  // 4. CHEMICAL MESSENGERS & HORMONES
  // =========================================================================

  dopamine: 'Chemical abbreviation from di-oxy-phenylalanine (DOPA) and amine. Synthesized in 1910, Swedish pharmacologist Arvid Carlsson proved in 1957-1958 that it was an independent neurotransmitter concentrated in the basal ganglia, earning the 2000 Nobel Prize. A neuromodulator released from the midbrain that drives motivation, reward prediction, learning, and the fluid initiation of physical movement.',
  serotonin: 'From Latin serum (blood serum), Greek tonos (tension or tone), and the chemical suffix -in. Isolated in 1948 by Maurice Rapport, Arda Green, and Irvine Page as a serum compound that constricts blood vessels; identified in the brain in 1953 by Betty Twarog. A neuromodulator made in the brainstem raphe nuclei that projects across the brain to stabilize mood, promote emotional patience, regulate sleep cycles, and signal satiety.',
  noradrenaline: 'From French and German nor- (nitrogen without radical) and Latin ad (at or near) plus renes (kidneys). Identified by Swedish physiologist Ulf von Euler in the mid-1940s as the primary chemical messenger of sympathetic nerves and brain alerting circuits. The brain\'s alertness and vigilance transmitter, released by the locus coeruleus to sharpen attention, widen pupils, accelerate heart rate, and prepare the mind and body for action.',
  norepinephrine: 'From Greek epi (upon) and nephros (kidney), the American medical term for noradrenaline. Released by the locus coeruleus and sympathetic nerves to spark high vigilance, sharpen sensory focus, and mobilize body energy during stress or sudden novelty.',
  acetylcholine: 'From Latin acetum (vinegar, for the acetyl group) and Greek chole (bile, for choline, first isolated from ox bile in 1862). The first neurotransmitter ever identified, discovered by Henry Dale in 1914 and proven in frog hearts by Otto Loewi in 1921. It triggers voluntary muscle contractions at neuromuscular junctions; inside the brain, it acts as an attention spotlight, promoting wakefulness, focus, and memory encoding.',
  glutamate: 'From Latin gluten (glue, from its discovery in wheat gluten by German chemist Karl Heinrich Ritthausen in 1866) and the chemical suffix -ate. Japanese chemist Kikunae Ikeda discovered in 1908 that it produces the savory taste umami; in the 1950s to 1970s, neuroscientists demonstrated it acts as the primary chemical stimulant of the brain. The chief fast excitatory neurotransmitter in the central nervous system, used by over half of all brain synapses.',
  GABA: 'Acronym for gamma-aminobutyric acid, from Latin butyrum (butter, from Greek boutyron), because butyric acid was first isolated from rancid butter. Synthesized in 1883, its widespread presence and inhibitory role in the mammalian brain was discovered in 1950 by Eugene Roberts and Sam Frankel. The primary fast inhibitory neurotransmitter of the mature central nervous system, opening chloride channels to quiet firing, prevent sensory overload, and avert seizures.',
  adrenaline: 'From Latin ad (near) and renes (kidneys), referring to the adrenal glands perched atop the kidneys. First isolated in pure crystalline form in 1901 by Jokichi Takamine and Thomas Bell Aldrich. The primary fight-or-flight hormone released by the adrenal medulla during stress, surging through the bloodstream to boost heart rate, open airways, and mobilize glucose for emergency action.',
  epinephrine: 'From Greek epi (upon) and nephros (kidney), the American pharmacological name for adrenaline. A rapid hormone and chemical messenger that triggers the fight-or-flight response, accelerating heart rate, dilating bronchioles, and preparing the body for immediate exertion.',
  cortisol: 'From Latin cortex (bark or outer shell, referring to the adrenal cortex) and the chemical suffix -ol for a steroid alcohol. Isolated from adrenal gland extracts in the 1930s by Edward Kendall and Tadeus Reichstein (1950 Nobel Prize). The primary glucocorticoid stress hormone, released by the adrenal cortex under hypothalamic-pituitary command to elevate blood sugar, regulate metabolism, and dampen inflammation during prolonged challenge.',
  oxytocin: 'From Greek oxys (swift or quick) and tokos (childbirth or labor), meaning "swift birth." Named by British pharmacologist Sir Henry Dale in 1906 after discovering that pituitary extracts triggered uterine contractions. A peptide hormone made in the hypothalamus and released by the posterior pituitary, stimulating labor and milk release, while promoting social bonding, trust, empathy, and maternal care in the brain.',
  vasopressin: 'From Latin vas (vessel) and pressus (pressed or squeezed, from premere "to press") plus the chemical suffix -in. Discovered in pituitary extracts for its ability to raise blood pressure by constricting blood vessels, also known as antidiuretic hormone (ADH). Produced by the hypothalamus and released by the posterior pituitary to instruct kidneys to conserve water; in the brain, it influences social recognition, pair bonding, and territorial behavior.',
  melatonin: 'From Greek melas (black or dark) and tonos (tension) or serotonin. Discovered in 1958 by dermatologist Aaron B. Lerner, who isolated it from pineal glands after noticing it caused frog skin cells to lighten by aggregating dark melanin granules. The darkness hormone synthesized by the pineal gland during nighttime hours, released into the bloodstream and cerebrospinal fluid to regulate circadian sleep-wake cycles.',
  'thyroid hormone': 'From Greek thyreoeides (shield-shaped, from thyreos "oblong shield" and eidos "form"), named because the thyroid gland resembles an ancient Greek warrior shield. In the body and brain, thyroid hormones (T3 and T4) govern cellular metabolic rate, oxygen consumption, protein production, and brain development.',
  leptin: 'From Greek leptos (thin, slender, or delicate). Discovered in 1994 by Jeffrey Friedman and colleagues during research into mouse obesity genetics. An endocrine hormone produced by adipose (fat) cells that signals total bodily energy reserves to the hypothalamus, suppressing appetite and encouraging calorie expenditure.',
  ghrelin: 'Coined as an acronym for Growth Hormone RELEase INducing, and playing on the Proto-Indo-European root ghre ("to grow"). Discovered in 1999 by Masayasu Kojima and Kenji Kangawa. The body\'s primary meal-initiating signal, released by empty stomach walls to activate hypothalamic circuits that trigger hunger and food-seeking.',
  'growth hormone': 'From Old English growan (to grow) and Greek horman (to set in motion). Isolated from pituitary glands in the mid-20th century. A peptide hormone released by the anterior pituitary that stimulates bone elongation, protein synthesis, tissue repair, and the breakdown of fats for bodily energy.',
  'sex hormones': 'From Latin sexus (gender or division) and Greek horman (to spur on). Includes estrogens, progesterone, and testosterone, derived from cholesterol in the gonads and adrenal cortex. Beyond reproduction, they cross into the brain to sculpt neural circuits, regulate mood, and influence spatial and verbal processing.',
  prolactin: 'From Latin pro (forward or in favor of) and lac (genitive lactis, meaning milk). Discovered in 1928 by Paul Stricker and Joseph Grueter for stimulating milk secretion. An anterior pituitary hormone that drives milk production after birth and acts inside the brain to foster nurturing behavior and parental bonding.',

  // =========================================================================
  // 5. SENSORY RECEPTORS & ANCHORS
  // =========================================================================

  retina: 'From Medieval Latin retina, likely from Latin rete (a net), describing the delicate, net-like lattice of photoreceptors and microscopic blood vessels spread across the back of the eye. The sensory sheet of the eye that translates photons of light into electrical impulses for the brain.',
  eye: 'From Old English eage (eye). The paired sensory organ that focuses incoming light through the cornea and lens onto the retina, initiating all visual sensations.',
  cochlea: 'From Greek kochlias (a spiral snail shell). Named by early anatomists for its coiled, snail-like bony spiral nestled deep inside the temporal bone. It contains the organ of Corti, where tiny sensory hair cells vibrate to sound waves and convert acoustic pitches into electrical signals.',
  ear: 'From Old English eare (ear). The organ of hearing and balance, collecting sound waves through the ear canal and converting pressure waves into nerve impulses in the inner ear.',
};
