// Glossary. Write [[term]] or [[term|shown text]] in any text field and the explainer
// underlines it with a hover definition. Matching ignores case and a trailing "s".
export default {
  neuron: 'A nerve cell. It collects signals on its branches and, if they add up, fires a pulse down its axon to other cells.',
  axon: 'The long output wire of a neuron. It carries the electrical pulse away from the cell body.',
  dendrite: 'The branching input side of a neuron, where it receives signals from other cells.',
  synapse: 'The tiny gap where one neuron passes a signal to the next, usually by releasing a chemical.',
  neurotransmitter: 'A chemical messenger released at a synapse, such as glutamate, GABA or dopamine.',
  receptor: 'A protein on the receiving cell that a neurotransmitter locks into, like a key in a lock.',
  'action potential': 'The brief electrical pulse (a "spike") a neuron fires to send a message.',
  excitatory: 'Makes the receiving neuron more likely to fire.',
  inhibitory: 'Makes the receiving neuron less likely to fire.',
  cortex: 'The thin, folded outer sheet of the brain, about 2–4 mm thick.',
  'grey matter': 'Tissue packed with cell bodies. The cortex and deep nuclei are grey matter.',
  'white matter': 'Bundles of axons wrapped in fatty insulation (myelin) that connect brain areas.',
  hemisphere: 'One half of the brain, left or right.',
  lobe: 'One of the big named regions of each hemisphere: frontal, parietal, temporal, occipital.',
  gyrus: 'A ridge on the surface of the brain.',
  sulcus: 'A groove between two ridges on the brain surface.',
  nucleus: 'In the brain, a compact cluster of neurons that work together (not the cell nucleus).',
  'pyramidal cell': 'The main excitatory neuron of the cortex, named for its triangular cell body.',
  'granule cell': 'A very small, very numerous neuron. The cerebellum has tens of billions.',
  'Purkinje cell': 'A large neuron in the cerebellum with a huge, flat, fan-shaped tree of dendrites.',
  interneuron: 'A local neuron that connects nearby cells, often inhibitory, shaping the timing of a circuit.',
  dopamine: 'A neuromodulator linked to reward, motivation and smooth movement.',
  glutamate: 'The most common excitatory neurotransmitter in the brain.',
  GABA: 'The most common inhibitory neurotransmitter in the brain.',
  neuromodulator: 'A chemical that changes how a whole region responds, rather than sending one precise message.',
  ataxia: 'Clumsy, poorly coordinated movement, usually caused by cerebellum damage.',
  myelin: 'A fatty coating around axons that makes signals travel much faster.',
};
